frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
1. kubelet probe failed with envoy redirect to auth
2. reinjection if a pod already has set sidecar config
1. fixed: kubelet probe failed with envoy redirect to auth
2. fixed: reinjection if a pod already has set sidecar config

fixed: kubelet probe failed with envoy redirect

---

apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml

Bug fix
contact and chainId use op main chain

build: update settings version to v0.1.60

---

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
apps/argo/config/user/helm-charts/recommend/templates/argo_fe_deploy.yaml
apps/devbox/config/user/helm-charts/devbox/templates/deployment.yaml
apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
third-party/seahub/config/user/helm-charts/seafile/templates/seafile_fe_deploy.yaml

`bug fix`
add a single quote to username helm values to avoid the numeric username breaking

add a quote to username

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

* `bug fix`: remove recursive dir listing

remove recursive dir listing

---

apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
build/installer/install_cmd.sh
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

*  `feature` use Cloudflare tunnel as an FRP alternative
* **Does this PR introduce a breaking change?** 
*  NO

use Cloudflare tunnel as an FRP alternative

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

build: update vault & files version to v0.4.55

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml

- bug fix: feed and entry query api

build: update wise and knowledge version to v0.1.23

---

build/installer/install_cmd.sh

check if the server is an AWS server and if it has a public IP. If the conditions are met, set selfhosted to false

fixed: check if it is an AWS server and modify the value of selfhosted.

---

apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml

Added three environment variables to the Settings Server. This allows testers to switch to the test environment without updating the image.
No

Added three environment variables to the Settings Server.

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

* `improvement` decrease l4 proxy nginx worker processes to reduce memory usage

decrease l4 proxy nginx worker processes

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
install operation failed but not clean resource
do a source clean operation when install failed
NO

fix: source clean when install failed

---

build/installer/upgrade_cmd.sh
third-party/pg_vectors/Dockerfile
third-party/pg_vectors/README.md

`bug fix` a breaking bug in the upgrade script 
`feature` create a pgvecto.rs extension integrating docker file  for the coming soon feature

pgvecto.rs dockerfile & fix upgrade script bug

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
get terminus release version error
fix: get terminus release version error when data is empty

Bug fix: fit get terminus release version response

---

apps/nitro/config/cluster/deploy/dify_deploy.yaml

Bug fix: Dify deploy: fix nginx bug when loading model or with old cookie

Bug fix: Dify deploy: fix nginx bug when loading model or with old cookie

---

apps/devbox/config/user/helm-charts/devbox/templates/deployment.yaml

Upgrade Devbox to v0.1.26
Changes: https://github.com/beclab/devbox/releases/tag/v0.1.26

Upgrade Devbox to v0.1.26. Changes: https://github.com/beclab/devbox/releases/tag/v0.1.26

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

Modification: io.Copy from/to Drive/Cache when pasting in diff archs

Modification: io.Copy from/to Drive/Cache when pasting in diff archs

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

fix: update func pingLoadData for local

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: control-hub scrollbar in windows

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

Bug fix
create second user but with empty email
correct user email field
NONE

fix: create second user but empty email

---

apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml

fix: wizard update links

---

apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml

Bug fix
https://github.com/beclab/settings/pull/1
https://github.com/beclab/settings/pull/2

build: update settings version to v0.1.62

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

Modification: file size exceeds 4GB error text stressed (backend only, still need frontend changing)

Modification: file size exceeds 4GB error text stressed

---

build/installer/install_cmd.sh

fixed: adds support for operating systems including Ubuntu 20, 22, 24, and Debian 11, 12. Specifically, it upgrades AppArmor to version 4.0.1 for Ubuntu 24 to ensure system security and compatibility.

fix: add os version support and verify apparmor and upgrade

---

.github/workflows/release-daily.yaml
.github/workflows/upload-full.yaml
build/installer/publicInstaller.latest

`workflow`:  upload full release package to s3

upload full package to s3

---

apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml

Bug fix
https://github.com/beclab/settings/pull/3

build: release settings new version to v0.1.63

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix, multiple file uploads

fix: multiple file uploads

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

Bug fix
https://github.com/beclab/TermiPass/pull/26

build: release vault & files version to v0.4.61

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

- [ X] The commit message follows our guidelines
- [ X] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)
Fix modifications that cause errors during installation.

Fix files deploy issue

---

build/installer/install_cmd.sh

`improvement` format fatal error log for terminus space crawling

format fatal error log

---

frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml

`bug fix`: set header x-bfl-user for legacy proxy request

set header x-bfl-user for legacy proxy request

---

apps/nitro/config/cluster/deploy/dify_deploy.yaml

bugfix: dify document indexing bug fixed (both economical and high-quality methods)

bugfix: dify document indexing bug fixed (both economical and high-quality methods)

---

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml

Modification: 
- dify-gateway: Only watch dify supported files

Modification: dify-gateway: Only watch dify supported files

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

Modification: 
- market: backend remove mongo

Modification: market backend remove mongo

---

frameworks/backup-server/config/cluster/deploy/backup_server.yaml

feat: add multiple return fields to the backup list interface according to the interface

build: backup-server up to v0.3.7

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

Modification: 
- files: Modify Knowledge Base related providers to fit frontend design

Modification: files: Modify Knowledge Base related providers to fit frontend design

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/devbox/config/user/helm-charts/devbox/templates/deployment.yaml
apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

Fix/update 1.4 icon

---

.githooks/commit-msg
.githooks/git-hooks-config.sh
.github/workflows/check.yaml
.github/workflows/release-daily.yaml

`ci`: add validating step to workflow and git-hook to the code committing

ci: add validating step to workflow and git-hook to the code committing

---

build/installer/upgrade_cmd.sh

`bug fix`：system upgrading will be broken in multi-user mode

fix: system upgrading will be broken in multi-user mode

---

README.md

* docs: update readme to include more comprehensive and accessible sections, status badges, links

docs: update readme to be more comprehensive and accessible 

---

README.md

docs: fix image display issue

---

build/installer/install_cmd.sh
build/manifest/images

feat: add check for the existence of local dependency files

feat: add check for the existence of local dependency files

---

build/installer/change_ip.sh
build/installer/uninstall_cmd.sh

`bug fix`: unable to update changed local IP when Cloudflare tunnel enabled

fix: unable to update changed local IP when Cloudflare tunnel enabled

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
gpu limit inject will override deployment/statefulset resource requests
gpu limit inject does not override  deployment/statefulset resource requests
NONE

fix: gpu limit inject override resource requests

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/nitro/config/cluster/deploy/dify_deploy.yaml

fix: 
- files: add quatation mark to BFL_NAME
- dify: modified lua script to fix a auto login bug with old cookie

fix: add quatation mark to BFL_NAME in files and fix a dify auto login bug with old cookie

---

build/installer/change_ip.sh

`bug fix`: After the system IP is changed, some Pods may sometimes run abnormally.  Restart to ensure the IP change is successful.

fix: restart some pods to make sure the system recovery

---

.github/workflows/push-deps-to-s3.yml

feat: add build artifact for pushing dependency files to S3

feat: add build artifact for pushing dependency files to S3

---

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/nitro/config/cluster/deploy/dify_deploy.yaml

modification:
- files&dify-gateway: Modify Knowledge Base related providers to fit frontend design
- dify-gateway: Only watch dify supported file types
fix:
- dify: modified lua script to fix a auto login bug with old cookie
- files: can't get default dataset bug

feat: knowledge base related providers in files and dify-gateway

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

fix: 
- files: fix files can't get default dataset bug

fix: files can't get default dataset bug

---

build/manifest/dependencies
scripts/build-full.sh
scripts/deps-manifest.sh
scripts/download-deps.sh
scripts/save-deps.sh
scripts/upload-deps.sh

fix: script improvement, add offline installation script for Terminus in K8s environment

fix: support offline installation packages for k8s

---

build/installer/install_cmd.sh
build/manifest/dependencies

fix: copy pre-installation dependency files to the installation directory

fix: copy pre-installation dependency files

---

build/installer/change_ip.sh
build/installer/version.hint
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

`fix`: lower the minimum upgradable version to accept the daily build version upgrading

fix: lower the minimum upgradable version

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
frameworks/app-service/config/cluster/crds/app.bytetrade.io_imagemanagers.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

feature
app install don't have image downloading progress
add downloading progress for app image pull

feat: add downloading progress for app image pull

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml

feature: font subset optimizes loading speed

feat: add font subset

---

build/installer/install_cmd.sh
build/manifest/images

fix: pull velero image failed

---

apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: controhub and dashboard icon woff update

---

build/installer/install_cmd.sh

feat: add Orion GPU container runtime pod running status check to make sure other GPU-required pods  can be injected GPU runtime drivers

feat: add orion gpu container-runtime pod running status check

---

README.md

feat: update readme with multiple sections, diagrams, tables

---

README.md

fix: fix table formatting in readme

---

.github/workflows/push-gpudeps-to-s3.yml
build/installer/install_cmd.sh
scripts/upload-gpu-deps.sh

feat: ubuntu gpu dependency file collection, add Ubuntu version support check when installing GPU packages

feat: ubuntu gpu dependency file collection and push to S3

---

README.md

fix: optimize feature comparison table

---

README.md

docs: Add <br> behind juciefs

---

apps/nitro/config/cluster/deploy/dify_deploy.yaml

modification: 
- dify/nitro: configurable using NITRO or WASM

feat: configurable using NITRO or WASM

---

README.md

fix: add new badges and fix wording

---

.github/workflows/release-daily.yaml
build/installer/uninstall_cmd.sh
frameworks/GPU/config/gpu/templates/container-runtime.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

`bug fix`: orion gpu runtime broken on Ubuntu 22.04

fix: orion gpu runtime broken on Ubuntu 22.04

---

frameworks/tapr/config/cluster/deploy/mongodb_deployment.yaml

`improvement`: increase MongoDB resource limit

fix: increase mongodb resource limit

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

fix:
- files: paste to sync timeout

fix: files paste timeout

---

build/installer/uninstall_cmd.sh

fix: support deletion operations for oss during uninstallation

fix: support deletion operations for oss during uninstallation

---

frameworks/osnode-init/config/cluster/deploy/nodeinit_daemonset.yaml

`feature`: add retry to refresh sts token.

feat: add retry to refresh sts token

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: controlHub middleware list

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: control-hub workloads

---

apps/argo/config/user/helm-charts/argo/templates/argo_deployment.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/tapr/config/cluster/crds/apr.bytetrade.io_middlewarerequests.yaml
frameworks/tapr/config/cluster/crds/apr.bytetrade.io_pgclusters.yaml
frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml

feature 
can not execute script after creaet database
postgresql add support extension and execute script;mongo add support execute script

feat: postgresql support extension and execute script;mongo support execute script

---

build/installer/install_cmd.sh
build/manifest/images

fix: velero image pull timeout causing k3s installation failure

fix: velero image pull timeout causing k3s installation failure

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

`bug fix`: Currently, the system upgrader always does the upgrading via the latest version.  Use the version got from Terminus Space instead.

fix: use the release version got from Terminus Space to upgrade the OS.

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

feat: Desktop and login add ways to open mobile browser bookmarks

---

apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml
third-party/seahub/config/user/helm-charts/seafile/templates/seafile_fe_deploy.yaml

fix:
- seafile: remove public accessible ui
- dify: add dify URL auth

fix: remove seafile ui and add dify auth

---

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
apps/nitro/config/cluster/deploy/dify_deploy.yaml

fix:
- nitro: add size limit for nitro.log
- dify-gateway: change Ashia type from agent to chatbot, and auto set whole model config to make it run more stable

fix: nitro relative bugs

---

.github/workflows/check.yaml

`ci/cd`: add installing test to ci workflow

ci: add installing test

---

apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
apps/argo/config/user/helm-charts/argo/templates/argo_deployment.yaml

feat: argo change pg

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

feature: system app adapts theme

feat: dark theme main

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

feature: system app adapts theme

feat: dark theme release 1.5

---

build/installer/install_cmd.sh

`optimize`: save terminus data in a separate disk

feat: save terminus data in a separate disk

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

feat: add controlhub service configmaps secrets yaml editor

---

third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml

feat: tailscale support arm64

---

frameworks/tapr/config/cluster/deploy/citus_deployment.yaml

`feat`: citus arm64 supported
citus version: 12.0
PostgreSQL version: 14.8

feat: citus arm64 supported

---

apps/system-apps/config/cluster/deploy/ks_server_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

feat: User Group (Control Hub/Browse)

---

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/nitro/config/cluster/deploy/dify_deploy.yaml
third-party/seahub/config/cluster/deploy/seafile_deploy.yaml

feat:
- seafile: our seahub and nginx-lua support arm64
- dify: our dify-api and nginx-lua support arm64
- nitro: our nitro support arm64
- files: our files-server and appdata-gateway support arm64
- agent: our dify-gateway support arm64

feat: seafile/files/dify/nitro arm64 support

---

apps/argo/config/user/helm-charts/argo/templates/argo_deployment.yaml

Bug fix
no usage middlewarerequest of mongodb exist
fix: rm no usage middlewarerequest of mongodb

fix: rm no usage middlewarerequest of mongodb

---

apps/nitro/config/cluster/deploy/dify_deploy.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

change:
- nitro: Only nitro and nginx in nitro, while commented other codes and remaining dify DNS for market using.

feat: only nitro and nginx in nitro now

---

build/installer/install_cmd.sh

fix: velero image pull timeout

fix: velero image pull timeout

---

apps/nitro/config/cluster/deploy/dify_deploy.yaml

fix:
- nitro: remove dify yaml bug

fix: nitro-dedify yaml bug

---

build/installer/install_cmd.sh
build/installer/uninstall_cmd.sh
build/manifest/dependencies

Bug fix
second user of terminus can not visit applicationmanagers resource
fix: add applicationmanagers,imagemanagers permission for workspaces-manager role

fix: add applicationmanagers,imagemanagers permission for workspaces-manager role

---

third-party/seahub/config/cluster/deploy/seafile_deploy.yaml

fix:
- seahub: fix seahub.tags not found bug

fix: seahub tags not found bug

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

`fix`: keep dify-ui in built-in apps

fix: keep dify-ui in built-in apps

---

apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml

`fix`: make the dify-ui entrance invisible

fix: make the dify-ui entrance invisible

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

fix:
- appservice: remove agent

fix: remove agent from appservice

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: update ControlHub/CRDs yaml button text in UI

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/nitro/config/cluster/deploy/dify_deploy.yaml
apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml

fix:
- files: configurable dify provider call; aboveos in appdata updated
- nitro: dify model set removed
- dify-ui: nginx service commented

fix: remove dify provider from files, dify model from nitro, aboveos in appdata and dify ui for the time being

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/nitro/config/cluster/deploy/dify_deploy.yaml
third-party/seahub/config/cluster/deploy/seafile_deploy.yaml

fix:
- files: server arm64 support bug; gateway update to newest server
- seahub: nginx-lua arm64 support bug
- nitro: nginx-lua arm64 support bug

fix: files & nginx-lua arm64 support bug

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml

feature: update wise to v0.1.30

feat: update wise version

---

build/installer/install_cmd.sh

fix: release version check bug
fix: check raspberry pi

fix: release version check bug

---

.github/workflows/check.yaml
.github/workflows/release-daily.yaml
build/installer/version.hint

ci: bump to 1.7.0

---

build/installer/install_cmd.sh
build/manifest/images

`feature`: support Raspbian arm64 version on Raspberry Pi 5
`feature`: bump k3s to 1.22.16
`feature`: preload image by kubekey instead of k3s
`fix`: update citus image version tag in the image manifest

feat: support raspbian arm64 version

---

build/installer/install_cmd.sh
build/installer/uninstall_cmd.sh
build/manifest/dependencies.amd64
build/manifest/dependencies.arm64

* fix: velero update, add wait-minute
* feat: velero upgrade to v1.11.2

fix: velero update, add wait-minute

---

build/installer/install_cmd.sh

`feature`: support installing Terminus OS on WSL2 Ubuntu-22.04 in Windows 11

feat: support WSL2 Ubuntu-22.04 in Windows 11

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

feat: add media server for files

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

feat: File supports video

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml

Refactor
- support  caller auth
- support forwarding of the same path for different applications 

refactor: legacy api with envoy sidecar

---

build/installer/install_cmd.sh
build/installer/publicAddnode.sh
build/manifest/images.node.mf
scripts/image-manifest.sh

`feature`: support adding arm64 worker node

feat: support adding arm64 worker node

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

feat: update market to v0.2.8

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml

feature
add api intent v2 provider registry

feat: add api intent v2 provider registry

---

apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml

feat: update profile version to v0.3.23

feat: update profile version to v0.3.23

---

apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

chore: optimize controlhub and dashboard build configuration

---

build/installer/install_cmd.sh
build/manifest/images

fix: support raspbian & bump k3s to 1.22.16

fix: support raspbian & bump k3s to 1.22.16

---

scripts/package.sh

ci: add macos installation script to installer package

ci: add macos installation script to installer package

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

feat: update build for quasar.config

---

frameworks/tapr/config/cluster/deploy/citus_deployment.yaml

feature
postgres does not have support for zhparser extension
add postgres extension zhparser

feat: add postgres extension zhparser

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: delete ControlHub/Middleware/ZincSearch

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

fix: for special characters in path

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

change:
- files: remove zinc and dify-gateway provider call

feat: files remove zinc and dify-gateway provider call

---

scripts/developer/install_macos.sh

fix: installing bugs on macos

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

feat: support open id connect

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

change:
- files: Revert "feat: files remove zinc and dify-gateway provider call (#207)"

feat: Revert "feat: files remove zinc and dify-gateway provider call (#207)"

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml

fix: fix knowledge auto restart

---

.github/workflows/release-daily.yaml
.github/workflows/upload-full.yaml
build/installer/install.sh
build/installer/publicInstaller.latest

feat: quick install script for macos & wsl & Raspberry Pi

feat: quick install script for macos & wsl & Raspberry Pi

---

README.md

- [] The commit message follows our guidelines
- [] Tests for the changes have been added (for bug fixes / features)
readme doc

docs: update home cloud as project positioning

---

build/installer/change_ip.sh

fix: change ip for wsl

---

build/installer/change_ip.sh
build/installer/install.sh
build/installer/install_cmd.sh
build/installer/publicAddnode.sh
build/installer/publicInstaller.latest
build/installer/uninstall_cmd.sh

fix: os arch check for macos

---

build/installer/install.sh
build/installer/publicInstaller.latest

fix: downloading the wrong package

fix: downloading the wrong package

---

README.md

1. New opening for Home Cloud positioning
2. Unify Terminus usage 
3. New Get Start guides

docs: adjust readme message for home cloud positioning and other updates

---

build/installer/install_cmd.sh

fix: installing bug on wsl in release 1.6

fix: installing bug on wsl in release 1.6

---

README.md

docs: further fix Web3 related wording and other formatting issues

---

apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml

fix: fix dashboard layout bug in windows

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

- chore: change vite to webpack
- fix: the source of the dev application is empty when it is not installed
- fix: change the status of the No Available entrances app from open to running
- fix: update semantic version check

feat: update market version to v0.2.10

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

feat: add controlhub/storages

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml

feat: Added initial support for Google Drive and Dropbox in Files.

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml

fix: fix knowledge corrunption auto restart in release-1.6

---

build/installer/install_cmd.sh
build/manifest/dependencies.amd64
build/manifest/dependencies.arm64
build/manifest/images

fix: add velero create crds retries

fix: add velero create crds retries

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

nusManifest.yaml
feature
add options for set envoy outbound and inbound timeout in TerminusManifest.yaml

feat: add options for set envoy outbound and inbound timeout

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

feat: update desktop&login&settings bg pictures

---

build/installer/install_cmd.sh
build/installer/uninstall_cmd.sh
build/installer/wizard/config/account/templates/account.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
scripts/developer/install_macos.sh
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

feature: optimize installing on raspbian and wsl
feature: support nat mode

feat: installation optimize

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/search3/config/cluster/deploy/search3_server_deploy.yaml

feat: 1. add library entry to search pg 2. add get resource by uri router

---

build/installer/install_cmd.sh

fix: check raspberry

---

build/installer/deploy/device-plugin.yaml
build/installer/deploy/nvidia-device-plugin.yml
build/installer/deploy/nvshare-system-quotas.yaml
build/installer/deploy/nvshare-system.yaml
build/installer/deploy/scheduler.yaml
build/installer/install_cmd.sh
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

feat:  add explicit runtime class for nvidia to support wsl

feat:  add explicit runtime class for nvidia to support wsl

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

[feature] [Bug fix]
Update files and video

feat: update files version to v1.2.14

---

build/installer/install_cmd.sh
build/manifest/images

fix: installing gpu bugs on wsl

fix: installing gpu bugs on wsl

---

frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml

feature
system-server proxy add support for sse/x-ndjson

feat: system-server proxy add support for sse/x-ndjson

---

apps/files/config/cluster/deploy/files_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml

change:
- files: move gateway, files-server to os-system (with a nginx together), left watcher disabled for the time being

feat: files to os-system

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

feat: add controlhub/jobs and controlhub/browse/pod monitoring

---

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feat: support gdrive and dropbox drive

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml

feature
add api for get provider registry list by appname

feat: get provider registry list by appname

---

apps/files/config/cluster/deploy/files_deploy.yaml
build/installer/deploy/device-plugin.yaml
build/installer/deploy/scheduler.yaml
build/installer/install_cmd.sh
build/installer/install_macos.sh

feat: support switching jfsnotify to fsnotify

feat: support switching jfsnotify to fsnotify

---

apps/files/config/cluster/deploy/files_deploy.yaml

files:
- optimize pvc search
- add headless service and remove node selector from appdata-backend daemonset to ensure cache working
- fix rename bug
- fix the bug when pasting/moving files with transcode url between different architectures
- add api/cache prefix proxy for cache
- jfsnotify version v0.0.1->v0.0.2

fix: files_os_system bugs

---

build/installer/install_cmd.sh

fix: ntpdate error

---

build/manifest/images
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

fix: modify l4 imagePullPolicy

fix: modify l4 imagePullPolicy

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
apps/profile/config/user/helm-charts/profile/templates/profile_deployment.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml
build/installer/deploy/device-plugin.yaml
build/installer/deploy/scheduler.yaml
build/installer/install_cmd.sh
build/manifest/images
third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml

fix: optimize the os restart process

fix: optimize the os restart process

---

build/installer/install_macos.sh

fix: minikube install

---

build/installer/install_macos.sh

fix: upgrade installer

---

apps/files/config/cluster/deploy/files_deploy.yaml

feat: support playing videos in Data and Cache

---

apps/files/config/cluster/deploy/files_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feat: files_1.7

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: fix controlhub/jobs job actions

---

.github/workflows/check.yaml
.github/workflows/release-daily.yaml
build/installer/version.hint

ci: bump to 1.8.0

---

build/manifest/images

fix: image update

---

build/installer/install_cmd.sh
build/manifest/images

fix: velero resource

---

README.md

docs: fix bad links and fold tables in readme

---

build/installer/install_cmd.sh
build/installer/install_macos.sh

fix: kubectl path and k8s preload images path

fix: kubectl path and k8s preload images path

---

build/installer/install_cmd.sh
build/installer/install_macos.sh

fix: update installer

---

build/installer/install_cmd.sh

fix: velero resource adjustment for 2c8g server

fix: velero resource adjustment

---

apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
build/installer/install_cmd.sh
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

fix: oidc bug 
fix: authelia crash on start up

fix: oidc bug & authelia crash on start up

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
frameworks/tapr/config/cluster/crds/apr.bytetrade.io_middlewarerequests.yaml
frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml

Bug fix
fix: change nat export to arrary
add all user app list api for controlhub

fix: change nat export to arrary;all user app list api

---

apps/files/config/cluster/deploy/files_deploy.yaml
third-party/seahub/config/cluster/deploy/seafile_deploy.yaml

feat: support playing videos in Sync

---

build/installer/deploy/patch-globalrole-workspace-manager.yaml
frameworks/app-service/config/cluster/crds/app.bytetrade.io_imagemanagers.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix:
download image obey image pullpolicy
fire an error when containerd is down

fix: download image obey image pullpolicy;fire an error when containerd is down

---

apps/files/config/cluster/deploy/files_deploy.yaml
libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml

files:
- watch /Home/Documents of all users
- send add/update/delete infos for text-like files to search3

feat: files watch /Home/Documents for search3

---

build/installer/change_ip.sh

fix: change ip bug on wsl

---

third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: add kubesphere redis to the dependencies of authelia

fix: add kubesphere redis to the dependencies of authelia

---

libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml

jfsnotify:
- fix service account error for os-system

fix: jfsnotify os-system bug

---

build/installer/install_cmd.sh

fix: add cuda lib fixing to k3s service as a pre-task to resolve the restarting issue on wsl

fix: add cuda lib fixing to k3s service as a pre-task

---

apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: update controlhub and dashboard disk unit

---

build/installer/install_cmd.sh

fix: Add system check for Raspberry Pi OS

fix: raspberry pi os validation

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feat: termipass v1.2.19

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

Fix: update market app details ui

fix: update market app details ui

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml

feat: search upgrade for desktop

---

build/installer/install_cmd.sh
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: add cuda lib fixing to k3s service as pre-task

fix: add cuda lib fixing to k3s service as pre-task

---

apps/files/config/cluster/deploy/files_deploy.yaml

fix: audio-only media not playing

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml

feat: Search Upgrade

---

build/installer/install_cmd.sh

fix: set fs type when system app installing

fix: set fs type when system app installing

---

apps/files/config/cluster/deploy/files_deploy.yaml
build/installer/deploy/device-plugin.yaml
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: clear the anonymous session

fix: clear the anonymous session

---

build/installer/install.sh
build/installer/install_cmd.sh
build/installer/install_macos.sh
build/installer/uninstall_cmd.sh
build/installer/uninstall_macos.sh

feat: uninstall using terminus-cli, added an option to choose whether to delete local image cache files

feat: uninstall using terminus-cli

---

apps/files/config/cluster/deploy/files_deploy.yaml
build/installer/deploy/device-plugin.yaml
build/installer/install_cmd.sh
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: updates synchronize

---

apps/wise/config/user/helm-charts/wise/templates/wise_deployment.yaml

**What kind of change does this PR introduce?** 
feat: update knowledge to v0.1.42

feat: update knowledge to v0.1.42

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml

feat: knowledge version updated to v0.1.42

---

apps/system-apps/config/user/helm-charts/monitoring/templates/monitoring_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

fix: optimized controlhub and dashboard

---

.github/workflows/push-to-s3.yaml
.github/workflows/release.yaml
build/installer/install.sh
build/installer/install_cmd.sh
build/installer/uninstall_cmd.sh
build/installer/uninstall_macos.sh
build/manifest/images

feat: update installer

---

build/installer/install.sh
build/installer/publicInstaller.latest
build/installer/publicInstaller.sh

fix: remove install-wizard

---

apps/system-apps/config/cluster/deploy/ks_server_deploy.yaml
apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: fix controlhub multiple users permissions

---

build/installer/install.sh
build/installer/publicInstaller.latest
build/installer/uninstall_cmd.sh

fix: change the path of installed lock file

fix: change the path of installed lock file

---

build/installer/install_cmd.sh

fix: remove unrelated directory operations

---

build/installer/install_cmd.sh

fix: nvidia-ctk use external containerd

---

apps/system-apps/config/user/helm-charts/system/templates/admin_console_deploy.yaml

fix: fix controlhub some bugs

---

apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml

feat: download version updated to v0.0.4

---

build/installer/deploy/patch-globalrole-workspace-manager.yaml

Bug fix
fix: add apiextensions permission for second user

fix: add apiextensions permission for second user

---

build/installer/install_cmd.sh

fix: .installed path

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
can not connect to containerd in k3s
fix: can not connect to containerd in k3s

fix: can not connect to containerd in k3s

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

feature
feat: webhook for crd imagemanager

feat: webhook for crd imagemanager

---

frameworks/tapr/config/cluster/deploy/nats_deployment.yaml

fix: nats imagePullPolicy

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

feat: update edit and view YAML type

---

apps/files/config/cluster/deploy/files_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml

uploader:
- change logic to based on resumable.js like seafile
- move from userspace to os-system

feat: uploader change

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feature
https://github.com/beclab/TermiPass/pull/104

feat: update files new version to v1.2.22

---

build/installer/install_cmd.sh

fix: retry for built-in app installation

fix: retry for built-in app installation

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: update controlhub toolbar actions style

---

apps/search3/config/cluster/deploy/search3_server_deploy.yaml

fix: fix english chinese search together

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml

fix: fix google drive list, refactor google drive operation

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

fix: update google drive

---

.github/workflows/push-deps-to-s3.yml
build/manifest/dependencies.amd64
build/manifest/dependencies.arm64
scripts/build-full.sh
scripts/download-deps.sh

fix: update deps manifest

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: fix controlhub Terminal and Log permissions

---

build/installer/install_cmd.sh

fix: use compiled redis

---

build/installer/install_cmd.sh

fix: update installer and k3s and containerd separation

---

apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml

fix: create rss data directory automatically

fix: create rss data directory automatically

---

apps/files/config/cluster/deploy/files_deploy.yaml

files:
- all folders watched in Drive, with special folder also parsed content

feat: all folders watched in Drive, with special folder also parsed content

---

scripts/build.sh

fix: build images manifest

---

build/installer/uninstall_cmd.sh

fix: uninstall for .prepared

---

build/installer/wizard/config/settings/templates/globalrole-binding.yaml
build/installer/wizard/config/settings/templates/system_namespace.yaml
build/installer/wizard/config/settings/templates/user-namespace.yaml
build/installer/wizard/config/settings/templates/user-namespacerole-binding.yaml
build/installer/wizard/config/settings/templates/user-system-ns.yaml
build/installer/wizard/config/settings/templates/user-systemrole-binding.yaml
build/installer/wizard/config/settings/templates/workspacerole-binding.yaml

fix: numeric user name

---

build/installer/install_macos.sh

fix: update for macos

---

build/installer/uninstall_cmd.sh

fix: remove cluster for prepared

---

.github/workflows/build-redis.yaml
scripts/build-redis.sh

ci: build redis

---

build/installer/install.sh
build/installer/install_cmd.sh
build/installer/publicInstaller.latest
build/installer/publicInstaller.sh

fix: add proxmox support

---

build/installer/install_cmd.sh

fix: Improve the validation of the pve

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feature
add allocatable pod check for user create
config system api

feat: add allocatable pod check for user create;config system api

---

libs/fs-lib/config/cluster/deploy/fsnotify_daemon.yaml

fix: jfsnotify daemon crash

---

build/installer/uninstall_cmd.sh

fix: uninstall script

---

README.md

Fixed issue https://github.com/beclab/Terminus/issues/375

docs: fix Discord link

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml

feat: Add Sync for Search and spell checker

---

apps/search3/config/cluster/deploy/search3_server_deploy.yaml

fix: update search to v0.0.11 which fix detect short language error

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml

fix: Listen message for Iframe

---

apps/files/config/cluster/deploy/files_deploy.yaml

fix: 
- files: change buffer location to fix a new found copy bug after running as user 1000

fix: change buffer location to fix a new found copy bug after running as user 1000

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

fix: ignore localhost ip as node ip

fix: ignore localhost ip as node ip

---

build/installer/install_macos.sh

fix: validate host ip on macos

fix: validate host ip on macos

---

apps/files/config/cluster/deploy/files_deploy.yaml
build/installer/install_cmd.sh
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

feat: add shared lib path

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feature
feat: inject window push state script

feat: inject window push state script

---

build/installer/install_cmd.sh

fix: add registry-mirrors

---

third-party/seahub/config/cluster/deploy/seafile_deploy.yaml

feat: 
- seahub: authenticate with X-Bfl-User (no need login/token/session again)

feat: seahub authenticate with X-Bfl-User (no need login/token/session again)

---

build/installer/install_cmd.sh
build/installer/install_macos.sh

fix: modify the prompt

---

build/installer/install.sh
build/installer/install_cmd.sh
build/installer/install_macos.sh
build/installer/publicInstaller.latest
build/installer/uninstall_cmd.sh
build/installer/uninstall_macos.sh

feat: zfs support

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feat: add cookie upload page

---

apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml

feat: add cookie  legacy provider

---

apps/files/config/cluster/deploy/files_deploy.yaml

feat: 
- files: Only watches drive while not watching Data, Cache and External

feat: files only watches drive while not watching Data, Cache and External

---

apps/nitro/config/cluster/deploy/nitro_deploy.yaml

feat: 
-nitro: disable nitro for the time being

feat: disable nitro for the time being

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

feature: support multi-language

feat: release market v0.2.14

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feature
feat: bfl-ingress inject terminus-language

feat: bfl-ingress inject terminus-language

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

feat: update termipass v1.2.26

---

frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml

fix: numeric username bug

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

feat: update profile v2

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml

feature
feat: move headscale frontend to system-frontend

feat: move headscale frontend to system-frontend

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: increase http header max size

fix: increase http header max size

---

apps/search3/config/cluster/deploy/search3_server_deploy.yaml

feat: upgrade search3 to v0.0.12

---

apps/files/config/cluster/deploy/files_deploy.yaml

fix: 
- tapr/uploader: uploader cors bug

fix: uploader cors bug

---

apps/files/config/cluster/deploy/files_deploy.yaml

feat: supports playing media files in external storage

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

feature
feat: set deploy/sts replicas to 0, when eviction occur on one node cluster

feat: set deploy/sts replicas to 0, when eviction occur on one node cluster

---

build/installer/install.sh

fix: terminus-cli 0.1.17

---

apps/files/config/cluster/deploy/files_deploy.yaml

fix: crash when clearing segments

---

libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml
libs/fs-lib/config/user/helm-charts/fsnotify/templates/fsnotify_deploy.yaml

feat: delay sending write msg in 1s

feat: delay sending write msg in 1s

---

apps/argo/config/user/helm-charts/argo/charts/argoworkflows/templates/server/server-deployment.yaml
apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

**What kind of change does this PR introduce?** 
feat: knowledge v0.1.44
feat: wise v1.2.29

feat: knowledge v0.1.44

---

build/installer/deploy/device-plugin.yaml
build/manifest/images
scripts/upload-gpu-deps.sh

fix: nvshare cuMemAlloc modified

fix: nvshare cuMemAlloc modified

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: envoy outbound suport websocket upgrade;system frontend configmap format

fix: envoy outbound suport websocket upgrade;system frontend configmap format

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml

fix: update search i18n for desktop

---

build/installer/install.sh

fix: cli 0.1.19

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: fix controlhub restart pod 404

---

build/installer/install.sh

fix: cli 0.1.20

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: reset password bug

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: envoy set probes route to path;envoy timeout

fix: envoy set probes route to path;envoy timeout

---

scripts/download-deps.sh
scripts/upload-deps.sh
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: migrate the authelia storage to postgres

fix: migrate the authelia storage to postgres

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: eviction from kubelet

fix: eviction from kubelet

---

.github/workflows/release-daily.yaml
.github/workflows/release.yaml

fix: release archive package

---

build/installer/common.sh
build/installer/install.sh
build/installer/install_cmd.sh
build/installer/install_macos.sh

- fix: common.sh compatibility with macos
- fix: copy ks-installer yaml file on macos
- fix: set reverse_proxy_config

fix: cli 0.1.21

---

apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feat: support switching and turning off reverse proxy

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

feature: update wise frontend to v1.2.33

feat: update wise to v1.2.33

---

libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml
libs/fs-lib/config/user/helm-charts/fsnotify/templates/fsnotify_deploy.yaml

fix: jfsnotify proxy nil pointer bug

fix: jfsnotify proxy nil pointer bug

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: fix dashboard cluster source panel

---

.github/workflows/release-daily.yaml
.github/workflows/release.yaml

fix: wrong path of install.sh

---

build/installer/deploy/device-plugin.yaml

fix: nvshare lib revert

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: update dashboard i18n

---

build/manifest/images

fix: update images tag

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml

fix: update i18n

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

feature
feat: auth add internal auth-level

feat: auth add internal auth-level

---

build/installer/install.sh

fix: update cli to 0.1.22

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: image download use mirror registry

fix: image download use mirror registry

---

build/installer/install.sh

* fix: passing S3 parameters during uninstallation

fix: cli update to 0.1.24

---

apps/search3/config/cluster/deploy/search3_server_deploy.yaml

feat: upgrade search3 to v0.0.15 and add space property word for process

---

build/installer/install.sh

fix: cli update to 0.1.25

---

apps/analytic/config/cluster/deploy/analytic_deploy.yaml
apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml

fix: ignore notification error when login

fix: ignore notification error when login

---

build/installer/common.sh
build/installer/install.sh
build/installer/install_cmd.sh

fix: cli update to 0.1.26

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml

fix: termipass v1.2.37 & profile v1.0.2 & settings v0.1.83

---

build/manifest/images
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

fix: update reverse proxy image version to v0.1.3

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

fix: update bfl version to v0.3.43

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/market/config/user/helm-charts/market/values.yaml
build/installer/install_cmd.sh
build/installer/install_macos.sh

feat: market v0.2.15

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml

feat: upgrade beclab/drive to v0.0.5 and beclab/driveexecutor to v0.0.5

---

build/installer/install.sh
build/installer/install_cmd.sh

fix: restore kubeType

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: image download progress;image pull retry strategy

fix: image download progress;image pull retry strategy

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

**What kind of change does this PR introduce?** 
feature: market v0.2.16 version

feat: market v0.2.16 version

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

fix: termipass v1.2.41

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

**What kind of change does this PR introduce?** 
feature: update market frontend app dependencies checker

feat: release market v0.2.17

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

fix: termipass v1.2.42

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

feature
feat: argo workflow mutate image;more smooth pull progress calculate method

feat: argo workflow mutate image;more smooth pull progress calculate method

---

third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml

fix: derp list optimization

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feat: update vault, file, wise, market version

---

.github/workflows/check.yaml
.github/workflows/release-daily.yaml
.github/workflows/release.yaml
build/installer/install.sh
build/installer/version.hint

ci: bump to 1.10.0

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: invalid containerd.sock after containerd restart

fix: invalid containerd.sock after containerd restart

---

build/installer/install_macos.sh

fix: download component

---

build/installer/deploy/device-plugin.yaml

fix: update device-plugin.yaml

fix: update device-plugin.yaml

---

build/installer/install.sh

fix: macos kubeaddons dir not create

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

feature: Applications in the mirror download state will also be displayed on the desktop

feat: release market v0.2.20

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

Bug fix
fix: ingress add terminus language for desktop

fix: ingress add terminus language for desktop

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

fix: termipass v1.2.46

---

build/installer/install.sh

fix: Add MarketProvider environment variable

fix: add MarketProvider

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml

feat: beclab/drive and beclab/driveexecutor upgrade v0.0.11

---

apps/search3/config/cluster/deploy/search3_server_deploy.yaml

feat: upgrade search3 to v0.0.16 for add google cloud search exact match

---

build/installer/install.sh

fix: conversion of token_max_age to nanoseconds

fix: token-max-age convert to nanoseconds

---

apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feat: notification multilingual support

feat: notification multilingual support

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: delete control-hub middleware

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

Bug fix
fix: replace image repo when cwf update

fix: replace image repo when cwf update

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

fix: update bfl to v0.3.47

---

frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
frameworks/tapr/config/cluster/deploy/nats_deployment.yaml

Bug fix
fix: nats admin password with leading digit cause nats load config error

fix: nats admin password with leading digit cause nats load config error

---

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml

fix: try to download the upgrade package from cdn

fix: try to download upgrade package from cdn

---

apps/files/config/cluster/deploy/files_deploy.yaml

bugfix: 
- files: skip watcher trying to watch /data/External

fix: files: skip watcher trying to watch /data/External

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

fix timeout cancel in app image downloading

fix: timeout cancel in app image downloading

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

fix: termipass-1.9 v1.2.49

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

fix: termipass v1.2.49

---

apps/files/config/cluster/deploy/files_deploy.yaml

fix: 
- files: files-server unescape bugfix for GET /api/resources sync support

fix: files-server unescape bugfix for GET /api/resources sync support

---

build/installer/install_macos.sh

fix:the command for downloading files on macOS

fix: macos download command

---

apps/search3/config/cluster/deploy/search3_server_deploy.yaml

feat: parallel search

---

build/installer/install.sh

Bug fix
fix multiple bugs during installation process on the WSL platform

fix: update CLI version to 0.1.34

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml

fix: add dependencies for desktop and settings

fix: add dependencies for desktop and settings

---

apps/argo/config/user/helm-charts/recommend/templates/argo_fe_deploy.yaml
apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
third-party/ks-console/charts/templates/ks-console.yaml

feat: add entrance state for app

---

build/installer/install.sh

Bug fix
add installation log file for backwards compatibility of cloud provisioner and terminusd

fix: update CLI version to 0.1.36

---

frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feat: add udp support

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

feat: update wise to v1.2.50

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

feat: 1.9 wise v1.2.50

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml

feat: Files add aws s3

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml

feat: drive upgrade to v0.0.24 for support aws s3 download,ls,getmetadata

---

build/manifest/images

fix: bump l4 proxy version

---

build/installer/install.sh

fix: check os type

---

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

fix: remove password in log

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: fix dashboard loading

---

apps/files/config/cluster/deploy/files_deploy.yaml

feat: 
- files: uploader retransfers files when uploading folder or multi-files

feat: uploader retransfers files when uploading folder or multi-files

---

build/installer/install.sh

fix: update CLI version to 0.1.39

---

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml

fix: fix controlHub and dashboard ui

---

third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml

feat: custom derpmap url

---

build/installer/install.sh

feature
update CLI version to 0.1.40 to support CLI-based IP changing feature

feat: update CLI version to 0.1.40

---

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
apps/vault/config/cluster/deploy/vault_server_deploy.yaml
apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
build/installer/install.sh
frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
frameworks/backup-server/config/cluster/deploy/backup_server.yaml
frameworks/osnode-init/config/cluster/deploy/nodeinit_daemonset.yaml
third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml

feat: add global envs for multiple components

---

.github/workflows/build-ubuntu2204.yaml
scripts/build-ubuntu2204.sh

ci: build Ubuntu2204.appx

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml

feat: update market/settings new version support Olares

---

apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml

fix: update version

---

build/manifest/images
frameworks/bfl/config/launcher/templates/bfl_deploy.yaml

feature
if  the scheme `http` or `https` is set in the FRP server, it will be trimmed before using.

feat: allow scheme in frp server enpoint

---

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml

MARKET_PROVIDER support "only domain" or "prefix http"

feat: release market v0.2.25 

---

README.md
README_CN.md

docs: update tech stack CDN link for readme

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
apps/notifications/config/user/helm-charts/notification/templates/notification_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

fix: update beclab/login:v0.1.31

---

third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

fix: update login to v0.1.32

---

README.md
README_CN.md

- Added an introductory video about Olares.
- Removed screenshots about built-in apps to avoid confusion.

docs: add intro video in readme

---

build/installer/install.ps1
build/installer/install.sh
scripts/build-manifest.sh

fix: support download cdn url

---

LICENSE.md

docs: update license title to Olares

---

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml

fix: fixed  ui bugs for desktop and login
