beclab/Olares

frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
fix the bug that caused tapr-middleware to crash and memory leaks during restoration system
=> update middleware-operator to 0.1.29

build/installer/uninstall_cmd.sh
restoring backups in the cloud, if an incorrect password is entered, will result in service uninstalling. add parameters tosupport unsupervised server uninstalling
=> fixed: to add a force uninstall cluster parameter

build/manifest/images, frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml, frameworks/tapr/config/cluster/deploy/mongodb_deployment.yaml
fixed: add a retry mechanism for pinging the primary during MongoDB database restoration
=> build: update mongodb-operator to 1.14.2

build/installer/wizard/config/account/templates/account.yaml, build/installer/wizard/config/account/values.yaml, frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Bug fix
create new user install sys apps but not set gpu type
set gpu type when create new user install sys apps
NONE
=> set gpu type when create new user install sys apps

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml, apps/nitro/config/cluster/deploy/dify_deploy.yaml
ADD：
- dify: wasm, a new tool for self-hosting llm model
CHANGE:
- dify: change api serving llm in market from nitro to wasm
- dify & dify-gateway: auto set/unset system model-config and Ashia model-config to nitro/wasm/gpt-4 when llm model loading by nitro/wasm/nil (while openai API key configured manually)
BUGFIX:
- dify & dify-gateway: change system model-config to ctx=4096, token=1024 and Ashia model-config to token=1024 in order to ensure model running more stable
=> add wasm to dify and dify-gateway

build/installer/install_cmd.sh, build/installer/publicRestoreInstaller.sh
* Upgrade velero-plugin-for-terminus to v1.0.2
* fixed: after backing up a restored system and then restoring it again, the Redis restoration operation does not execute
=> fixed: restoration operation does not execute

build/installer/publicRestoreInstaller.sh
fixed: adds support for operating systems including Ubuntu 20, 22, 24, and Debian 11, 12. Specifically, it upgrades AppArmor to version 4.0.1 for Ubuntu 24 to ensure system security and compatibility
=> fixed: add os verify when restore backup

apps/agent/config/user/helm-charts/agent/templates/agent_deploy.yaml, apps/nitro/config/cluster/deploy/dify_deploy.yaml
BUGFIX:
- dify: change libfile copy logic to fit both cloud and minibox
CHANGE:
- defy-gateway: model default max-token down to 512 to fit wasm default and minibox
=> dify&dify-gateway: fit both cloud and minibox

build/installer/uninstall_cmd.sh, frameworks/GPU/config/gpu/templates/container-runtime.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
`bug fix`: orion GPU runtime broken on Ubuntu 22.04
=> fix: orion gpu runtime broken on Ubuntu 22.04

build/installer/install_cmd.sh, build/manifest/dependencies, scripts/build-full.sh, scripts/deps-manifest.sh, scripts/download-deps.sh, scripts/upload-deps.sh
fix: curl download failure, as well as other errors
=> fix: curl download failure, as well as other errors

apps/files/config/user/helm-charts/files/templates/files_deploy.yaml, apps/nitro/config/cluster/deploy/dify_deploy.yaml
change:
- files: manually chunk when pasting to sync to ensure dealing with files between 2G and 4G correctly
- dify: system model context from 4096 down to 1024 for running more stable
=> feat: manually chunk in files and context down to 1024 in dify

frameworks/app-service/config/cluster/crds/app.bytetrade.io_imagemanagers.yaml, frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Bug fix
conflict when multi thread update crd concurrency
fix: progress job use random ticker to lower conflict
=> fix: progress job use random ticker to lower conflict

.github/workflows/release-daily.yaml, build/installer/publicInstaller.sh
`ci/cd`: upload the full package to s3 in daily-build
=> ci: upload the full package to s3 in daily-build

.github/workflows/release-daily.yaml, build/installer/install.sh, build/installer/publicInstaller.sh
`ci/cd`: use an independent daily-build install script for the daily-build version installing,  keep the publicInstaller.sh for Terminus Space itself.
=> ci: independent daily-build install script

apps/nitro/config/user/helm-charts/dify/templates/dify_fe_deploy.yaml, third-party/seahub/config/user/helm-charts/seafile/templates/seafile_fe_deploy.yaml
fix:
- seafile: remove public accessible ui
- dify: add dify URL auth
=> fix: remove seafile ui and add dify auth

build/installer/version.hint, third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
`fix`: add infisical deployment init-container environments
change the minimum upgradable version
=> fix: add infisical deployment init-container envs

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
`feature`: patch nginx base image to supported arm64, fix l4-bfl-proxy and bfl-ingress arm64 version nginx exec file format error.
=> feat: l4 proxy & bfl ingress arm64 supported

apps/nitro/config/cluster/deploy/nitro_deploy.yaml
change:
- nitro: configurable dify_host and llm_host for dify model auto config
=> feat: restore dify model auto config

build/installer/install_cmd.sh, build/installer/publicAddnode.sh, build/manifest/images.node.mf, scripts/image-manifest.sh
feat: support adding arm64 worker node
=> feat: support adding arm64 worker node

apps/nitro/config/cluster/deploy/nitro_deploy.yaml
fix:
- nitro: nginx config spell error
=> fix: nitro nginx config spell error

scripts/developer/install_macos.sh
=> fix: installing bugs on macos

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml, frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml, frameworks/tapr/config/cluster/deploy/citus_deployment.yaml
Bug fix
fix: app inter call sidecar inject
postgres update extension vectors to 0.3.0
=> fix: app inter call sidecar inject;update vectors to 0.3.0

apps/search3/config/cluster/deploy/search3_server_deploy.yaml, apps/search3/config/cluster/search3_server_deploy.yaml
=> feat: init search3

build/installer/check_image_size.sh
=> feat: Added a script to check the size of all images in the installation package.

build/installer/install_cmd.sh
fix: apt update failed with wrong clock time
=> fix: apt update failed with wrong clock time

build/installer/install_cmd.sh, build/installer/publicAddnode.sh, build/installer/upgrade_cmd.sh, build/manifest/dependencies.amd64, build/manifest/dependencies.arm64
fix: bump juicefs-ext to 11.1.1
=> fix: bump juicefs-ext to 11.1.1

build/installer/install.sh
=> fix: terminus-cli 0.1.16

.github/workflows/release-daily.yaml, .github/workflows/release.yaml
Bug fix
the current released `install.sh` will not have a valid `Version`, resulting in failure of execution.
```
curl -ssLO https://github.com/beclab/Terminus/releases/download/1.8.0-20240917/install.sh
❯ chmod +x install.sh
❯ ./install.sh
Unable to get latest Install-Wizard version. Set VERSION env var and re-run. For example: export VERSION=1.0.0
```
the cause is:
in the action spec, the released `install.sh` is copied from `build/installer`:
https://github.com/beclab/Terminus/blob/896ece5975f825a43b4635bffe2455d76ec55e9d/.github/workflows/release-daily.yaml#L125-L128
whereas the version string injection is done to the …
=> fix: copy back install.sh after version string is injected

build/installer/install.sh
- fix: no longer delete the share directory
- fix: remove the cli directory during the uninstall process up to the prepare stage
- fix: automatically retrieve the terminus version number and kube type during uninstallation
=> fix: cli update to 0.1.29

apps/files/config/cluster/deploy/files_deploy.yaml
files:
- GET /api/resource add recursive streaming style for folder downloading by "?stream=1"
- GET /api/resource add sync support by "?src=sync"
- Both of the params above can work together for sync folder downloading
- fix a new found bug for search3 when content is empty when the pod is restarting
=> feat: files get resource recursive stream for folder downloading

build/installer/install.sh, build/installer/install_cmd.sh, frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
feature
if the environment variable `TERMINUS_CERT_SERVICE_API` is set, it will be used instead of the default `https://terminus-cert.snowinning.com`
if the environment variable `TERMINUS_DNS_SERVICE_API` is set, it will be used instead of the default `https://terminus-dnsop.snowinning.com`
=> feat: use domestic terminus cert&dns service if set

libs/fs-lib/config/cluster/deploy/fsnotify_deploy.yaml, libs/fs-lib/config/user/helm-charts/fsnotify/templates/fsnotify_deploy.yaml
fix: deadlock in jfsnotify-proxy where client watcher crash
=> fix: deadlock in jfsnotify-proxy where client watcher crash

build/installer/install.sh, build/installer/wizard/config/settings/templates/terminus_cr.yaml
Bug fix
the legacy way of replacing holder string in yaml files (notably the terminus_cr.yaml) before applying it may cause a problem that, if the OS is uninstalled and then installed again, the modified yaml files will remain replaced,
and the replace operation done by the new installation process will not take any effect, resulting in inconsistent behaviors.
using helm values instead, to keep the files unchanged throughout multiple installations
=> fix: use helm templating instead of sed replace

build/installer/install.sh
Bug fix
the webhook for `users.iam.kubesphere.io`, embedded in the ks controller-manager takes some time to be up after it's running, and may cause a failure of user creation.
=> fix: add startup probe for ks-controller-manager

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Bug fix
the local IP address is added as a DNS record for local domain upon user activation, even when a NAT gateway IP address is set.  this will only be corrected some time later by another control loop.
choose the NAT gateway IP address as the DNS record for the local domain during user activation, if one is present.
none
=> fix: choose nat ip as local domain dns record if present

build/installer/install.sh
feature
Get a valid IP address from the local network interfaces of MacOS, and use it as the default IP of NAT gateway, saves the hassle of typing the IP manually if it is the IP address the user wants.
```
2024-11-28T17:47:32.276+0800	[Module] GetNATGatewayIP
Enter the NAT gateway(the MacOS host)'s IP [default: 192.168.1.5]:
2024-11-28T17:56:31.627+0800	Nat Gateway IP: 192.168.1.5
2024-11-28T17:56:31.632+0800	[A] LocalHost: GetNATGatewayIP success (8m59.36280975s)
```
=> feat: set default nat gateway ip in prompt for mac

.gitignore, build/installer/install.sh
feature
JuiceFs is always installed on Linux as a base storage for all Olares workloads.
by default, JuiceFS is not installed and the local fs is used.
a new environment variable `JUICEFS` is added to the `install.sh` script, to let user choose between the local filesystem and JuiceFS as the base storage for Olares workloads.
if set to `1`, the option `--with-juicefs=true` is specified when invoking the `olares-cli olares prepare` command, and JuiceFS, along with its dependencies Redis/MinIO will be installed.
* **Does this PR introduce a breaking change?** (What …
=> feat: add env for install.sh to choose between JuiceFS & local fs

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Bug fix
store the currently applied DNS record of local domain, and update the DNS record only when it doesn't match with the desired IP, to avoid unnecessary requests, e.g. when the DNS record hasn't been propagated or the local DNS service is being hijacked.
=> fix: store & compare applied dns record of local domain

build/installer/install.sh, build/manifest/images
feature
coredns is managed by k3s/kubeadm
nodelocaldns is installed but not used in k3s
nodellocaldns blocks non-cluster DNS request to coredns in k8s
pods in cluster cannot resolve static hostname mapping from /etc/hosts in host machine
manage coredns ourselves
disable nodelocaldns
make coredns read /etc/hosts file from host machine and serve its DNS records to pods in cluster
none
=> feat: configure coreDNS to serve record from node /etc/hosts

build/installer/install.ps1, build/installer/install.sh
In order to run the latest Llama model with Ollama, we upgrade CUDA toolkit to 12.4, which is paired with the driver version 550.
1.10.5, 1.11.0
none
https://github.com/beclab/Installer/pull/65
https://docs.nvidia.com/deploy/cuda-compatibility/#use-the-right-compat-package
=> installer: upgrade cuda driver to 550

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
set `spec.runAsUser`:`true` in `OlaresManifest.yaml` if that app can work fine with uid eq 1000.
main, release 1.10
None
https://github.com/beclab/app-service/pull/114
None
=> app-service: olares manifest add runasuser config parameter

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
The settings and profile servers both use NestJS, each requiring 70-90 MB of memory, and there is a lot of duplicate code. This modification merges the code repositories for settings and profile, as well as consolidates the servers for profile and settings.
v1.11.0
None
https://github.com/beclab/settings/releases/tag/v0.2.0
=> settings,profile: merge profile server to settings server

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Some image upload client uses the HTTP v1.0. To be compatible with these clients, add the option to envoy sidecar config.
main, release-1.10
Bug: Cannot upload images in profile editor
none
=> olares: compatible with http 1.0 in image upload api

build/installer/install.ps1, build/installer/install.sh
On systems where JuiceFS is not enabled, there's no need to restart all of the pods after ip changing.
Only the pods whose `.hostNetwork` is set to true or are using node's IP as a env var should be restarted, and this shortens the time the change ip command takes.
1.11.0
none
https://github.com/beclab/Installer/pull/66
none
=> installer: when changing ip, only restart pods related to host ip if juicefs disabled

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Some UI bugs on desktop
main, release 1.10.0
Bug: Adaptive docker height and long press icon displays error on mobile devices
https://github.com/beclab/desktop/releases/tag/v0.2.45
None
=> desktop: upgrade to v0.2.45

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
1. In user initializing progress, if the user activates the HTTPS proxy, the initializing state will keep the running state even the progress has already failed.
2. When a user updates the password in Settings, the new password is not actually applied in the data store.
v1.11.0, v1.10.5
Bug: user initializing is running for a long time.
Bug: reset user password not working
https://github.com/beclab/bfl/pull/59
https://github.com/beclab/bfl/pull/60
=> bfl: reset password not applied and user initializing failed state

apps/files/config/cluster/deploy/files_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml, apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, apps/vault/config/cluster/deploy/vault_server_deploy.yaml, apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
1. When copying between sync and other drives, it fails if there are spaces in the name. This is involved in v0.2.40 which is also dealing with special characters.
2. When copying between sync and other drives recursively, it is newly presented that it fails because the inconsistent permission.
3. When uploading a file in a folder containing spaces, it will cause a path decoding error.
v1.12.0, v1.11.0, v1.10.5
https://github.com/beclab/files/releases/tag/v0.2.46
https://github.com/beclab/TermiPass/releases/tag/v1.3.2
=> files: fix the bug when copying name with space for src xor dst is sync

build/installer/install.ps1, build/installer/install.sh
fix the bug that when executing olares-cli, a program stack with nil pointer dereference panic is likely to show up rather than the actual error message.
main
https://github.com/beclab/Olares/issues/734
https://github.com/beclab/Installer/pull/67
none
=> installer: use the logger from std lib at cmd entry

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml, frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
The current market only supports obtaining and installing the latest version of the app. When the app is upgraded alongside the system's core components, there may be compatibility issues with older versions of the system. Additionally, older systems may be unable to upgrade due to technical reasons or user preferences, leading to situations where these users can no longer use the app.
v1.11.0 & v1.12.0 
https://github.com/beclab/market/commit/8b9dd1534c0717ee72d0a17268ce346cd9751c35
https://github.com/beclab/app-service/pull/115
=> market, app-service: support old version install app

build/installer/upgrade_cmd.sh
Since settings app is merged into system-frontend. System upgrade must uninstall the legacy settings app first.
v1.10.5
Bug: v1.10.5 upgrade failed.
none
=> oalres: uninstall settings app in upgrade

build/installer/install.ps1, build/installer/install.sh
detect public IP when installing Olares by:
1. check whether the machine has a local network interface to which a public IP is bound
2. if the machine is an AWS EC2 instance, check whether it has an associated public IP address by contacting the IMDS service
if a public IP is detected, the `selfhosted` setting is turned off when installing related components, and then reverse-proxy or tunnel is disabled automatically in activation.
v1.11.0 v1.12.0
none
https://github.com/beclab/Installer/pull/68
none
=> installer: detect public ip during installation

apps/download/config/user/helm-charts/download/templates/download_deploy.yaml, apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml, apps/rss/config/cluster/deploy/rss_deploy.yaml
Background
support LarePass download
support some bilibili subscriptions and their content parsing
reduce the size of the rsshub image
v1.12
Related Issues
https://project.feishu.cn/terminus/issue/detail/5105792969
https://project.feishu.cn/terminus/issue/detail/4976580565
https://project.feishu.cn/terminus/issue/detail/5051040496
https://github.com/beclab/recommend-system-module/pull/74
https://github.com/beclab/recommend-system-module/pull/72
None
=> knowledge and download:  support LarePass donload and fix bilibili extract bug

apps/download/config/user/helm-charts/download/templates/download_deploy.yaml, apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml, apps/rss/config/cluster/deploy/rss_deploy.yaml
Background
support LarePass download
support some bilibili subscriptions and their content parsing
reduce the size of the rsshub image
v1.11
Related Issues
https://project.feishu.cn/terminus/issue/detail/5105792969
https://project.feishu.cn/terminus/issue/detail/4976580565
https://project.feishu.cn/terminus/issue/detail/5051040496
https://github.com/beclab/recommend-system-module/pull/74
https://github.com/beclab/recommend-system-module/pull/72
None
=> knowledge and download: support LarePass donload and fix bilibili extract bug

.github/workflows/check.yaml, build/installer/install.ps1, build/installer/install.sh
If a containerd instance not managed by us is already installed on a system, conflicts may be encountered. A precheck before preparing is added to error out in this case.
Some ports in host machine network is required to expose service, if they're occupied, related pods cannot bind the ports and will fail to start. A prechck is also added to test whether these ports are able to bind and will error out if not.
v1.11.0, v1.12.0
none
https://github.com/beclab/Installer/pull/75
none
=> fix(installer): add precheck for conflicting containerd and ports

build/installer/install.ps1, build/installer/install.sh
cloud instance already has containerd installed and should not be blocked by the containerd conflicting precheck.
v1.11.0, v1.12.0
none
https://github.com/beclab/Installer/pull/79
none
=> fix(installer): skip conflicting containerd precheck on cloud instance

.github/workflows/push-deps-to-s3.yml, .github/workflows/push-to-s3.yaml, .github/workflows/release-daily.yaml, .github/workflows/release.yaml
The runner `ubuntu-latest` is updated from `ubuntu-22.04` to `ubuntu-24.04`, on which some jobs will fail to run.
In our case, the `configure coscmd` job called `coscmd` that's incompatible with the Python 3.12 shipped with Ubuntu 24.04.
main
none
none
none
=> ci: use stable runner ubuntu-22.04 rather than latest

build/installer/install.ps1, build/installer/install.sh
Title: installer
Support for installing Olares in PVE and LXC containers created by PVE.
1.11 1.12
#366 
* **PRs Involving Sub-Systems**
For LXC containers, it is necessary to set the privileged attribute.
```
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow: a
lxc.cap.drop:
lxc.mount.auto: "proc:rw sys:rw cgroup:rw"
```
For installation in PVE, non-enterprise users need to disable the enterprise repository, which can be done in the control panel.
=> installer: feat support pve lxc

frameworks/tapr/config/cluster/deploy/nats_deployment.yaml
nats server may restart if nats.conf not exists.
1.10,1.11,1.12
None
https://github.com/beclab/Olares/pull/773
None
=> olares: add init container for nats to generate nats.conf

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- AI applications may start using either GPU or CPU
- AI applications may only support GPU startup
- Different versions of AI applications have different requirements for the runtime environment (CUDA)
1.12
None
https://github.com/beclab/app-service/pull/118
None
=> app-service: set gpu values

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
In the previous update, we changed the local database to Redis. To handle the situation of upgrading the market, the configuration for the Redis password involves first checking for an existing password. If none is found, a new random password will be generated. However, the location where the password is checked in the configuration is incorrect, which prevents the market from connecting to Redis after the upgrade.
none
none
=> olares: fix redis password lost

build/installer/install.sh
the image-service needs to load the registry mirrors set in `/etc/containerd/config.toml` in order to pull image, the container runtime of MiniKube needs to be changed from Docker to Containerd, and registry mirrors should be injected into the inner containerd environment.
v1.12.0
none
https://github.com/beclab/Installer/pull/83
none
=> feat(installer): support setting registry mirrors for minikube

build/installer/install.ps1, build/installer/install.sh
extract installation/validation of object storage service out of `prepare` into a separate `install storage` phase, and move FS-related tasks to the `install` phase, a corresponding `storage` phase for uninstallation is also added.
v1.12.0
none
https://github.com/beclab/Installer/pull/85
none
=> feat(installer): seperate phase & command for storage installation

build/installer/install.ps1, build/installer/install.sh
If the `config_path` is set in the `[plugins."io.containerd.grpc.v1.cri".registry]` section in containerd config, the `[plugins."io.containerd.grpc.v1.cri".registry.mirrors]` will take no effect, so the `config_path` should be reset if we need to inject mirrors to the containerd config in MiniKube.
v1.110 v1.12.0
none
https://github.com/beclab/Installer/pull/86
none
=> fix(installer): reset config path of cri plugin in minikube

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
after patch deploy  pod template would cause generate 2 replicaset and cause pod restart
1.12
None
https://github.com/beclab/app-service/pull/119
None
=> app-serivce: fix patch deploy/sts cause pod restart

build/installer/install.sh
`minikube start -p {profile}` command will override the image metadata db of containerd in the profile, causing loss of all images loaded by us.
v1.11.0 v1.12.0
none
https://github.com/beclab/Installer/pull/87
none
=> fix(installer): tag k8s images in minikube to avoid destructive reload

build/installer/install.sh
cherry pick of https://github.com/beclab/Olares/pull/789: extract installation/validation of object storage service out of `prepare` into a separate `install storage` phase, and move FS-related tasks to the `install` phase, a corresponding `storage` phase for uninstallation is also added.
v1.12.0
none
https://github.com/beclab/Installer/pull/85
none
=> cherry pick of #789: feat(installer): seperate phase & command for storage installation

build/installer/install.ps1, build/installer/install.sh
a separate `precheck` command which is responsible for running system checks and printing out all unsatisfied requirements is added and executed before other phases.
v1.12.0 v1.11.1
none
https://github.com/beclab/Installer/pull/88
none
=> feat(installer): add a separate command for all prechecks

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- suspend app in os-system caused other deploy scaled to zero
- the progress of the image download may stall at a certain value
- the image may be considered downloaded even though it is not fully downloaded
1.12
None
https://github.com/beclab/app-service/pull/120
https://github.com/beclab/app-service/pull/121
None
=> app-service: fix app suspend in os-system;image download bug

third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Title: headscale :  acl 
When users or applications want to control the opening permissions of the tailscale port, they can set it by dynamically controlling the headscale acl rules through k8s crd
Headscale sets up an ACL rule to restrict access to port 443. This cannot meet the needs in the following two scenarios
1. Users want to access the host for debugging through ssh via VPN
2. Users want to stream Steam through VPN
So, we hope that the system can set rules for ACL
=> feat(headscale): move acl.json to configmap

build/installer/install.sh
To install the version of Olares for WSL, firewall rules need to be set. During the installation process, users will be prompted to add the rules, but they can skip this step and set the firewall rules themselves.
v1.12.0 v1.11.1
none
https://github.com/beclab/Installer/pull/89
none
=> feat(installer): add firewall settings for Windows

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
api apps missing initializing state app
1.12
None
https://github.com/beclab/app-service/pull/123
None
=> app-service: fix api apps missing initializing state

build/installer/install.ps1, build/installer/install.sh
GPU-related pods will not be created if the system has not enabled GPU, thus their Running status need not to be checked
handle the case where `nvidia-smi` tool is installed but CUDA is not
restart GPU plugins properly
v1.11.1 v1.12.0
none
https://github.com/beclab/Installer/pull/95
https://github.com/beclab/Installer/pull/96
* none
=> fix(installer): properly check cuda driver & gpu plugin

build/installer/install.ps1, build/installer/install.sh
correct the current invalid value used to label a GPU node
explicitly set a local Runner in order to run GPU status tasks outside of a Pipeline
v1.11.1 v1.12.0
none
https://github.com/beclab/Installer/pull/97
https://github.com/beclab/Installer/pull/98
none
=> fix(installer): invalid gpu node label value, run task without runner

build/installer/install.ps1, build/installer/install.sh
running the ps1 installation script in non-administrator mode, environment variables cannot be passed to WSL.
1.12, 1.11
none
none
=> fix(installer): check if PowerShell is running as an administrator

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- only replace image ref with custom mirror only if registry is docker.io
- turn off custom mirror connection check
1.12
None
https://github.com/beclab/app-service/pull/124
None
=> image-service: fix remove custom mirror connection check;only proxy docker.io

build/installer/install.ps1, build/installer/install.sh
nil pointer dereference panic when labelling GPU node
correct daemonset name when restarting Nvidia plugin pod
also disable GPU when uninstalling CUDA
more appropriate error message when CUDA version is too low
correct wrong basedir path when installing container-toolkit in WSL
support newer CUDA version with a warning message
v1.11.1 v1.12.0
none
https://github.com/beclab/Installer/pull/100
https://github.com/beclab/Installer/pull/101
https://github.com/beclab/Installer/pull/103
https://github.com/beclab/Installer/pull/104
https://github.com/beclab/Installer/pull/105
https://github.com/beclab/Installer/pull/106
none
=> fix(installer): multiple GPU-related bugs

build/installer/install.ps1, build/installer/install.sh
use a global supported coda version list to avoid inconsistencies in different check modules
v1.11.1
none
https://github.com/beclab/Installer/pull/108
none
=> fix(installer): use a global supported cuda version list

third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
If the non-auth request is a local domain, it should be redirected to the login portal following the request of the local domain
v1.12.0
Redirect the non-auth request of the local domain to the public domain login portal.
https://github.com/beclab/authelia/commit/44c21a3091beed557eba892af5bd7a914c368844
=> auth: redirect to login portal following the request of local domain

build/installer/install.ps1, build/installer/install.sh
the cuda lib script should be executed in WSL right after it's generated
the WSL's GPU driver is managed by Windows and should not be uninstalled by the `gpu uninstall` command
v1.11.1
none
https://github.com/beclab/Installer/pull/109
https://github.com/beclab/Installer/pull/110
none
=> fix(installer): run cuda lib script for WSL, disable uninstall cmd for WSL

build/installer/install.ps1, build/installer/install.sh
this is a cherry-pick of https://github.com/beclab/Olares/pull/851
A search domain other than the `"."` in the Linux's DNS resolver configuration causes the cluster DNS to malfunction, a check for this case is added to the precheck list to avoid a late failure.
Some native libs on Debian may conflict with an arbitrary version of Nvidia driver, the hard coded version should be removed to let the package manager decide what's the appropriate version to install.
v1.11.2
none
https://github.com/beclab/Installer/pull/114
https://github.com/beclab/Installer/pull/113
none
=> feat(installer): check the validity of resolv.conf before installation

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- delete cache dir when cancel app installation
- inject env NVSHARE_MANAGED_MEMORY when install app that need gpu
1.12
None
https://github.com/beclab/app-service/pull/127
https://github.com/beclab/app-service/pull/128
None
=> app-service: delete cache dir when cancel installation;set nvshare env

build/installer/install.ps1, build/installer/install.sh
if the `systemd-resolved` is active, stop and disable it to avoid refreshing back the `/etc/resolv.conf` file, if the system can not resolve domain name normally, set an available DNS server.
v1.11.2 v1.12.0
none
https://github.com/beclab/Installer/pull/115
none
=> feat(installer): check systemd-resolved and config resolv.conf

build/installer/install.ps1, build/installer/install.sh
the fetch of WSL IP from Windows host is sometimes messed up by other warning messages
the Windows host's IP is not shown as a default value when executing change-ip command
the url to check whether the machine's DNS server is working normally cannot be reached by CN users
add an option to specify mirrors when installing the Nvidia container toolkit
v1.11.2 v1.12.0
none
https://github.com/beclab/Installer/pull/119
https://github.com/beclab/Installer/pull/120
https://github.com/beclab/Installer/pull/117
https://github.com/beclab/Installer/pull/116
https://github.com/beclab/Installer/pull/118
none
=> fix(installer): fix multiple network-related bugs

third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Title: headscale:  db
When performing rolling update for headscale deployment, there is data conflict in SQLite.
=> fix(headscale): use postgres instead of sqlite for headscale rollingupdate

build/installer/install.ps1, build/installer/install.sh
A new environment variable named`"PUBLICLY_ACCESSIBLE"` is added to the installer let user explicitly specify that their machine can be accessed on the public internet, and no reverse proxy should be used to route traffic.
none
https://github.com/beclab/Installer/pull/121
none
=> feat(installer): add env var to explicitly specify public access

.github/workflows/release-daily.yaml, .github/workflows/release.yaml, build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
Currently, a local and single node environment is assumed in the Olares installer, this PR adds a `joincluster.sh` that can be executed on a new machine to let it join an already existing Olares cluster.
What the new script does, effectively, is read a bunch of environment variables that specify how to access the master node through SSH, run the corresponding commands of `olares-cli` to retrieve the Olares version of the master node, download and install the container components and join the cluster.
Specifically, the environment variables read by the new `joincluster.sh` script are:
| name | explain | required | default |
|---|---|---|---|
| MASTER_HOST | the IP address of the master node | true | |
| MASTER_NODE_NAME | the node name of master | false | |
| …
=> feat: add node to a cluster

build/installer/install.ps1, build/installer/install.sh
When installing olares in WSL, the .vhdx file will occupy a large amount of disk space on the system drive. During installation, the user will be prompted to select a storage location, and the file will be migrated to the user-specified drive.
1.11.x
=> feat(installer): set wsl distro storage location

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
the current uninstallation process wipes out the JuiceFS rootfs, which is fine in a single-node environment but causes trouble in a multi-node environment because all nodes share a same view of the JuiceFS. When uninstalling worker node, the JuiceFS rootfs should be left untouched
v1.12.0
none
https://github.com/beclab/Installer/pull/124
none
=> fix(installer): dont wipe juicefs when uninstalling worker

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
`bfl` Headscale ACL API path parameters are mismatch
v1.12.0
bfl headscale acl API not work
https://github.com/beclab/bfl/pull/64
=> bfl: fix headscale acl api path parameters

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix: restore settings app entrance status notification and dashboard websocket
feat: restrict suspend/resume operations
fix: space url split error
1.12
None
https://github.com/beclab/settings/releases/tag/v0.2.7
None
=> settings, dashboard: restore settings app entrance status notification and dashboard websocket

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml, apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml, frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml, third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml, third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
To avoid evicting some critical pods by k8s / k3s, mark these pods as `system-cluster-critical`
Some critical pods were evicted when the server had some resource pressure, causing the cluster not working  properly
https://github.com/beclab/bfl/pull/65
=> olares,bfl: update critical pods priority class

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
read the `DOWNLOAD_CDN_URL` env and download the WSL package from the corresponding CDN
handle locales other than English when interacting with sudo prompt via SSH
extract containerd binarys to `/usr/bin` directly to avoid creating and deleting tmp directory
v1.12.0
none
https://github.com/beclab/Installer/pull/128
https://github.com/beclab/Installer/pull/126
https://github.com/beclab/Installer/pull/127
https://github.com/beclab/Installer/pull/130
none
=> fix(installer): issues in wsl downloading/ssh sudo/containerd install

build/installer/install.ps1, build/installer/install.sh
read the `DOWNLOAD_CDN_URL` env and download the WSL package from the corresponding CDN
extract containerd binarys to `/usr/bin` directly to avoid creating and deleting tmp directory
v1.11.3
none
https://github.com/beclab/Installer/pull/128
https://github.com/beclab/Installer/pull/130
none
=> fix(installer): issues in wsl downloading/containerd install

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
web browser in windows app can not access to the network cause by envoy
1.11
None
https://github.com/beclab/app-service/pull/134
None
=> app-service: support network visit from windows app

build/installer/install.ps1, build/installer/install.sh
Mounting shared path via Samba protocol needs `cifs-utils` to be installed
none
https://github.com/beclab/Installer/pull/133
=> installer: install cifs-utils for mounting smb path

apps/files/config/cluster/deploy/files_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml, apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, apps/vault/config/cluster/deploy/vault_server_deploy.yaml, apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
disable nats and expand upload size limit to 100G
v1.11.0
none
https://github.com/beclab/TermiPass/pull/326
https://github.com/beclab/TermiPass/pull/325
none
=> files&files server: disable nats and expand upload size limit to 100G

build/installer/install.ps1, build/installer/install.sh
Due to network or other reasons, running wsl --update is unresponsive, possibly because Microsoft Store or GitHub is inaccessible. The new upgrade method has been adjusted to downloading an offline installation package for installation or upgrade.
1.11
https://github.com/beclab/Installer/pull/137
=> fix(installer): wsl hangs on update

apps/files/config/cluster/deploy/files_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml, apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, apps/vault/config/cluster/deploy/vault_server_deploy.yaml, apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml, third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
files: nginx increase worker and timeout, and pasting temp file invisiable
fix create new folder in sync and update axios timeout to 30min
v1.11.0
none
https://github.com/beclab/TermiPass/pull/328
none
=> files&files server: updage LarePass version to v1.3.24

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
App-server will inject some environment duplicated if the environment value is empty 
v1.11.3
https://github.com/beclab/app-service/pull/135
=> app-service: inject nvshare environment duplicately

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
remove the application cache path on the hosts directly
application's cache be removed inompletetly
https://github.com/beclab/app-service/pull/136
=> app-service: remove app cache path on the hosts directly

.github/workflows/release-daily.yaml, scripts/upload-deps.sh, scripts/upload-images.sh
To avoid image files and dependencies being contaminated, upload the original file as a backup.
v1.12.0
1. Checking caching files on s3 got the 503 error code
2. Caching file was contaminated by re-uploading
none
=> olares: upload the original file with md5 as a backup

frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
Citus and KVRocks middleware data files are stored on the master node host path. So it needs to always schedule them to the master node.
Citus loses data on multi-node cluster
https://github.com/beclab/tapr/pull/35
=> tapr: add node affinity to citus and kvrocks

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
coredns also counts as a pod using host ip because the local network's gateway is often used as its upstream DNS server in the pod's `/etc/resolv.conf`, and it needs to be manually updated in case of a CIDR change
the default timeout period of CRI requests is `2m` in kubelet, and can time out during the middle of a normal operation like unpacking a large image on slow hardwares, we explicitly lift it to `5m` to make it more tolerable.
1.12.0
none
https://github.com/beclab/Installer/pull/142
https://github.com/beclab/Installer/pull/143
none
=> fix(installer): restart coredns when change ip, raise cri timeout

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml, scripts/upload-deps.sh, scripts/upload-images.sh
- resume op failed after restart
- envoy inbound not support tcp
1.12
None
https://github.com/beclab/app-service/pull/139
https://github.com/beclab/app-service/pull/138
=> app-service: continue to resume op after restart; envoy inbound tcp proxy

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml, scripts/upload-deps.sh, scripts/upload-images.sh
- resume op failed after restart
- envoy inbound not support tcp
1.11
None
https://github.com/beclab/app-service/pull/139
https://github.com/beclab/app-service/pull/138
=> app-service: continue to resume op after restart; envoy inbound tcp

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Increase l4 proxy nginx worker process number to half of CPU cores
v1.11.4 v1.12.0
Bulk concurrent requests cause nginx to hang
https://github.com/beclab/bfl/pull/68
=> bfl: increase l4 proxy nginx worker process number to half of cpu cores

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Increase l4 proxy nginx worker process number to half of CPU cores
v1.11.4
Bulk concurrent requests cause nginx to hang
https://github.com/beclab/bfl/pull/68
=> bfl: increase l4 proxy nginx worker process to half of cpu cores

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
**Background**
Directly set the user's account email as olaresID without displaying it, and hide the field.
1.11
None
https://github.com/beclab/settings/pull/86
None
=> settings: hide user email entry

apps/files/config/cluster/deploy/files_deploy.yaml
Files-server runs as a cluster service to manage the files of all users and all apps.  It must get the root privileges to operate with all apps' stored files.
v1.12.0
Insufficient privileges for reading/writing some app's stored files.
none
=> files: make the files server running as root

build/installer/install.ps1, build/installer/install.sh
Use the absolute path of ubuntu.exe to avoid failing to locate the file due to incorrect environment variables
1.11
https://github.com/beclab/Installer/pull/155
=> fix(installer): use the absolute path of ubuntu.exe

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Apps that cannot be upgraded in the upgrade list are shown as paused.
1.12
None
https://github.com/beclab/market/pull/65
None
=> market: allow paused apps to update

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Safari on desktop does not support PWA mode.
v1.11.0
none
https://github.com/beclab/desktop/pull/67
none
=> fix(desktop): disable PWA in safari on the desktop

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive:  fix dropbox async upload size error
when async upload file from terminus to dropbox, when upload compelete, upload redunat last chunk, but just need to upload empty chunk
release-1.1
https://github.com/Above-Os/drive/pull/85
=> fix: drop async upload filesize error

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Bulk HTTP requests from a single page exceeding the max keep alive requests number of ingress cause the requests from the browser to broken
v1.11.5 v1.12.0
Comfyui web client loading js requests broken
https://github.com/beclab/bfl/pull/71
=> bfl-ingress: increase keepalive requests of ingress

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml, frameworks/tapr/config/cluster/deploy/lldap-deployment.yaml
- app installation can not be canceled after reboot
1.12
None
https://github.com/beclab/app-service/pull/149
=> app-service: fix app installation can not be canceled after reboot

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml, build/manifest/images, frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- custom allowed outbound port
- tcp udp port can use same port
- add idle timeout to original_dst cluster
1.12
https://github.com/beclab/app-service/pull/153
https://github.com/beclab/app-service/pull/151
https://github.com/beclab/app-service/pull/154
=> app-service: custom allowed outbound port;tcp udp port

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
- trim registry mirror url path containing only slashes to avoid wrong handling by containerd when resolving and fetching images
- marking the os platform of WSL as linux when running in OIC container
v1.11.5
none
https://github.com/beclab/Installer/pull/159
https://github.com/beclab/Installer/pull/157
none
=> fix(installer): trim all redundant slashes in the mirror url; mark as linux in docker desktop with wsl

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive:  add id route for info,  fix file size limit
1. Add id route for fileinfo , for client to easy track for google cloud drive
2. Replace i32 with i64, remove upload filesize limit
release-1.11
https://github.com/Above-Os/drive/pull/89
https://github.com/Above-Os/drive/pull/88
=> feat: add id-route for file info, fix file size limit when direct upload

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
add a watcher for reverse proxy ConfigMap events, which is responsible for watching the `reverse-proxy-config` ConfigMap and applying the config if necessary.
v1.12.0
none
https://github.com/beclab/bfl/pull/70
none
=> feat(bfl): add watcher to apply reverse proxy

apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml, third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
fix: open the app in a new tab when on mobile and tablet devices
fix: update device identification logic
v0.11.0
none
https://github.com/beclab/desktop/pull/74
https://github.com/beclab/login/pull/25
=> login&desktop: open a new tab when on mobile and tablet devices

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
this is a cherry pick of https://github.com/beclab/Olares/pull/1013
add a watcher for reverse proxy ConfigMap events, which is responsible for watching the `reverse-proxy-config` ConfigMap and applying the config if necessary
v1.11.5
none
https://github.com/beclab/bfl/pull/70
none
=> feat(bfl): add watcher to apply reverse proxy (#1013)

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
- handle node shell change to bash
1.11
None
https://github.com/beclab/kubesphere-ext/pull/8
=> ks: handle node shell change to bash

apps/files/config/cluster/deploy/files_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml, apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, apps/vault/config/cluster/deploy/vault_server_deploy.yaml, apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- files：
- add support for new field id_path for google drive stream
- add CACHE_DIR to make appdata use the newest version correctly
- same logic of getting mounted data for 1.11 and 1.12
- uploader:
- change offset judge method for SMB 499
- improve uploading speed
- wise:
- add a filter feature to Wise
- update the database
1.12
None
[feat: Cumulative updates for files_drives from 1.12 to feed newest drive_server and 1.11 by lovehunt](https://github.com/beclab/files/pull/5)
[fix: same logic of getting mounted data for 1.11 and 1.12 by lovehunter9 · Pull Request #6 · beclab/](https://github.com/beclab/files/pull/6)
[fix: lost uploading info when reseting and change offset judge method …
=> wise, file: update files & wise new version to 1.3.38

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
- handle node shell change to bash
1.11
None
https://github.com/beclab/kubesphere-ext/pull/8
=> ks: node shell default use bash

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- hostpath with type DirectoryOrCreate exists with incorrect permission
1.11
None
https://github.com/beclab/app-service/pull/159
=> app-service: change hostpath with type DirectoryOrCreate owner to 1000 by inject init container

build/manifest/images
- add node shell image to pre download
1.11
None
None
=> fix: add node shell image to pre download

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
add support for swap & zram related configurations during installing Olares
the following environment variables can be set when executing `install.sh` in order to configure swap and ram
| env var name | explain | type | values | default |
| :--- | --- | --- | --- | --- |
| SWAPPINESS <br/> | Configure the Linux swappiness value | int | 0~100, refer to https://docs.kernel.org/admin-guide/sysctl/vm.html#swappiness | if not set, the current kernel configuration is left unchanged |
| ENABLE_POD_SWAP  | Enable pods on Kubernetes cluster to use swap, note that only pods of the Burstable QOS group can use swap due to K8s design | bool | 0, 1 | setting ENABLE_ZRAM, ZRAM_SIZE, or ZRAM_SWAP_PRIORITY implicitly enables this, regardless of the provided value |
| ENABLE_ZRAM | Set up …
=> feat(installer): support swap and zram configurations

build/manifest/images
the image `registry.k8s.io/kube-controller-manager:v1.32.2` was missed when updating images for K8s v1.32.
1.12.0
none
none
none
=> fix: add the missing kubernetes image

third-party/infisical/config/cluster/deploy/infisical_deploy.yaml
Some fields of the DB table `organizations` are missing in the OR mapping 
v1.12.0
Failed to restart Infisical sidecar
https://github.com/beclab/tapr/pull/46
=> tapr: add missing fields of db table organizations in `Infisical` sidecar

build/installer/wizard/config/settings/templates/system-serviceaccount.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml, frameworks/tapr/config/user/helm-charts/tapr/templates/tapr_deploy.yaml
- add tapr-image-role secrets permission
- fix create user cpu check
1.12
None
https://github.com/beclab/bfl/pull/81
=> tapr,bfl:add tapr-image-role secrets permission;fix create user cpu check

third-party/infisical/config/user/helm-charts/infisical/templates/infisical_deploy.yaml
Optimize the infisical sidecar performance, use the pod localhost address as the infisical server address to the infisical sidecar. 
v1.11.6
No response of the list secrets API 
none
=> olares: use the pod localhost address as the infisical server address to the infisical sidecar

third-party/infisical/config/cluster/deploy/infisical_deploy.yaml
Optimize the infisical sidecar performance, use the pod localhost address as the infisical server address to the infisical sidecar. 
v1.12.0
No response of the list secrets API 
none
=> olares: use the pod locahost address as the infisical server address to the infisical sidecar

build/installer/install.sh
olares-cli adds a set of commands for data backup and restoration. You can use `olares-cli olares backups -h` to get command help information.
```
Olares backup tool-kit
Usage:
olares-cli olares backups [command]
Available Commands:
backup      Back up data to multiple storage targets: Space, S3, COS, and local
download    Download the backup dependency tool Restic
restore     Restore data from multiple storage targets: Space, S3, COS, and local
snapshots   Manage and view backup snapshots
Flags:
-h, --help   help for backups
Use "olares-cli olares backups [command] --help" for more information about a command.
```
1.12
https://github.com/beclab/Installer/pull/171
=> feat(installer): support data backup, restore in olares-cli

apps/files/config/cluster/deploy/files_deploy.yaml, apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml, apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml, third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml, third-party/opentelemetry/config/user/helm-charts/opentelmetry/templates/otel_define.yaml
Fix some opentelemetry annotations configuration bugs
1、otel nginx instrumentation only supports version 1.24.3 and 1.25.3, 
2、Golang auto instrumentation configuration must specify the exec filename
v1.12.0
otel tracing not work
none
=> olares: fix the opentelemetry annotations configuration bugs

apps/files/config/cluster/deploy/files_deploy.yaml
- Background
files: 
files-server project structure reconstruction v2
chown to 1000 after creating folder (including os and fs)
add GET/PUT /api/permission API and change cache gateway relatively
smb permission denied text change to more readable
1.11
None
https://github.com/beclab/files/pull/10
=> feat: files permission relative

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
When copying and pasting a huge file in `Files`, the HTTP request gets a timeout response cause of the envoy reaches the 5 minutes idle timeout.
`Files server` responses 504 timeout. 
none
=> olares: increase envoy idle timeout for files-frontend

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
the following new commands are added:
`olares-cli olares start` to start an already stopped Olares system
`olares-cli olares stop` to stop an Olares system
`olares-cli olares logs` to collect logs of various components in Olares system
optimize the shutdown duration of Olares system
1.12.0
none
https://github.com/beclab/Installer/pull/172
https://github.com/beclab/Installer/pull/174
https://github.com/beclab/Installer/pull/175
https://github.com/beclab/Installer/pull/176
none
=> feat(installer): add commands to get logs & start/stop Olares; optimize shutdown performance

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive:  add id route for info,  fix file size limit
basically compelete s3 reconstruct, but still have some bug
main
* https://github.com/Above-Os/drive/pull/105
* https://github.com/Above-Os/drive/pull/104
* https://github.com/Above-Os/drive/pull/103
* https://github.com/Above-Os/drive/pull/102
* https://github.com/Above-Os/drive/pull/101
* https://github.com/Above-Os/drive/pull/100
* https://github.com/Above-Os/drive/pull/99
* https://github.com/Above-Os/drive/pull/98
* https://github.com/Above-Os/drive/pull/97
* https://github.com/Above-Os/drive/pull/96
* https://github.com/Above-Os/drive/pull/95
=> feat: basically compelete reconstruct s3

build/manifest/images, frameworks/GPU/config/gpu/hami/values.yaml
update the libvgpu.so lib file shipped with HAMI to a more tolerant one with lower version requirements for GLIBC
1.12.0
none
https://github.com/beclab/HAMi/commit/b3d2f621d5c2229069dddd06c2243ca810761ce0
none
=> fix(gpu): update libvgpu.so with more tolerant GLIBC requirements

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
When uploading the last chunk of a file,  `file-server` will copy the temporary file to the destination. Sometimes it will cause the upload API responsing 504 timeout.
uploading last chunk of a file got 504 timeout response
none
=> olares: uploading last chunk of a file got 504 timeout response

third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Authelia redis session cache needs to be gc if expired
v1.11.6
Bulk anonymous session cause Authelia memory leak
https://github.com/beclab/authelia/pull/6
=> authelia: fix cached redis session provider gc api

frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
Adding a namespace to kvrocks should call `config rewrite` command to persist the configuration to config file
kvrocks namespace config need to be recreated after restart
https://github.com/beclab/tapr/pull/50
=> tapr: persist kvrocks namespace config

apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3:  restore metadata when return data
reduce metadat when return to frontend
release-1.11
https://github.com/Above-Os/search3/pull/48
=> fix: restore metadata when return to frontend

apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3:  restore metadata when return data
reduce metadat when return to frontend
main
https://github.com/Above-Os/search3/pull/48
=> fix: add metadata when return to frontend

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Currently, custom domain for an app entrance is only supported in CloudFlare tunnel mode, this PR adds support for both CloudFlare and FRP tunnel, and handles the switching between them.
In FRP mode, which is a layer-4 reverse proxy, the HTTPS certificate for the custom domain should be uploaded.
1.12.0
none
https://github.com/beclab/bfl/pull/85
https://github.com/beclab/bfl/pull/89
https://github.com/beclab/settings/pull/94
none
=> feat: support custom domain in both cloudflare and FRP tunnel

apps/notifications/config/cluster/notification_deploy.yaml, third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Send user login-related message to notification server via nats message queue
v1.12.0
none
https://github.com/beclab/authelia/pull/10
=> authelia: send user login related message to notification server via nats

build/installer/upgrade_cmd.sh
The app name of devbox has changed to studio, modify the upgrade script app name `devbox` to `studio`
v1.11.6
System upgrade failed
none
=> olares: change app name devbox to studio

apps/files/config/cluster/deploy/files_deploy.yaml
`Files server` postgresql password variable name has changed in the secret.  It will cause system upgrading to fail. 
v1.11.6
System upgrading failed
none
=> olares: file server upgrade failed

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
the app-service needs this value to configure the settings for newly created users.
1.12.0
none
https://github.com/beclab/Installer/pull/189
none
=> fix(installer): add MARKET_PROVIDER to global envs

build/installer/install.ps1, build/installer/install.sh
fix error when path is not specified during file restoration by olares-cli
1.11.6
https://github.com/Above-Os/backups-sdk/commit/3246e815b9de919985d255a3534aafbf4628162a
=> fix(installer): olares-cli restore path not specified

build/installer/upgrade_cmd.sh, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
When system upgrading, app-service may be upgraded, checking the upgrading state API  should not return `not_running` at this time.
v1.11.6
The system upgrading page has been closed unexpectedly
https://github.com/beclab/bfl/pull/94
=> olares: fix upgrading state not_running bug

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive: fix locked not released when some thread corrupted
1. fix lock not released when direct upload file because of thread corruption
2. change async download chunk from 1 mb to 8mb
release1.11
* https://github.com/Above-Os/drive/pull/111
* https://github.com/Above-Os/drive/pull/112
=> fix: lock bug

apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive: fix locked not released when some thread corrupted
1. fix lock not released when direct upload file because of thread corruption
2. change async download chunk from 1 mb to 8mb
daily build
* https://github.com/Above-Os/drive/pull/111
* https://github.com/Above-Os/drive/pull/112
=> fix: fix cloud drive lock not released when some thread corrupted

frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- the app cache directory is not completely deleted in some case 
- check node status before system upgrade
1.11
None
https://github.com/beclab/app-service/pull/192
https://github.com/beclab/app-service/pull/193
=> app-service: fix cache delete not completely in some case;node status check before system upgrade

build/installer/upgrade_cmd.sh
Helm will format the numeric user name as scientific notation automatically, add the quotes to username in helm values
v1.11.6
System upgrade failed if Olares has one numeric user
none
=> olares: add quotes to username

apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Mark the market app as cluster critical to avoid eviction by kubelet
v1.11.7
none
none
=> olares: mark the market as cluster critical

frameworks/tapr/config/cluster/deploy/sys_event_deploy.yaml
For the ios device, local domain resolver needs to response the other query type except type A. So add a template plugin to corefile to response  type ANY with response code NXDOMAIN
v1.12.0
Local domain solution not working on ios device
https://github.com/beclab/tapr/commit/d7a531e574178ae425ed6c0c15f3a2c3e58f844f
=> tapr: add other query type response code

frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
When `tapr` is deleting the kvrocks' middleware request, if the namespace does not exist, the deletion should be ignored to avoid returning an error.
v1.11.7
none
none
=> tapr: ignore deleting the not exists namespace

frameworks/tapr/config/cluster/deploy/sys_event_deploy.yaml
Updating the Coredns configuration corefile, the template args will be changed to the wrong format
v1.12.0
When added a new user, the local domain not work
https://github.com/beclab/tapr/commit/3613d86ff3cebab4044ed238fac0cf9fe7d4fa66
=> tapr: fix corefile updating bug

README.md, README_CN.md, README_JP.md
Update the support info to direct users to direct users to Linux as the official recommended platform.
=> docs: update Olares platform support info

frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_backups.yaml, frameworks/backup-server/config/cluster/deploy/backup_server.yaml
missing resticSnapshotId in restoration process, fixed api bug, refined api response data format
1.12
https://github.com/beclab/backup-server/pull/16
https://github.com/Above-Os/backups-sdk/pull/12
=> backup-server: restore params invalid, api response data format

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
Save the metadata value of basedir and version in the /etc/olares/release file with a dot env format, like the /etc/os-release file, so that users need not to specify these arguments explicitly, e.g.:
```
~ cat /etc/olares/release
OLARES_BASE_DIR="/home/keven/.olares"
OLARES_VERSION="1.11.7"
```
1.11.7
none
https://github.com/beclab/Installer/pull/193
none
=> feat(installer): save metadata to and read from release file

third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
Specify Jaeger collector runs as user 1000 to get the port listening permission
v1.12.0
Sometimes Jaeger collector got the port listening permission denied error.
none
=> otel: run collector as user 1000

frameworks/tapr/config/cluster/deploy/sys_event_deploy.yaml
Replace dns rcode NXDOMAIN with NOERROR in local domain
v1.12.0
none
https://github.com/beclab/tapr/commit/3589e7cc85bd5ed22a45972edfe78ed2fe1e004c
=> tapr: replace nxdomain with noerror

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
When adding an ACL port, the second custom port confirmation button cannot be clicked
1.12
none
https://github.com/beclab/settings/pull/97
none
=> fix: settings frontend add ACL port ui bug

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
after the revamp of the pod operation console for controlHub workloads, the issue of layout disorder on small screens has been optimized.
v1.11
none
https://github.com/beclab/system-apps/pull/37
none
=> ControlHub: fix workloads operation layout

build/installer/upgrade_cmd.sh, frameworks/tapr/config/cluster/deploy/redixcluster_deploy.yaml
Force update kvrock workload definition 
v1.11.7
System-upgrade does not update kvrocks configuration of namespace persistence
none
=> tapr: force update kvrock workload definition

build/installer/install.ps1, build/installer/install.sh, build/installer/joincluster.sh
add error message output when using cli for backup and restore, fix traceId is nil
1.11.7
https://github.com/Above-Os/backups-sdk/pull/19
https://github.com/Above-Os/backups-sdk/commit/c10ce08025932592aca0f90bb51fa718e4acd601
=> fix(installer): add error message output when using cli backup

apps/files/config/cluster/deploy/files_deploy.yaml
- Background
files: 
add smb readonly field (not used by frontend for the time being)
add del all thumbs and renaming try to the beginning of moving folder
use rm -rf with ls retry for only smb when deleting at the ending of moving folder
v1.12.0
none
https://github.com/beclab/files/pull/14
none
=> fix: files-server rename and cut/paste of smb bugfix

third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
the current manifest of the Otel-related CRDs do not specify a hook, and helm upgrade will fail to run because other resources are being recreated.
1.12.0
none
none
none
=> fix: create crd in helm post-install hook

build/installer/version.hint
The [semver spec on the pre-release version](https://semver.org/#spec-item-9) specifies that leading zeros are illegal.
We change the current `0000` to `1` so that any daily-build and RC release version satisfy the minVersion requirement.
1.12.0
none
none
none
=> fix: correct minVersion in version.hint to follow semver spec

frameworks/backup-server/config/cluster/deploy/backup_server.yaml
abnormal restoration state, api interface improvement, resolved the repository size retrieval failure when backing up to Tencent COS space
1.12.0
https://github.com/beclab/backup-server/pull/22
https://github.com/Above-Os/backups-sdk/pull/20
=> backup-server: abnormal restoration state, get space cos stats failed

build/manifest/images, frameworks/GPU/config/gpu/hami/values.yaml
merge updates of HAMi from upstream and temporarily revert libvgpu.so to the official version. (i.e., without nvshare)
1.12.0
none
https://github.com/beclab/HAMi/commit/c49e679dfa056862ffd4bb90eec977ab869647e5
none
=> feat: upgrade hami and use original libvgpu.so

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
The Olares password is transmitted in plain text during the interface transmission process, which is not secure and needs to be changed to encrypted transmission.
1.12
None
https://github.com/beclab/TermiPass/pull/422
None
=> feat(settings): Encrypted transmission of login password

frameworks/bfl/config/launcher/templates/bfl_deploy.yaml, frameworks/bfl/config/launcher/templates/otel_define.yaml, third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
Fix go instrumentation resource limit typo
v1.12.0
go instrumentation resource limit not working
none
=> olares: fix go instrumentation resource limit typo

apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Fixed the issue that the interface is not called when creating a sub-account
1.12
None
https://github.com/beclab/TermiPass/pull/441
None
=> fix(settings): the problem of failure to create sub-account

build/manifest/images, frameworks/bfl/config/launcher/templates/otel_define.yaml, third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
OpenTelemetry nginx auto-instrumentation will lose the context configuration when nginx reloads the config.
v1.12.0
BFL Ingress openresty auto-instrumentation not work
None
=> otel: nginx auto instrumentation config reload bug fix

apps/notifications/config/cluster/deploy/notification_deploy.yaml
the current `{{- $namespace := printf "%s%s" "os-system" -}}` prints out an incorrect "os-system%!s(MISSING)" instead of "os-system"
1.12.0
none
none
none
=> fix(chart): remove redundant format symbol in template

frameworks/bfl/config/launcher/templates/otel_define.yaml, third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
Bump the go auto-instrumentation image version and change the API  protocol
v1.12.0
none
none
=> otel: bump the go auto-instrumentation image version

build/manifest/images, frameworks/bfl/config/launcher/templates/otel_define.yaml, third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
Opentelemetry Nginx auto-instrumentation sets too many headers in the request.
v1.12.0
Files can not mkdir
https://github.com/beclab/opentelemetry-cpp-contrib/commit/9363fe8f662a29ee0add0aaf5715d98f6ce32ab3
=> otel: fix nginx instrumentation too many headers

build/manifest/images, frameworks/bfl/config/launcher/templates/bfl_deploy.yaml, frameworks/bfl/config/launcher/templates/otel_define.yaml, third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
Fix nginx instrumentation arm64 build script bug
Optimize bfl pod network sys config
Optimize dynamic client by using dynamic resource informer in BFL api
v1.12.0
Nginx instrumentation crashed when loading functions from the dynamic library
https://github.com/beclab/opentelemetry-cpp-contrib/commit/1cd1dfa523ff432eb58d7407c44bdd72bc272c64
=> otel: fix nginx instrumentation arm64 build script bug

framework/tapr/.olares/config/cluster/deploy/middleware_deploy.yaml
`Knowledge` needs privileges to backup and download pg data on the server, add  two roles `pg_write_server_files`, `pg_read_server_files` to pg users
v1.12.0
none
https://github.com/beclab/tapr/pull/58
=> tapr: add roles to pg user

build/base-package/install.ps1, build/base-package/install.sh, build/base-package/joincluster.sh, infrastructure/kubesphere/.olares/Olares.yaml
- batch/v1beta1 has been deprecated
1.12
None
https://github.com/beclab/kubesphere-ext/pull/19
=> ks: update cronjob gv to batch/v1

.github/workflows/check.yaml
the old version var in the download url for CI deploying test is missed when refactoring workflow file
1.12.0
none
none
none
=> fix(ci): pass correct version var when deploying in CI

cli/pkg/pipelines/gpu_upgrade.go
the `gpu.bytetrade.io/cuda` label is set to the CUDA version on a node during installation, but not updated when upgrading through `olares-cli gpu upgrade`
1.12.0
none
none
none
=> fix(cli): update CUDA version in node labels after upgrading GPU driver

cli/pkg/gpu/prepares.go
Some GPU cards declare themselves as a `3D controller` rather than `VGA compatible controller` to the PCI bus, which is not considered when detecting GPU cards in the machine. And it should also be considered.
1.12.0
none
none
none
=> fix(cli): also consider 3D controller when detecting GPU by lspci

build/base-package/install.sh, cli/cmd/ctl/os/release.go
the current `local` flag in the auto-generated version of Olares local release results in the frontend to fail authentication
1.12.0
none
none
none
=> fix(cli): remove the local flag in local release version

framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
1. Add a new api olares-info to replace the deprecated api terminus-info later
2. Change the ingress default fallback page to olares.xyz
v1.12.0
none
https://github.com/beclab/bfl/pull/101
=> bfl: add a new olares-info api

cli/pkg/gpu/tasks.go
Currently, when installing GPU driver, the `nvidia-kernel-open` is installed first and then `nvidia-driver`, whereas they're actually a same driver, just an open-sourced one and a proprietary one. And they're also mutually exclusive, with the installation of the latter effectively removing the former.
1.12.0
none
none
https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2204/x86_64/Packages
=> fix(cli): just install a single instance of GPU driver

cli/pkg/bootstrap/precheck/tasks.go
Currently, 5090m GPU cannot be detected by 12.9 CUDA Toolkit
1.12.0
none
none
none
=> fix(cli): lift cuda version restraint to 12.8

framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
1. Adding scheme to k8s client go in the http api handler will cause the concurrent map writes issue
2. Bulk HTTP clients for app-service
v1.12.0
bfl crashed when performance testing
https://github.com/beclab/bfl/pull/102
=> bfl: crash and bulk http clients

apps/.olares/config/cluster/deploy/files_deploy.yaml
Background
fix:
- files-server: sync (seafile) dir rename bug
- appdata-gateway: fatal error, concurrent map writes
v1.12.0
Related Issues
none
https://github.com/beclab/files/pull/18
https://github.com/beclab/files/pull/19
none
=> fix: files sync dir rename bug

.github/workflows/release-daily.yaml
change the wrong version `github.event.input.tags` of normal release to the corrent version `needs.daily-version.outputs.version` of daily release.
1.12.0
none
none
none
=> fix(ci): use correct daily release version for daemon

.github/workflows/check.yaml, .github/workflows/release-cli.yaml, .github/workflows/release-daemon.yaml, .github/workflows/release.yaml
`actions/checkout` does not persist across workflow calls, and the git ref it checks out defaults to the default branch (main), which should be the HEAD of PR branch and release tag, respectively, when doing PR test and formal release.
1.12.0
none
none
none
=> fix(ci): pass in git ref when calling workflow for submodule

daemon/pkg/cluster/state/current.go
currently, the `upgradeingTarget` field in the system state of olaresd is not reset when not upgrading.
1.12.0
none
none
none
=> fix(daemon): reset upgrade target when not upgrading

framework/gpu/.olares/config/gpu/hami/templates/gpu-scheduler/daemonset.yaml, framework/gpu/.olares/config/gpu/hami/templates/gpu-scheduler/namespace.yaml, framework/gpu/.olares/config/gpu/hami/templates/gpu-scheduler/service.yaml, framework/gpu/.olares/config/gpu/hami/values.yaml
install gpu-scheduler in the dedicated namespace gpu-system for fine-grained network policy control
1.12.0
none
https://github.com/beclab/HAMi/commit/dd34a3097c57a811ad6a86b71630f8971bc35f76
none
=> feat: dedicated namespace for gpu-scheduler

framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: fix search3monitor error
1. delete exist resource_uri for moved to event
2.  limit search3 db pool max_connection
daily build
https://github.com/Above-Os/search3/pull/56
https://github.com/Above-Os/search3/pull/55
=> fix: fix movedto event error

.github/workflows/release-daily.yaml, .github/workflows/release.yaml
The `joincluster.sh` script is not copied back to the `build` directory after the Olares version placeholder has been substituted in the release CI, resulting the original script being released 
1.12.0
none
none
none
=> fix(ci): copy back joincluster script before releasing

framework/files/.olares/config/cluster/deploy/files_deploy.yaml
Background
fix:
- files-server: copy task cancel bug
v1.12.0
Related Issues
none
https://github.com/beclab/files/pull/23
none
=> fix: files-server copy task cancel bug

framework/gpu/.olares/config/gpu/hami/templates/scheduler/deployment.yaml, framework/gpu/.olares/config/gpu/hami/values.yaml
the current way to schedule hami-scheduler pod to master node by specifying `.spec.nodeSelector` is not expressive enough and cannot handle the case where the label exists but with an empty value, we change it to node affinity to handle both cases, whether it has a value or not.
1.12.0
none
none
none
=> fix(gpu): use node affinity to select master node for hami-scheduler

framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: fix search3monitor title document language detect error
1. The original title language detection was based on a combination of Facebook's fastText and lingua-rs, striking a balance between memory usage and accuracy. However, for short texts like titles, there were still cases where the language could not be detected or was detected incorrectly. Now, the detection is based purely on lingua-rs, which offers highe accuracy at the cost of higher memory usage (with the model occupying around 400MB of memory resident at all times).
2.  When uploading a file to the Olares host, the file is assigned a temporary path or identifier. Because it only exists for a short period of time, the file may disappear from the disk before it is inserted into the …
=> fix: fix monitor document title detection language error

framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: fix-search3-error
1. Some batch operations on the database involve writing raw SQL statements, and certain filenames contain special characters that need to be escaped; otherwise, execution errors may occur.
2. For filenames like ‘bzhan Nars新计划 [BV1bMTYzrEz3].m.mp4’, a search using "nars" can find the file, but extracting the highlight phrase fails, resulting in nothing being returned to the frontend.
daily build
https://github.com/Above-Os/search3/pull/62
https://github.com/Above-Os/search3/pull/63
https://github.com/Above-Os/search3/pull/64
https://github.com/Above-Os/search3/pull/65
https://github.com/Above-Os/search3/pull/66 …
=> fix: fix search3 error

cli/.goreleaser.yaml
Currently, ARMv7 version of olares-cli is built in release CI on all ARM-based systems regardless of specific arch, for some newer CPUs without ARMv7 backwards compatibility, it can fail to run.
1.12.0
https://github.com/beclab/Olares/issues/1445
none
none
=> refactor(cli): distinguish between 32-bit and 64-bit arch in release ci

apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml, framework/analytics/.olares/config/cluster/deploy/analytics_deploy.yaml, framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml
**Background**
We use webpack to package a TypeScript project to reduce the Docker image size.
Specifically, since these projects use Prisma, we package the Prisma client library but not the Prisma core library in the Docker image.
When the program starts, the entrypoint calls npx prisma migrate, which triggers npm install. This causes two issues:
1. When the network is poor, the container fails to resolve [npmjs.org](https://npmjs.org/), preventing the Docker container from starting normally.
2. It takes up to a minute for the service to go online, which is time-consuming.
Therefore, we decided to package the Prisma core library into the Docker image, which increases each Dockerfile size by 70MB.
Considering that we plan to rewrite these three projects in Rust or Go, we are willing to …
=> feat(user-service, notification, analytics): put prisma library under node_moudles in dockers

framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: daemonset
1. search3monitor support multiple node for external and cache
2.  search3monitor run as daemonset
daily build
https://github.com/Above-Os/search3/pull/78
=> feat: search3 support multiple node for cache and external, run as daemonset

cli/pkg/k3s/tasks.go, cli/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
So that kubelet will start image gc when available space of imagefs is less than 10%
1.12.0
none
none
none
=> feat(cli): set explicit image gc policy when installing K8s

daemon/internel/apiserver/handler_ifs.go, daemon/internel/mdns/server.go, daemon/pkg/commands/upgrade/install_olaresd.go
1. Add more fields to network interfaces api when test-connectivity option is false
2. Fix nvstream mDNS service, for steam headless, restarting bug
v1.12.0
Cannot be discovered by Moonlight client
none
=> olaresd: network interface api modifed and nvstream mdns bug fix

framework/argo-workflow/.olares/config/cluster/deploy/server-deployment.yaml, framework/argo-workflow/.olares/config/cluster/deploy/workflow-controller-deployment.yaml
Add missing app author label `applications.app.bytetrade.io/author: bytetrade.io` to argo workflow deployments
1.12.0
none
none
none
=> fix(manifest): add missing app author label to argo deploy

framework/reverse-proxy/.olares/Olares.yaml
in https://github.com/beclab/Olares/pull/1443, the version of reverse proxy image was updated to `0.1.10` in the bfl deployment manifest but left the Olares.yaml unchanged
1.12.0
none
none
none
=> fix(manifest): update the missed reverse proxy image version

framework/infisical/.olares/config/cluster/deploy/infisical_deploy.yaml
When a user is not synced, responding `user not found` in the secret-list api.
v1.12.0
Infisical got crashed when the secret-list api is called if the user is not synced
https://github.com/beclab/tapr/commit/58496077548269b33fccd5f66dabd72219f69dca
=> infisical: crash when user not found

framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
When the new user is created, BFL will create the user's directory and change the owner to the user. When the cluster is restarted, it's unnecessary to change the owner again.
v1.12.0
Some apps' data directory permissions were changed when the cluster was restarted.
none
=> bfl: do not change owner when restart

framework/infisical/.olares/config/cluster/deploy/infisical_deploy.yaml
Failed to create user because a ‘user not found’ error was thrown in the wrong place.
v1.12.0
Failed to create user in infisical sidecar.
https://github.com/beclab/tapr/commit/759c04e6d59998b3fc32936c16f44603002b31d0
=> infisical: create user error

cli/pkg/plugins/dns/templates/coredns_service.go
The `endpoint_pod_names` config option in the [`Kubernetes` plugin](https://coredns.io/plugins/kubernetes/) of CoreDNS tells CoreDNS to serve A records resolved by pod names, in addition to service names, and allows us to proxy requests to specific pods, such as a files service on a specific node.
1.12.0
none
none
none
=> feat(cli): config endpoint_pod_names in coredns when installing

daemon/go.mod, daemon/pkg/cluster/state/utils.go
when Olaresd checks whether a particular process is running, it reads and parses the corresponding pid file, if file exists but contains an empty string, strconv.Atoi("") will fail with "invalid syntax", causing Olaresd to stuck forever in the error state, this case should be checked first and return early.
1.12.0
none
none
none
=> fix(daemon): handle empty pid files when check process running

cli/pkg/bootstrap/os/templates/init_script.go
In https://github.com/beclab/Olares/pull/1502, the local reserved ports is changed, but the modifying of existing sysctl.conf logic is missed.
1.12.0
none
none
none
=> fix(cli): also update local reserved ports when modifying sysconf

cli/pkg/phase/cluster/delete_cluster.go, cli/pkg/terminus/modules.go, cli/pkg/terminus/tasks.go
Currently there's no limit on uninstallation, which means uninstallation can also happen during upgrading, thus upgrade-related state files should also be cleared when uninstalling
1.12.0
none
none
none
=> fix(cli): clear upgrade-related state files when uninstalling

platform/tapr/.olares/config/cluster/deploy/middleware_deploy.yaml
- user-service may can not get mesage from subject
1.12
None
https://github.com/beclab/tapr/pull/67
=> tapr: add default perm for nats subject

.github/workflows/check.yaml, .github/workflows/release-cli.yaml, .github/workflows/release-daemon.yaml
`repository` must be specified when calling [actions/checkout](https://github.com/actions/checkout), or it fails for PRs from a forked repo.
1.12.0
none
none
=> fix(ci): specify repo when checkout code for PR

daemon/pkg/utils/k8s.go
The current user filter in olaresd has no actual effect in the two-level nested for loop
1.12.0
none
none
none
=> fix(daemon): apply filters correctly when listing users

framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
Change unmount-api route path of `file server` from /api/unmount to /api/unmount/external
v1.12.0
none
https://github.com/beclab/bfl/pull/112
=> bfl: change unmount-api of file-server

framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
When k8s has multiple nodes, l4-bfl-proxy and headscale/tailscale may be scheduled to different nodes
1.12.0
=> fix(headscale): Make the Affinity Rule Strict

cli/pkg/common/kube_runtime.go
`arg.User` is initialized in `NewArgument` so the pointer is always non-nil, correct non-emptiness check should be further extended to the specific fields.
1.12.0
none
none
none
=> fix(cli): check emptiness of user and domain before write release file

docs/manual/docs-home.md
Fixed the use case link error on doc home page
=> docs: fix use case link on main

cli/cmd/ctl/os/upgrade.go, cli/pkg/upgrade/version.go
when getting upgrade path or doing upgrade, all three of: base/target/olares-cli version must be on the same release line
the output order of upgrade path can be optionally reversed and defaults to the latest version in the first
1.12.0
none
none
none
=> feat(cli): adjust release line constraint and output order of upgrade path command

infrastructure/gpu/.olares/config/gpu/hami/values.yaml, platform/hami/.olares/Olares.yaml
The metrics exporting API in HAMi-WebUI is adjusted for our modification of HAMi
Also, the libvgpu.so is updated with the latest build of our fork
1.12.0
none
https://github.com/beclab/HAMi-WebUI/commit/021105dfdfae2d267911f88d8939b691c0c90024
https://github.com/beclab/HAMi/commit/59966b0c2dd6406e2c794f21a0cb514020af06c2
none
=> feat(gpu): update metrics API for HAMi-WebUI and library for HAMi

build/build-manifest.py
As image layers are stored and retrieved from image registry in gzipped tar archives, but Containerd stores and also extracts them in the form of original tar files, we need to know the uncompressed size in order to calculate a more accurate disk space needed for upgrade download.
1.12.0
none
none
none
=> feat(ci): retrieve and save uncompressed size of layers in image manifest

build/upload-images.sh
Image layers are not compressed when generating archives by `docker save`, take the image `beclab/hami:v2.5.4` as an example:
```
➜  ~ sudo docker save mirrors.joinolares.cn/beclab/hami:v2.5.4 > docker-hami.tar
➜  ~ mkdir docker-hami
➜  ~ tar xf docker-hami.tar -C docker-hami
➜  ~ file docker-hami/blobs/sha256/*
docker-hami/blobs/sha256/096e1df4f7d9bdf9dba4a48975218030baae0f559d8e1c8481ba43dd7e3797cf: JSON data
docker-hami/blobs/sha256/0df26ec8d5656f0db50c6b71bc74210997320bc3bb6f3e316cef32511513dce1: JSON data
docker-hami/blobs/sha256/14b6e58bdddd8a008a31e21f23c87708544af7ed1929a194bf1af7ed3cd5488b: POSIX tar archive
docker-hami/blobs/sha256/1954c94787cadb0888f5c98b32d139fdddbeef342aecd199b7504a168ce3ab4c: POSIX tar archive …
```
=> perf(ci): use skopeo to upload image archive to cdn

framework/README.md
Background
Since the release cycle of applications such as knowledge and wise is inconsistent with the main Olares project, we moved them to independent repositories and released them through the app market.
1.12.0
Related Issues
none
none
none
=> feat(docs): Remove knowledge, rsshub and argowoflow infomation from Readme

build/build-manifest.py
In https://github.com/beclab/Olares/pull/1570, we tried to retrieve the uncompressed size of every layer of all images, which significantly slows the CI workflow, also, considering that most of our archived images are generated by docker save, compare existing contents by sha256 hash is mostly useless, this PR reverts that commit.
1.12.0
none
none
none
=> Revert "feat(ci): retrieve and save uncompressed size of layers in image manifest (#1570)

framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
Add cluster app ref label to the namespace of the workflow to make the knowledge backend accessible for the workflow tasks
v1.12.0
The tasks of the workflow cannot access the knowledge backend service.
https://github.com/beclab/app-service/commit/6b1164e816e8070b9428c4aa2e6a3f0df6754adb
=> app-service: add workflow label to the namespace of workeflow

framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
Check the remaining disk space in real time during backup and restore, and fix the issue where special characters in the file list during app backup are recognized as wildcards.
1.12
https://github.com/beclab/backup-server/pull/49
https://github.com/Above-Os/backups-sdk/pull/36
https://github.com/Above-Os/backups-sdk/pull/37
=> fix(backup): add check disk space

cli/go.mod, cli/pkg/container/containerd.go, cli/pkg/container/templates/containerd_config.go, cli/pkg/gpu/module.go, cli/pkg/gpu/tasks.go, cli/pkg/images/load.go, cli/pkg/upgrade/1_12_0_20250723.go, cli/pkg/upgrade/modules.go, cli/pkg/upgrade/version.go, daemon/internel/watcher/upgrade/upgrade_watcher.go, infrastructure/containerd/.olares/Olares.yaml
Upgrade Containerd to `v2.1.3`
Deprecated and unnecessary default configs in the current config template are removed, according to [Deprecated config properties](https://containerd.io/releases/#deprecated-config-properties), except the `[plugins."io.containerd.grpc.v1.cri".registry.mirrors]` that multiple services rely on
When configuring Nvidia runtime for Containerd using `nvidia-ctk`, the config source is changed from command to file, to avoid a config migration to version 3
An upgrade version for the incoming daily build `1.12.0-20250723` is also added, to upgrade Containerd
1.12.0
none
none
none
=> feat: upgrade containerd to v2.1.3

framework/monitor/.olares/config/cluster/deploy/ks_server_deploy.yaml
User metadata has reconstructed the label data, and the monitoring server needs to perform some compatibility processing.
1.12
none
https://github.com/beclab/ks-apiserver-proxy/pull/2
none
=> fix(monitoring-server): update monitoring server role management

framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
When k8s has multiple nodes, headscale and tailscale may be scheduled to different nodes
1.12.0
=> fix: make the affinity rule strict for tailscale

build/build.sh, framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml, framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
1. Change the internal mode rule that only requests via Larepass VPN will match the rule
2. Fix admin user resets the password of another user bug
3. Get the real client IP from the proxy protocol header sent by frp
4. OnFirstFactor message data fix
v1.12.0
The user's password, which has been reset, is still a valid password
https://github.com/beclab/authelia/pull/26
https://github.com/beclab/l4-bfl-proxy/commit/c2d6a93ac9c7c1b258f45c4a06ac357831537ad1
=> bfl, authelia: fix internal mode and get real ip

cli/.goreleaser.yaml, cli/pkg/files/file.go, cli/pkg/terminus/tasks.go, cli/version/vendor.go, daemon/cmd/terminusd/version/vendor.go
Inject `VENDOR_REPO_PATH` from the env`OLARES_VENDOR_REPO_PATH` when building olares-cli, and download wizard from the specific vendor path
1.12.0
none
none
none
=> feat(cli): download wizard from different vendor path

cli/pkg/upgrade/base.go, daemon/internel/watcher/upgrade/upgrade_watcher.go, daemon/pkg/commands/operations.go, daemon/pkg/commands/upgrade/check.go
In upgrade's precheck, if any user is in the progress of activation, wait for it to complete
Already activated user's wizard should be skipped when upgrading
1.12.0
none
none
none
=> fix(upgrade): wait for user to finish activation before upgrading

infrastructure/gpu/.olares/config/gpu/hami/values.yaml, platform/hami/.olares/Olares.yaml
Revert https://github.com/Project-HAMi/HAMi/commit/0b48f3c3c85e2b9f0576f36ed7f38d2fdedf52d9#r162715985 that causes hami-scheduler to panic
1.12.0
none
https://github.com/beclab/HAMi/commit/595f0661222ae9e800d4b5691a200a0b81952908
none
=> fix(gpu): revert buggy code change from upstream

cli/pkg/common/kube_runtime.go, cli/pkg/core/connector/system.go
The kernel of Linux container on Windows has a `-wsl` suffix, which will be considered as WSL. 
v1.12.0
OIC on Windows install failed
none
=> cli: fix the installation in oic on Windows

cli/pkg/common/common.go, cli/pkg/images/load.go, cli/pkg/kubesphere/minikube.go, infrastructure/kubernetes/.olares/Olares.yaml
Fixes some errors that fail the installation on MacOS using Minikube:
Upgrade K8s to v1.33.3 when starting cluster using Minikube
Import images into containerd using native ctr command
Removed unused image with a fixed amd64 architecture  
1.12.0
none
none
none
=> fix(cli): installation on MacOS using minikube

framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
When reloading app policies, ignore errors for one user to ensure that the policies for other users are successfully reloaded.
v1.12.0 v1.12.1
When a new user creating, app policies cannot be reloaded.
https://github.com/beclab/authelia/pull/29
=> authelia: ignore error when app policies reloading

framework/market/.olares/config/cluster/deploy/market_deploy.yaml
In the case of missing URL, the market will try to find the URL from the secp information. This action ignores the username matching, resulting in the wrong information being found.
1.12.0
https://github.com/beclab/market/commit/8678eee7cfb003bc6ca33835697f31b3ee0a7630
=> fix: entrance url matching error in market

cli/pkg/bootstrap/os/module.go, cli/pkg/bootstrap/os/tasks.go
In some systems, the default config file for sysctl `/etc/sysctl.conf` is not read after reboot, due to a missing `/etc/sysctl.d/99-sysctl.conf` that symbolically links to it, in such cases, we create the missing symlink.
1.12.0
none
none
see also https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/2084376
=> fix(cli): create symlink to sysconf if none exists

framework/chart-repo/.olares/config/cluster/deploy/chart_repo_deploy.yaml
In cases of network anomalies, a large number of rendering failures occur in a short period of time, resulting in applications being classified as abnormal and unable to render. This submission provides a regular opportunity for these applications to be retried
1.12.1
https://github.com/beclab/dynamic-chart-repository/commit/77e0754625a2ab74ddb1f8ec57465ea361a77091
=> fix: update check condition for failed task in chart repo

framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
When the ephemeral user is initializing, send the cookie to the wizard subdomain instead of the parent domain.
v1.12.1
Initializing the new user in the same browser will make the admin user's access forbidden.
https://github.com/beclab/authelia/pull/30
=> authelia: send the cookie of an ephemeral user to subdomain

.gitignore, cli/pkg/bootstrap/precheck/tasks.go
This PR modifies the cli to alow a user to bypass the failer on an unsupported os to allow for better testing.
It also modifies the .gitignore to prevent unwanted build files and output binaries from being commited.
This PR did use ai code but I did verify all code worked and was accurate.
I testes the binary on both an previously working os and ubuntu devel branch. It appered to work on both.
Issues that should be closed because of this PR
#1645 
old issues that have since been recitfied
#723
#890
=> feat(testing‑mode): allow installation on unsupported OS + ignore build artifacts

framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- Background
fix: cloud move delete and fix a bug because of mkdir for copy and upload
1.12.1
none
https://github.com/beclab/files/pull/57
https://github.com/beclab/files/pull/58
none
=> fix: cloud move delete and fix a bug because of mkdir for copy and upload

.github/workflows/release-cli.yaml, .github/workflows/release-daemon.yaml, .github/workflows/release-daily.yaml, .github/workflows/release.yaml, build/base-package/install.ps1, build/base-package/install.sh, build/base-package/joincluster.sh, build/build-manifest.py, build/build-manifest.sh, build/build.sh, build/deps-manifest.sh, cli/.goreleaser.yaml, cli/cmd/ctl/options/download_options.go, cli/pkg/files/file.go, cli/pkg/phase/download/download_wizard.go, cli/pkg/pipelines/download_wizard.go, cli/pkg/terminus/modules.go, cli/pkg/terminus/tasks.go, daemon/.goreleaser.yml, daemon/.olares/Olares.yaml
To address the issue that a released version may need to be overridden by a new release action, and thus need a manual refresh to the CDN. We differentiate multiple releases of the same version by suffixing their commit hashes to the released artifacts stored in the CDN.
All archived components that are unified with the main release version or scripts that need to download these archives, specifically:
install-wizard(including its contained manifests)
olares-cli
olaresd
install/join scripts
when  released on the main/daily line, will be suffixed with the release id(commit hash)
The auto-installation CI for pull request check is not changed.
All modifications are backwards compatible, i.e., if release id is not specified, the old archive format is used.
* **Target Version …
=> feat(ci): differentiate multiple releases of the same version

.github/workflows/release-daily.yaml, .github/workflows/release.yaml
The md5sum check logic has been moved from the install script to olares-cli, and is no longer used.
1.12.1
none
none
none
=> chore(ci): remove unused md5 render step in release workflow

.github/workflows/release-daily.yaml, .github/workflows/release.yaml
In https://github.com/beclab/Olares/pull/1727, a new param called release id has been added for `build/bash.sh` but was missed in some steps of the workflow.
1.12.1
none
none
none
=> fix(ci): add missing param for release_id when uploading package

.github/workflows/release.yaml
In https://github.com/beclab/Olares/pull/1724, some version input in the `release` workflow mixed with that of the `release-daily` workflow
1.12.1
none
none
none
=> fix(ci): correct input source of release version in workflow

.github/workflows/release-daily.yaml, .github/workflows/release.yaml, cli/pkg/release/manifest/manifest.go
Adjust the local release command `olares-cli release` to align with the new changes introduced in https://github.com/beclab/Olares/pull/1724, specifically, in addition to get the latest daily build tag, its commit hash is also retrieved to generate the final manifest. The commit hash in release CI is set to a fixed length for the local release command.
1.12.1
none
none
none
=> feat(cli): adjust local release command for release id

cli/cmd/ctl/os/upgrade.go, cli/pkg/pipelines/upgrade.go, cli/pkg/upgrade/1_12_0_20250702.go, cli/pkg/upgrade/1_12_0_20250723.go, cli/pkg/upgrade/1_12_0_20250730.go, cli/pkg/upgrade/1_12_1.go, cli/pkg/upgrade/base.go, cli/pkg/upgrade/interfaces.go, cli/pkg/upgrade/version.go
Switch the current single-flow path-based upgrade mechanism, to a multi-dimension matrix-based one.
Two new subcommands of `upgrade` is added to the `olares-cli`:
`spec`: returns the upgrade spec of the current version, in JSON format, including its version numbers, release type(`stable`/`daily`/`rc`/`beta`/`alpha`), whether breaking change is introduced, and what versions are supported to upgrade to it, distinguished by different release types.
`viable`: whether a base-version can upgrade to the current version.
1.12.1
none
none
none
=> refactor(upgrade): remove path cmd & add spec/viable cmd for upgrade

cli/pkg/etcd/templates/backup_service.go, cli/pkg/upgrade/1_12_1_20250826.go, cli/pkg/upgrade/version.go
The script that `backup-etcd.service` executes clears history data by parsing the filenames using awk, but for different locales, the output of `ls -lt` is inconsistent, this can be avoided by explicitly setting the locale in the systemd service config.
1.12.1
none
none
none
=> fix(cli): explicitly set locale in etcd backup service

cli/pkg/web5/jws/checkjws.go
* Renamed the `resolveDID` function to `ResolveOlaresName` in `cli/pkg/web5/jws/checkjws.go` to better reflect its purpose and updated all references to use the new name. 
v1.12.1
none
none
=> cli: Rename resolveDID to ResolveOlaresName

framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml, framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml, framework/files/.olares/config/cluster/deploy/files_deploy.yaml, framework/system-server/.olares/config/user/helm-charts/systemserver/templates/permission.yaml
1. Change the namespace of the user-backend service account
2. Add privileges to user-backend service account
v1.12.1
none
none
=> systemserver: change user-backend service account namespace and privilege

framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- Background
recons files by hertz instead of mux/http
v1.12.1
none
https://github.com/beclab/files/pull/82
=> feat: files http hertz recons

framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
As stated in https://github.com/beclab/bfl/security/dependabot/20, the current jwt library we depend on has a high-level vulnerability, and also this project has already been archived 3 years ago, this PR migrates the jwt dependency to the https://github.com/golang-jwt/jwt
1.12.1
https://github.com/beclab/bfl/security/dependabot/20
https://github.com/beclab/bfl/security/dependabot/25
https://github.com/beclab/bfl/pull/130
https://github.com/beclab/bfl/pull/131
https://github.com/beclab/bfl/pull/132
none
=> fix(bfl): migrate from deprecated form3tech-oss/jwt-go to golang-jwt

framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- Background
POST/PATCH/DELETE /api/resources will 400 when response is empty. This PR fixed this bug.
1.12.1
none
https://github.com/beclab/files/pull/84
none
=> fix: files /api/resources empty response bug

framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml, framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml, framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml, framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml, platform/tapr/.olares/config/cluster/deploy/middleware_deploy.yaml
- multi event were published under pressure
- citus, reverse proxy,notification priority set to system-cluster-critical
1.12
None
https://github.com/beclab/tapr/pull/71
https://github.com/beclab/bfl/pull/134
https://github.com/beclab/app-service/pull/307
=> app-service,bfl,tapr: fix multi event send; set reverse proxy,citus,notificaton priority

framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- Background
fix a bug of smb_history apis involved by req and resp format
1.12.1
none
https://github.com/beclab/files/pull/93
none
=> fix: files smb_history req and resp bugfix

framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- third party app may be suspend due to system high load, that may cause some bad case.
1.12
None
None
=> fix: disable suspend app feature when system high load

cli/pkg/bootstrap/os/tasks.go, cli/pkg/bootstrap/patch/tasks.go, cli/pkg/common/common.go, cli/pkg/core/connector/system.go, cli/pkg/utils/apt.go
Adjust certain tasks to support Debian 13's change on: 1.removal of `software-properties-common` package 2. `ntpdate` package
Remove support for no-longer supported distros: 1. Debian 11 2. Ubuntu 20.04 as the new containerd binary cannot run on the old glibc embedded in these two distros. 
v1.12.1, v1.12.2
none
none
none
=> feat(cli): support installation on Debian 13 and remove no longer supported distros

framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- Background
fix a bug of drive pdf preview leads to downloading
fix svg preview
fix /api/mount response without data field for choosing path
add avif and heic support in sync
1.12.1
none
https://github.com/beclab/files/pull/94
https://github.com/beclab/files/pull/95
https://github.com/beclab/files/pull/96
https://github.com/beclab/files/pull/97
https://github.com/beclab/files/pull/98
none
=> fix: files image and pdf preview, and /api/mount response for choosing path

framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml, framework/system-server/.olares/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
When the request from the client is authorized with the public policy by Authelia, the request doesn't have any token, neither the user token nor the service account token, it will not be allowed by the RBAC proxy. 
The new solution in this PR, when Authelia authorized the request, will add a nonce which generated by RBAC proxy to the request header, and the RBAC proxy will authenticate this nonce.
v1.12.1 v1.12.2
The request hits the public policy is still responsing the forbidden code.
https://github.com/beclab/system-server/pull/13
https://github.com/beclab/authelia/pull/38
=> authelia, systemserver: authenticate the request with public policy in rbac proxy

platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- user can also refresh token after reset password, that's bad
1.12.1
None
https://github.com/beclab/lldap/pull/23
=> lldap: invalidate refresh token after reset password

framework/chart-repo/.olares/config/cluster/deploy/chart_repo_deploy.yaml, framework/market/.olares/config/cluster/deploy/market_deploy.yaml
For chart packages submitted by users and automatically generated by Studio, even if the fields are legal, rendering may fail or some field contents may not be structured using JSON. This may cause a deadlock-like phenomenon. This modification is to prevent this from happening and avoid market freezing.
1.12.1
https://github.com/beclab/dynamic-chart-repository/commit/ea4b4ba5a7b097c85959e3605728bc1270619fc3
https://github.com/beclab/market/commit/d29e010d464881100c08d0402c07a47aaab1c028
=> fix:Market defending against abnormal data

framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- v2 uninstall all does not wait ns to be deleted that's may cause second install failed 
- helm uninstall launcher to delete pv
v1.12.1
None
https://github.com/beclab/app-service/pull/313
https://github.com/beclab/app-service/pull/312
=> app-serivce: fix v2 uninstall all wait ns be deleted

cli/pkg/core/connector/system.go, cli/pkg/gpu/tasks.go
Support installing Olares on Ubuntu 25.04
The deprecated [apt-key(8)](https://manpages.debian.org/testing/apt/apt-key.8.en.html) utility has been removed in Ubuntu 25.04 and the import of libnvidia-container's gpgkey is changed to the new method and path as suggested in [Installing the NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
1.12.2
none
none
none
=> feat: support installation on Ubuntu 25.04

framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml, infrastructure/gpu/.olares/config/gpu/hami/values.yaml, platform/hami/.olares/Olares.yaml
A new field `podGpuConsumePolicy` is added into application's OlaresManifest.yaml, and if declared, the corresponding label gpu.bytetrade.io/app-pod-consume-policy will be injected to the app pod's labels, enabling a single pod of the app to consume all GPUs bound to it, or multiple replicas of the app to each consume a seperate bound GPU.
1.12.2
none
https://github.com/beclab/app-service/pull/320
none
=> feat(app-service): support declaration of GPU consume policy in app manifest

cli/pkg/terminus/ossystem.go, daemon/pkg/commands/upgrade/check.go
Olares is shipped with dozens of CRDs, and they are applied to the kube-apiserver in a batch request, along with other components. Although the request may succeed immediately, but the actual registration and serving of the new CRD kinds is asynchronous from the API handler, typically this only takes a short period of time, less than a second, but when programmatically applying CRs right after applying CRDs, combined with a relatively slow machine, a race condition can occur and cause the CRs to be rejected by the kube-apiserver.
1.12.2
none
none
none
=> fix(cli): add retry with delay before applying CR of new kind

framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
If the entrance policy is set to internal, the requests from the cluster pods should get the bypass policy as an internal requests
v1.12.2
none
https://github.com/beclab/authelia/pull/42
=> authelia: mark request from cluster pods as internal
