beclab/Olares

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
> feat: add API to retrieve the default reverse proxy config

- build/installer/install.sh
> fix: update CLI version to 0.1.55

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
> feat: release vault and settings new version

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Bug fix: fix the theme following system
> fix: theme switch

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Bug fix: fix the theme following system
> fix: theme switch 1.10

- build/installer/install.sh
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Bug fix
fix: add rootPath for helm values
> fix: add rootPath for helm values

- README.md
> docs: add a rebranding note in readme to clear confusion

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
feature
feat: add custom cpu/memory threshold for suspend app
> feat: add custom cpu/memory threshold for suspend app

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
feature
feat: image-service add support for http mirror
> feat: image-service add support for http mirror

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
> fix: update v1.2.62 for larePass

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
> fix: fix controlHub terminal link

- build/installer/install.sh
> fix: make systemd always restart redis

- build/installer/install.ps1
- build/installer/install.sh
> fix: add truncate option for different type of logs

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
> fix: preload font 1.10

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
fix: add an ip service provider
> fix: add an ip service provider

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
fix: closed channel causes panic
> fix: closed channel causes panic

- build/installer/install.sh
feature
a new environment variable named `LOCAL_RELEASE` is added to `install.sh`.
developers can execute `LOCAL_RELEASE=1 bash build/installer/install.sh` in the root path of `Olares` the repository to build and install a local release of Olares.
basically it's a reimplementation of the build scripts under https://github.com/beclab/Olares/tree/main/scripts by the `olares-cli`, with the CDN uploading logics removed, for the sake of local releasing.
None
> feat: add support for install.sh to build local release of Olares

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Bug fix
fix: nvshare switch not update deployment with gpu
> fix: nvshare switch not update deployment with gpu

- build/installer/install.ps1
- build/installer/install.sh
> fix: debian add-apt-repository

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/settings/config/user/helm-charts/settings/templates/settings_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
> fix: preload font

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
> fix: update preview img for files

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
> fix: update img size when onResize

- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Bug fix
fix: change system upgrade job image pull policy
> fix: change system upgrade job image pull policy

- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
Bug fix
fix: nats auth error after upgrade
> fix: nats auth error after upgrade

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
market-backend update:
no local db & cache api data
> feat: market-backend no local db & cache api data

- README.md
- README_CN.md
> docs: update platform support info

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
> fix: Larepass v1.2.67

- apps/files/config/cluster/deploy/files_deploy.yaml
fix: 
- files: external 404 when it is null fixed
> fix: external 404 when it is null fixed

- build/installer/install.ps1
- build/installer/install.sh
Bug fix
get a default local IP address by the network interface connected to the default gateway
> fix: get local IP by the default route

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
> feat: s3, dropbox async download and upload task

- build/installer/install.sh
feature
show progress info for every item when downloading files and preloading images
> feat: show progress info when downloading & importing

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Bug fix
fix: bfl ingress support http2
> fix: bfl ingress http2

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
> fix: settings nginx conf bug

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
> fix: Update learpass to v1.2.69

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix: update settings nginx gzip
> fix: update settings nginx gzip

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Bug fix
fix: bfl ingress add application/x-mpegURL gzip types
> fix: bfl ingress add application/x-mpegURL gzip types

- .github/workflows/build-redis-231.yaml
- scripts/build-redis.sh
ci: build redis for glibc_2.31
> ci: build redis for glibc_2.31

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
feature
feat: inject runasuser equal 1000 for third party app's pod
> feat: inject runasuser equal 1000 for third party app's pod

- apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
- [ X] The commit message follows our guidelines
- [ X] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / features)
feature
When users activate the wizard, they will encounter an option to enable reverse proxy.
Remove the need for users to make a selection themselves.
No
> feat: During the wizard process, skip the step of choosing whether to enable reverse proxy.

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
* feat: add host address management and fix version bug by @icebergtsn in https://github.com/beclab/settings/pull/62
* style: update class name by @icebergtsn in https://github.com/beclab/settings/pull/63
* fix: ci by @icebergtsn in https://github.com/beclab/settings/pull/64
**Full Changelog**: https://github.com/beclab/settings/compare/v0.1.94...v0.1.95
> chore: settings v0.1.95 add host address management

- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Bug fix
fix: ignore system frontend
> fix: ignore system frontend

- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
feature
feat: upgrade app-service upgrade job
> feat: upgrade app-service upgrade job

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/search3/config/cluster/deploy/search3_server_deploy.yaml
> fix: wise video audio search missing

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
> fix: revert runasuser

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
> feat: add control-hub middleware

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
> feat: add control-hub middleware 1.10

- build/installer/install.ps1
- build/installer/install.sh
multiple patches of installer is cherry picked from the main branch onto release-0.1.74
v1.10.5
none
https://github.com/beclab/Installer/pull/72
https://github.com/beclab/Installer/pull/71
none
> installer: cherry picked multiple patches

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
failed to get metric values in some situation
v1.10,v1.11
None
https://github.com/beclab/app-service/pull/116
None
> app-service: fix get metric values error in some situation

- .github/workflows/release-daily.yaml
- .github/workflows/release.yaml
- apps/system-apps/config/cluster/deploy/ks_server_deploy.yaml
remove unused api and related logic from monitoring-server
v1.11
none
https://github.com/beclab/system-apps/pull/5
none
> refactor(monitoring-server-deployment): remove unused apis

- apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Wizard & LarePass check dns error
v0.5.12
None
> fix: wizard approve dns check

- apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
Wizard & LarePass check dns error
v.1.11.0 v1.12.0
None
https://github.com/beclab/wizard/pull/15
> wizard: approve dns check

- README.md
- README_CN.md
> docs: update Ubuntu support version

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
In the v0.3.0 update, the market introduced support for retrieving application information using version numbers. However, one API endpoint was overlooked, which may lead to inconsistencies in application information across different pages.
This commit upgrades the market version to v0.3.2 and fixes inconsistencies in the information.
https://github.com/beclab/market/pull/57
https://github.com/beclab/market/pull/59
https://github.com/beclab/market/pull/60
> market: fix app info inconsistency

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Title: setting, profile
Extract and replace common components and fix some UI bugs.
1.11 1.12
None
https://github.com/beclab/settings/pull/69
https://github.com/beclab/settings/pull/68
> setting, profile: replace common component and fix ui details

- README_CN.md
> docs: fix video link in readme

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
optimize dashboard and controlhub styling
none
https://github.com/beclab/system-apps/pull/7
none
> style(dashboard&controlhub): optimize dashboard and controlhub styling

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
Optimize Login and Desktop ui
none
https://github.com/beclab/login/releases/tag/v0.1.34
https://github.com/beclab/desktop/releases/tag/v0.2.46
none
> style(login&desktop): optimize Login and Desktop ui

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
upgrade larepass version to v1.3.6
fixed some ui issues
https://github.com/beclab/TermiPass/releases/tag/v1.3.6
none
> files/vault/wise: upgrade larepass version to v1.3.6

- build/installer/install.ps1
- build/installer/install.sh
Title: installer:  get cuda version
app-service needs to inject CUDA_VERSION
1.11.0 1.12+
> installer: feat get cuda version

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Title: tapr, system-fronted, knowledge:  websocket proxy
Knowledge WebSocket proxy migrated to system-fronted
1.11 1.12+
> tapr, knowledge, system-fronted: fix adjust knowledge websocket proxy

- build/installer/deploy/device-plugin.yaml
- build/installer/deploy/scheduler.yaml
Sometimes restarting `Nvshare`, some nvshare mounting files will conflict with the directories on the host.
1.11.0 1.12.0
Nvshare restarting failed
none
> olares: fix nvshare files be conflicting with dir

- build/installer/deploy/scheduler.yaml
Typo in nvshare scheduler daemonset yaml
1.11.0 1.12.0
nvshare daemonset yaml bug
none
> olares: typo in nvshare scheduler yaml

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Title: wise, vault, file
fix: fixed team bugs in vaults and operate defaultPath error in files
refactor: Optimize the loading speed of the article detail page and the loading states of some buttons in wise
1.11 1.12
None
https://github.com/beclab/TermiPass/pull/287
https://github.com/beclab/TermiPass/pull/286
> wise, vault, file: Optimize the loading speed of the reading detail page.

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Title: wise, vault, file
vault: delete padding in files ListingItem.
files: disable check item in files home and transfer add retry.
wise: fixed inbox loading state initialization issue and prevented multiple calls of hover state.
1.11 1.12
None
https://github.com/beclab/TermiPass/pull/289
https://github.com/beclab/TermiPass/pull/292
https://github.com/beclab/TermiPass/pull/293
> wise, vault, file: fix some ui bugs

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
update controlhub ui
update dashboard ui
fix dashboard avatar
fix settings ui bug
none
https://github.com/beclab/system-apps/pull/8
https://github.com/beclab/settings/pull/70
none
> fix(system-frontend): fix app bugs and update some ui

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
update controlhub ui
update dashboard ui
fix dashboard avatar
fix settings ui bug
none
https://github.com/beclab/system-apps/pull/8
https://github.com/beclab/settings/pull/70
none
> fix(system-frontend): fix app bugs and update some ui 1.11

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Title:  aboveos/knowledge, beclab/r4:  recommend optimization
This optimization is mainly about optimizing the sorting in recommendations, including fixing some bugs, and the traceability of recommendations, the following is important change. 
1. The scores of recommended articles cached by the knowledge service may come from the scores of models in different periods, identified by score_rank_time, and then cache the latest same Time-scored articles 
2. Use the long-term and short-term distance scores between the article and the user, as well as the score of the publication time. These scores are weighted to obtain the final score of the article 
3. Record some important information between rank moments to judge the quality of the article score, thereby affecting the …
> feat: recommend optimization

- frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
want to visit some service through tailscale
1.12
None
https://github.com/beclab/app-service/pull/122
> app-service: add tailscale acls support for OlaresManifest.yaml

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
adds the functionality to upload files to Olares and generate corresponding entries in Wise.
v1.12.0
None
https://github.com/beclab/TermiPass/releases/tag/v1.3.11
None
> wise: updates upload and download functionality

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
support filter view
fix custom folder bug in download
v1.12.0
Related Issues
none
none
none
> knowledge and download: add filter and fix download bugs

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix dashboard analytics multiple entrances bug
controlhub ui
none
https://github.com/beclab/system-apps/pull/10
none
> fix: fix dashboard analytics multiple entrances and controlhub ui

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix dashboard analytics multiple entrances bug
controlhub ui
none
https://github.com/beclab/system-apps/pull/10
none
> fix(controlhub&dashboard): fix dashboard analytics multiple entrances and controlhub ui

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Background
fix database migration bug
fix wise nginx configuration bug
v1.12.0
Related Issues
none
none
none
> wise: fix nginx configuration and database migration bugs

- build/installer/deploy/device-plugin.yaml
- build/installer/deploy/nvidia-device-plugin.yml
- build/installer/deploy/scheduler.yaml
- build/installer/install.ps1
- build/installer/install.sh
install GPU driver & plugin by default, if the machine has a GPU
v1.11.1 v1.12.0
none
https://github.com/beclab/Installer/pull/90
none
> feat(installer): add gpu commands

- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
Activation failed when customizing a domain name for the user
v1.11.x v1.12.x
none
none
> fix(vault-server):  vault-server when customizing domain names

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
fix some bugs in Files
fix some bugs in Vaults
Files add notification
v1.12.0
none
https://github.com/beclab/TermiPass/pull/305
https://github.com/beclab/TermiPass/pull/300
https://github.com/beclab/TermiPass/pull/307
https://github.com/beclab/TermiPass/pull/308
> feat(Files&Vault&Wise&Files server): update LarePass  new version to v1.3.14

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
refactor: added secondary prompts for standardized installation pre-checks 
feat: added dependency checking mechanism 
feat: added a dialog prompt for missing installation dependencies 
feat: added a dialog prompt for missing referenced apps
fix: fixed several known bugs
fix: multi app creation may failed
1.12
None
https://github.com/beclab/market/releases/tag/v0.3.3
https://github.com/beclab/bfl/pull/62
https://github.com/beclab/Olares/pull/125
None
> market, bfl, app-service: added dependency checking mechanism and fixed some bugs

- build/installer/install.ps1
Get the current user's home directory in Windows
1.11
> fix(installer): windows user home path

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
fix some bugs in Files
fix some bugs in Vaults
feat: files server send message to frontend with nats when directory changed
v1.11.0
none
https://github.com/beclab/TermiPass/pull/305
https://github.com/beclab/TermiPass/pull/300
https://github.com/beclab/TermiPass/pull/307
https://github.com/beclab/TermiPass/pull/308
> feat(Files&Vault&Wise&Files server): update LarePass new version to v1.3.14

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix some bugs and update the version to be consistent with olares 1.11
1.12
None
https://github.com/beclab/TermiPass/releases/tag/v1.3.16
None
> wise: fix some bugs and update the version to be consistent with olares 1.11

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
> Revert "feat(Files&Vault&Wise&Files server): update LarePass new version to v1.3.14"

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
add the necessary ports and set up Tailscale ACLs for secure access. 
1.12
None
https://github.com/beclab/settings/releases/tag/v0.2.5
https://github.com/beclab/bfl/pull/61
https://github.com/beclab/bfl/pull/63
https://github.com/beclab/app-service/pull/130
https://github.com/beclab/app-service/pull/131
> bfl, settings, app-service: add ports and tailscale acl

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix space refresh token error
1.11
None
https://github.com/beclab/settings/releases/tag/v0.2.4
None
> settings: fix space refresh token error

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix bytetrade-ui btn style
1.11
None
https://github.com/beclab/settings/releases/tag/v0.2.9
None
> settings: fix bytetrade-ui btn style

- README.md
- README_CN.md
- README_JP.md
> docs: update the latest arch diagram

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- inject NVSHARE-DEUBG env for gpu application's container
1.12
None
https://github.com/beclab/app-service/pull/133
None
> app-serivce: inject nvshare-debug env

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
some tasks are skipped or modified for the installer to run in a container.
v1.12.0
none
https://github.com/beclab/Installer/pull/132
none
> fix(installer): modified some commands to compatible running In the container

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
fix: fix external bug and ci add upload-frontend-files-11
v1.11.0
none
https://github.com/beclab/TermiPass/releases/tag/v1.3.19
https://github.com/beclab/settings/releases/tag/v0.2.10
https://github.com/beclab/market/releases/tag/v0.3.4
none
> files&settings&market&files server: update version larepass to v1.3.19

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
Background
fix http error 403 on youtube download
v1.12.0
Related Issues
none
none
none
> download: update yt-dlp download version to v0.0.19

- scripts/build-wsl-install-msi.sh
upload wsl2 installation package to s3, these files will be used for the offline installation or update of wsl2.
> ci: upload wsl2 installation package

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
fix: files immediately send events for remove/rename and folder create
fix: fix files uplaodModal count err and filter md5
v1.12.0
none
https://github.com/beclab/TermiPass/pull/323
none
> files&files server: update larepass version to v1.3.20

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fixed pod status sync after deleted replicas
v1.11.0
none
https://github.com/beclab/system-apps/pull/11
* none
> fix(control-hub): fix pod status sync after delete replicas

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
add youtube playlist feed
fix http error 403 on youtube download
v1.11
Related Issues
none
none
none
> knowledge&download: update yt-dlp to v0.0.19 and knowledge to v0.1.61

- scripts/build-wsl-install-msi.sh
fix the upload wsl.msi script
main
> ci: build wsl-msi script fix

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
add youtube playlist feed
v1.12.0
Related Issues
none
none
none
> knowledge: update version to v0.1.61

- third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Title:  tailscale :  env
After headscale changes the database, tailscale reconnects
> fix: let tailscale follow headscale restart

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
- third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
files: nginx increase worker and timeout, and pasting temp file invisiable
fix create new folder in sync and update axios timeout to 30min
v1.12.0
none
https://github.com/beclab/TermiPass/pull/328
none
> files&files server: updage LarePass version to v1.3.24

- build/installer/install.ps1
- build/installer/install.sh
fix: Optimize the prompt message for selecting the distro install location during WSL installation. 
fix: setup host ip as nat gateway ip for oic
1.12
https://github.com/beclab/Installer/pull/138
https://github.com/beclab/Installer/pull/140
> fix(installer): prompt for the installation location and setup host ip as nat gateway ip for oic

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
uploader: (v1.0.9) make uploading big file invisible at final stage (make it same as files-server pasting does)
files: nginx worker change to auto, increase nginx and envoy timeout
seafile: increase nginx timeout to make it match files
files: notify each operation when pasting
v1.11.0
none
https://github.com/beclab/TermiPass/pull/329
> files&files server: update LarePass version to v1.3.25

- frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
add acl rules to application crd
v1.11.3
tailscale acl not work
> app-service: add acl rules to application crd

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
fix: delete notify id in notifyHide
v1.12.0
none
https://github.com/beclab/TermiPass/pull/330
> files: delete notify id in notifyHide

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- change user space network policy for ipblock
1.12
None
https://github.com/beclab/app-service/pull/140
> app-service: change user space network policy for ipblock

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive:fix most dropbox, google drive problem
import changes
1. fix most dropbox, google drive problem, make them usable
2. support direct download from google drive, dropbox
3. support direct upload to google drive, dropbox
4. support google style document download
daily build
https://github.com/Above-Os/drive/pull/83
https://github.com/Above-Os/drive/pull/82
https://github.com/Above-Os/drive/pull/81
https://github.com/Above-Os/drive/pull/80
https://github.com/Above-Os/drive/pull/79
https://github.com/Above-Os/drive/pull/78
https://github.com/Above-Os/drive/pull/77
https://github.com/Above-Os/drive/pull/76
https://github.com/Above-Os/drive/pull/75 …
> feat: fix knowen dropbox, googledrive problem

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
fix resource cache in safari browser
fix ui bug in pad
v1.11.0
none
https://github.com/beclab/desktop/pull/64
none
> fix(desktop): fix resource cache in safari browser and some ui bug

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
fix resource cache in safari browser
fix ui bug in pad
v1.12.0
none
https://github.com/beclab/desktop/pull/64
none
> fix(desktop): fix: fix resource cache in safari browser and some ui bug

- third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
the login content cannot display content on Safari browser
v1.12.0
none
https://github.com/beclab/login/pull/23
none
> login: display login content on Safari browser

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: deal with special characters in dir/file name for drive/cache/sync (except "/" in dir/file name)
uploader: fix uploading progress lost problem at restarting, and make uploadstemp dir also invisible for drive
feat: update client download to c++
fix: some LarePass platform bugs
v1.12.0
none
https://github.com/beclab/TermiPass/pull/337
https://github.com/beclab/TermiPass/pull/338
https://github.com/beclab/TermiPass/pull/339
https://github.com/beclab/TermiPass/pull/340
none
> larePass&files&files server: update LarePass version to v1.3.29

- build/installer/install.ps1
- build/installer/install.sh
Add more log information when an error occurs while install the WSL Distro
1.11
https://github.com/beclab/Installer/pull/147
https://github.com/beclab/Installer/pull/148
> fix(installer): improve log information for create distro in wsl

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: a bug of pasting to sync with special characters, and add a msg to block it when there are backslashes in dst
fix: prompt message when a backslash appears in sync
fix: open txt in drive
fix: preview images in TIFF format
fix: some clients bug
v1.11.0
none
https://github.com/beclab/TermiPass/pull/341
https://github.com/beclab/TermiPass/pull/342
none
> larepass&files&files server: update LarePass version to v1.3.30 

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: a bug of pasting to sync with special characters, and add a msg to block it when there are backslashes in dst
fix: prompt message when a backslash appears in sync
fix: open txt in drive
fix: preview images in TIFF format
fix: some clients bug
v1.12.0
none
https://github.com/beclab/TermiPass/pull/341
https://github.com/beclab/TermiPass/pull/342
none
> larepass&files&files server: update LarePass version to v1.3.30

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: fix bug of sync recursive pasting with eacape
fix: block slashes when creating/renaming and update notify msg
v1.11.0
none
https://github.com/beclab/TermiPass/pull/343
https://github.com/beclab/files/pull/2
none
> larepass&files&files server: update LarePass version to v1.3.31

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
add save zhihu page
add save substack page
add save twitter page
add twitter download
v1.12.0
Related Issues
none
none
none
> download&backend server: update download-spider to v0.0.17, backend to v0.0.26

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Choose the nearest CDN server in the upgrade job
v1.11.5
Failed to download the upgrade package
https://github.com/beclab/app-service/pull/145
> app-service: choose the nearest cdn server in the upgrade job

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- Choose the nearest CDN server in the upgrade job
- Change kubephsere kubectl image tag
1.12
None
https://github.com/beclab/app-service/pull/145
https://github.com/beclab/kubesphere-ext/pull/5
> app-service,kubesphere: get best cnd server in upgrade job; change kubectl image tag

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/rss/config/cluster/deploy/rss_deploy.yaml
Background
add bilibil collection feed
add filter fields
fix twitter download bug
v1.12.0
Related Issues
none
none
none
> download&download: update knowledge to v0.1.62, yt-dlp to v0.0.20

- build/installer/wizard/config/settings/templates/system-serviceaccount.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
- fix auth token validate
1.12
None
https://github.com/beclab/system-server/pull/8
https://github.com/beclab/tapr/pull/36
> tapr, system-server: fix auth token validate

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/rss/config/cluster/deploy/rss_deploy.yaml
Background
add twitter feed
fix twitter download bug
v1.12.0
Related Issues
none
none
none
> knowledge: update knowledge to v0.1.63

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3, beclab/desktop:  search3 optimization
1.reduce time for search: keep only websearch; only return top 50 rank;
2. merge the same file or doc when title or content contain keyword
main
https://github.com/Above-Os/search3/pull/47
https://github.com/Above-Os/search3/pull/46
https://github.com/Above-Os/search3/pull/45
https://github.com/Above-Os/search3/pull/44
https://github.com/Above-Os/search3/pull/43
https://github.com/Above-Os/search3/pull/42
> feat: optimization search3

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- apps/search3/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3, beclab/desktop:  search3 optimization
1.reduce time for search: keep only websearch; only return top 50 rank;
2. merge the same file or doc when title or content contain keyword
main
https://github.com/Above-Os/search3/pull/47
https://github.com/Above-Os/search3/pull/46
https://github.com/Above-Os/search3/pull/45
https://github.com/Above-Os/search3/pull/44
https://github.com/Above-Os/search3/pull/43
https://github.com/Above-Os/search3/pull/42
> feat: search3 optimization

- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
- create stream return nil value
1.12
None
https://github.com/beclab/tapr/pull/37
> tapr: fix create stream return nil value

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
update highlight txt in search
v1.12.0
none
https://github.com/beclab/desktop/pull/68
none
> desktop: update highlight txt in search

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
add support for google drive and dropbox, including list (& stream list), copy/move, create, rename, delete
add preview cache for all drives
v1.12.0
none
https://github.com/beclab/files/pull/3
https://github.com/beclab/TermiPass/pull/353
none
> files&files server: add support for google drive and dropbox

- README.md
- README_CN.md
- README_JP.md
> docs: fix bad link in readme

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- build/manifest/images
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- custom allowed outbound port
- tcp udp port can use same port
- add idle time to original_dst cluster
1.11
https://github.com/beclab/app-service/pull/150
https://github.com/beclab/app-service/pull/152
https://github.com/beclab/app-service/pull/154
> app-service: custom allowed outbound port;tcp udp port

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
update desktop dock logic
add landscape mode for mobile devices
remove the background when dragging app icons in Chrome
refactor login code
v1.12.0
none
https://github.com/beclab/desktop/pull/71
https://github.com/beclab/desktop/pull/72
https://github.com/beclab/login/pull/24
none
> login&desktop: update desktop dock logic and optimize mobile device

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
add twitter article extract
modify filter interface
v1.12.0
Related Issues
none
none
none
> knowledge&download: update knowledge to v0.1.64, download-spider to v0.0.19

- build/manifest/components
download and push the restic tool to s3
1.12
> ci: build restic

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- fix envoy outbound port
1.11
None
https://github.com/beclab/app-service/pull/155
> app-service: fix envoy outbound port

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
Increase ingress client body buffer size to improve the file uploading speed
v1.11.5
none
https://github.com/beclab/bfl/pull/77
> fix: increase ingress client body buffer size

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
add a node terminal tool
v1.11.0
none
https://github.com/beclab/system-apps/pull/14
https://github.com/beclab/kubesphere-ext/pull/8
none
> feat(control-hub): add node terminal

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
fix samsung devices cannot landscape
v1.12.0
none
https://github.com/beclab/desktop/pull/76
none
> fix: update @bytetrade/core to 0.2.53

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
fix samsung devices cannot landscape
v1.11.0
none
https://github.com/beclab/desktop/pull/76
none
> fix: update @bytetrade/core to v0.3.76

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
add a node terminal tool
v1.12.0
none
https://github.com/beclab/system-apps/pull/14
https://github.com/beclab/kubesphere-ext/pull/8
none
> feat(control-hub & ks): add node terminal

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- third-party/seahub/config/cluster/deploy/seafile_deploy.yaml
fix:
seafile: remove recv file log for uploading more stable
files-frontend: upload request auto retry error
1.12
None
https://github.com/beclab/TermiPass/pull/365
https://github.com/beclab/TermiPass/pull/364
> files: update files new version to 1.3.39

- build/installer/upgrade_cmd.sh
System upgrade checking is earlier than helm upgrading
v1.11.5
System upgrade status checking not working
none
> olares: fix system upgrade status checking bug

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
Desktop: launch display different icons on different devices
v1.11.0
none
https://github.com/beclab/desktop/pull/77
none
> desktop: launch display different icons on different devices

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
**Background**
wise: add reading progress function and fix some ui bugs
knowledge: fix filter bug
1.12
None
https://github.com/beclab/TermiPass/pull/366
https://github.com/beclab/TermiPass/pull/367
None
> wise, knowledge: add reading progress function and fix some bugs

- build/installer/wizard/config/account/templates/account.yaml
- special leading char cause helm render error
1.12
None
None
> olares: fix special leading char cause helm render error

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix control-hub multiple terminal path conflicts
v1.11
none
https://github.com/beclab/system-apps/pull/15
none
> control-hub: fix terminal route path conflict

- apps/files/config/cluster/deploy/files_deploy.yaml
- Background
files: files-server project structure reconstruction
1.12
None
https://github.com/beclab/files/pull/7
> style: files-server project structure reconstruction

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Reconnect the socket if it is not connected after returning to the application, and reinitialize the data after the connection is successfully established.
1.11
None
https://github.com/beclab/market/pull/66
None
> market: reconnect socket and reinitialize data on app return

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files open Google Drive and Dropbox
1.12.0
None
None
* None
> feat(files): update files support google drive & dropbox

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
Title: aboveos/drive:  add id route for info,  fix file size limit
1. direct transmission allows retransmission of previous blocks2. Replace i32 with i64, remove upload filesize limit
2.  relase memtory in different thread
3.  modify error tips for easily undersand
release-1.11
https://github.com/Above-Os/drive/pull/90
https://github.com/Above-Os/drive/pull/91
https://github.com/Above-Os/drive/pull/92
https://github.com/Above-Os/drive/pull/93
https://github.com/Above-Os/drive/pull/94
> fix: google dropbox optimization 

- build/manifest/images
- update ks image tag
- 
1.12
None
None
> fix: change ks image tag

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
request data again when socket err or network offline
v1.12.0
none
https://github.com/beclab/desktop/pull/78
none
> desktop: request data when socket err or network offline

- build/manifest/images
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
optimize L4 proxy gateway performance:
1. Change nginx to openresty to optimize lua performance and memory usage
2. Optimize the lua script, reduce the json decode times
L4-bfl-proxy high memory usage
https://github.com/beclab/l4-bfl-proxy/pull/2
> l4-bfl-proxy: optimize l4 proxy gateway performance

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
The application entry details page needs to add a detailed url
Application websocket needs to be kept alive
1.12.0
None
https://github.com/beclab/settings/pull/90
https://github.com/beclab/settings/pull/88
None
> feat(settings): add entrance endpoint url & fix WebSocket keep-alive

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- revert hostpath chown 1000
- remove handle model code
1.11
None
http://ubugithub.com/beclab/app-service/pull/162
https://github.com/beclab/app-service/pull/161
> app-service: revert hostpath chown 1000;remove handle model code

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
add xhs article extract
add quora article extract
fix bluesky extract bugs
fix  opml feeds import bug
v1.12.0
Related Issues
none
none
none
> knowledge&download: update knowledge to v0.1.66, download-spider to v0.0.20

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
file: fixed the issue with resumablejs.js retrying to upload from 0 Merge duplicate upload tasks
wise: added new query conditions and quick add functionality for tags/feeds to the filter view
1.12
None
https://github.com/beclab/TermiPass/pull/373
https://github.com/beclab/TermiPass/pull/374
https://github.com/beclab/TermiPass/pull/376
None
> wise, file: fixed the issue with resumablejs.js retrying to upload from 0 Merge duplicate upload tasks and wise filter optimize

- apps/files/config/cluster/deploy/files_deploy.yaml
- Background
files: 
files-server project structure reconstruction v2
chown to 1000 after creating folder (including os and fs)
add GET/PUT /api/permission API and change cache gateway relatively
smb permission denied text change to more readable
1.12
None
https://github.com/beclab/files/pull/10
> feat: files permission relative

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
the official frp code does not print errors when reading & writing messages, we add some logs in such cases
1.12.0
none
https://github.com/beclab/bfl/pull/83
none
> feat(frp): add error logs

- build/installer/upgrade_cmd.sh
Background
Sometimes when the system upgrade has been finished, some apps are not ready yet.
v1.12.0
Related Issues
none
none
> olares: add system upgrading apps checking

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- missing pod metric route
1.12
None
https://github.com/beclab/Installer/pull/177
https://github.com/beclab/kubesphere-ext/pull/11
> ks: add pod metric route

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- set upgrade job ttl to 30 days
1.12
None
https://github.com/beclab/app-service/pull/164
> app-service: set upgrade job ttl to 30 days

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
- third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
- third-party/opentelemetry/config/user/helm-charts/opentelmetry/templates/otel_define.yaml
1. fix opentelemetry auto instrumentation config
2. Fix Jaeger collector config
3. comment out auto instrumentation temporarily 
v1.12.0
none
none
> olares: fix opentelemetry instrumentation config

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- app-service: add download cdn url to helm values
1.12
None
https://github.com/beclab/app-service/pull/166
> app-service: add download cdn url to helm values

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
Files & vault unified dialog style
Files supports aws s3 cloud disk
Files fixed copy and paste shortcut key function
Files add shard md5 detection for file upload
Files add permission relative
1.12.0
None
https://github.com/beclab/TermiPass/pull/380
https://github.com/beclab/TermiPass/pull/377
https://github.com/beclab/TermiPass/pull/382
> feat(Files&Vault): update files & vault to new version to v1.3.43

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
desktop:  add intent to support open file in files
desktop: adjust docker app position when init web
login: update input style on mobile/tablet device
v1.12.0
none
https://github.com/beclab/desktop/pull/82
https://github.com/beclab/desktop/pull/81
https://github.com/beclab/desktop/pull/83
https://github.com/beclab/login/pull/27
none
> desktop&login: add intent to support open file in files

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
update the logic for saving webpage and new download
modify delete file in entries and feeds
v1.12.0
Related Issues
none
none
none
> knowledge: update knowledge to v0.1.67

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- upgrade app mission some helm values
1.11
None
https://github.com/beclab/app-service/pull/167
> app-service: fix upgrade values

- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
- frameworks/tapr/config/cluster/deploy/redixcluster_deploy.yaml
Adding a namespace to kvrocks should call `config rewrite` command to persist the configuration to config file
kvrocks namespace config need to be recreated after restart
https://github.com/beclab/tapr/pull/52
> tapr: persist kvrocks namespace config

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/app-service/config/cluster/crds/app.bytetrade.io_applications.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
The Settings project needs to add configuration sub-routes, ACL, and SSH related configurations
1.12.0
None
https://github.com/beclab/settings/pull/93
https://github.com/beclab/app-service/pull/170
https://github.com/beclab/bfl/pull/86
None
> feat(settings): update settings support vpn config

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files-frontend: 
fix some dialog bug
fix aws s3 upload path error
files-server: 
add aws s3 feature support which are left in the latest version
fix an old cut/paste bug
wise-frontend: 
feat: unified entry deletion logic and fix some bugs
1.12.0
* **Related Issues** 
None
https://github.com/beclab/TermiPass/pull/387
https://github.com/beclab/TermiPass/pull/386
None
> feat(files&wise&files-server): update files & wise new version to v1.3.44

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
add video, audio page metadata analysis
v1.12.0
Related Issues
none
none
none
> feat(knowledge): update knowledge new version to v0.1.68

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
-  nil tailscale in update application
1.12
None
https://github.com/beclab/app-service/pull/173
> app-service: fix nil tailscale in update application

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- build/manifest/images
- frameworks/tapr/config/cluster/deploy/sys_event_deploy.yaml
1. the correct cluster ip of coredns service should be injected to tailscale container for ip resolution. 
2. add privileges of configmap to component sys-event 
1.12.0
none
https://github.com/beclab/Installer/pull/182
none
> fix(installer): pass the correct coredns service ip

- apps/files/config/cluster/deploy/files_deploy.yaml
- Background
files-server: jsonify message for status 500
1.12.0
None
https://github.com/beclab/files/pull/12
None
> fix: files-server jsonify message for status 500

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
- Background
files-frontend:
fix some dialog bug
fix aws s3 upload path error
files-server:
add aws s3 feature support which are left in the latest version
fix an old cut/paste bug
wise-frontend:
feat: unified entry deletion logic and fix some bugs
drive-server:
fix latest awss3 copy repeate error and delete error
1.11.6
None
https://github.com/beclab/TermiPass/pull/387
https://github.com/beclab/TermiPass/pull/386
https://github.com/beclab/files/pull/12
https://github.com/beclab/tapr/pull/53
https://github.com/Above-Os/drive/pull/110
https://github.com/Above-Os/drive/pull/109
https://github.com/Above-Os/drive/pull/108
https://github.com/Above-Os/drive/pull/107
https://github.com/Above-Os/drive/pull/106
- Other …
> feat: update files support awss3 (including files, wise, files-server, drive-server, uploader)

- build/manifest/images
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
- frameworks/tapr/config/cluster/deploy/sys_event_deploy.yaml
- third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
1. In `only vpn` mode, check the remote address IP instead of the domain name
2. Fix dead loop bug in internal policy of the entrance
3. Missing quotes in the corefile template plugin options
v1.12.0
none
https://github.com/beclab/l4-bfl-proxy/pull/3
https://github.com/beclab/tapr/commit/2776d127c472c95b8d9a5cabbfc2b4c79d4cb982
https://github.com/beclab/authelia/pull/9
> l4-bfl-proxy, tapr, authelia: fix local domain solution bugs

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
The Settings project needs to add configuration sub-routes, ACL, and SSH related configurations。
The settings project supports custom third-party domain names.
1.11
none
https://github.com/beclab/settings/pull/94
https://github.com/beclab/settings/pull/93
none
> feat(settings): update settings support configuration sub-routes, ACL, and SSH, third-party domain

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
- merge cs chart to one make is more simple
1.12
None
https://github.com/beclab/market/commit/270ddd39340d025b27ab2c81574970daeb565f57
https://github.com/beclab/app-service/pull/174
> market,app-service: merge cs chart to one

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- fix a bug and add some log
1.12
None
https://github.com/beclab/kubesphere-ext/pull/12
https://github.com/beclab/lldap-client/pull/2
> ks: fix a bug and add some log

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
Implement unified installation package for CS architecture with enhanced prompts and pre-check optimizations.
- Combined client and server into a single installation package.
- Improved user prompts during the installation process for better clarity.
- Added/optimized pre-check mechanisms to ensure environment readiness before installation.
1.12
None
https://github.com/beclab/market/pull/68
None
> market: modify cs app to shared app

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
files-server: fix external move folder bug
files-frontend: fix google drive & dropbox & aws s3 account display error
1.11
None
(https://github.com/beclab/TermiPass/pull/388)
None
> feat(files-server & files): update files frontend & files server version

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
files-server: fix external move folder bug
files-frontend: fix google drive & dropbox & aws s3 account display error
settings-frontend: fix use default language error
1.12
None
(https://github.com/beclab/TermiPass/pull/388)
None
> feat(files-server & files & settings): update files frontend & files server version

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Refactor devbox and rename to studio
v1.12.0
none
https://github.com/beclab/system-apps/pull/21
https://github.com/beclab/system-apps/pull/20
none
> devbox&devbox server&app server: Initialize Studio

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
update the logic for saving webpage and new download
add video, audio page metadata analysis
modify delete file in entries and feeds
v1.11
Related Issues
none
none
none
> knowledge&download: update knowledge to v0.1.68, download-spider to v0.0.21

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Fix conflict app prompt.
Add app dependency state check.
Store App Store application information into the database.
1.11
None
https://github.com/beclab/market/releases/tag/v0.3.9
https://github.com/beclab/app-service/pull/183
https://github.com/beclab/app-service/pull/181
https://github.com/beclab/app-service/pull/179
None
> market, app-service: Conflict Resolution, Dependency Check, and App Store Data Integration

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- studio bug fix
1.11
None
https://github.com/beclab/devbox/pull/38
https://github.com/beclab/system-apps/commit/9e0764fa4f83108fda14ca115517d36b2d5913b3
> studio,studio-server: fix some bug

- build/installer/upgrade_cmd.sh
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
When system upgrading, some builtin app like `studio` depends on app-service upgrading,  so upgrade app-service in priority
v1.11.6
`studio` missing  when system upgrading
none
> olares: upgrade app-service in priority

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
desktop: update the display logic for delete icons in Lanchpad
v1.11.0
none
https://github.com/beclab/desktop/pull/84
none
> desktop: update the display logic for delete icons in Lanchpad

- build/installer/upgrade_cmd.sh
Fixing upgrading bugs:
1. Check app-service status bug
2. Failed to apply system version after upgrading successfully
v1.11.6
none
none
> olares: fix checking app service status bug

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
fix some bugs
v1.11.0
none
https://github.com/beclab/system-apps/pull/24
https://github.com/beclab/system-apps/pull/26
none
> studio&studio server: fix some bugs

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- build/installer/upgrade_cmd.sh
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
fix some bugs
v1.12.0
none
https://github.com/beclab/system-apps/pull/24
https://github.com/beclab/system-apps/pull/26
none
> studio&studio server&app service: fix some bugs

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
wise
fix: handling of filter query values with spaces and resolve minor UI bugs
files
fix: google drive & dropbox &awss3 bugs
1.12.0
None
https://github.com/beclab/TermiPass/pull/390
https://github.com/beclab/TermiPass/pull/389
None
> feat: update files & wise new version to v1.3.46

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
fix audio metadata bug
fix twitter file_type bug
fix twitter title bug
v1.11
Related Issues
none
none
none
> fix(knowledge): update knowledge new version to v0.1.69

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
studio: translate content
studio: optimize the scroll height style of the application
v1.11.0
none
https://github.com/beclab/system-apps/pull/27
> studio: update version to v0.2.4

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Optimized partial copywriting
1.11
None
https://github.com/beclab/TermiPass/pull/391
None
> wise: optimized partial copywriting

- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_restores.yaml
- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_snapshots.yaml
- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
backup-server code improvements, fixes include: API interface, mutex used in worker management, adjustment of CRD time fields to Time format
1.12
https://github.com/beclab/backup-server/pull/8
> backup-server: fix bugs in api and worker management

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- pull image with unpack
- del cache dir by call files
1.12
None
https://github.com/beclab/app-service/pull/197
https://github.com/beclab/app-service/pull/195
> app-service: pull image with unpack;del cache dir by call files

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Refactor the controlhub workloads to support the automatic refresh of the workloads in the studio based on the deployment and installation status of the application.
v1.12
none
https://github.com/beclab/system-apps/pull/29
none
> studio: automatically refresh the workloads

- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_restores.yaml
- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_snapshots.yaml
- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
API interface adjustment, thread pool integration, and backup and restore progress extraction optimization.
1.12
https://github.com/beclab/backup-server/pull/9
https://github.com/beclab/backup-server/pull/10
https://github.com/beclab/backup-server/pull/11
> backup-server: api adjustment, working pool integration

- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_backups.yaml
- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
list query supports pagination, working-pool supports backup and restore for multiple users.
1.12
https://github.com/beclab/backup-server/pull/12
https://github.com/beclab/backup-server/pull/13
> backup-server: query page, pool with multi users

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
1. update controlHub and studio dialog
2. fix deploy the app when the configuration is created
v1.11
none
https://github.com/beclab/system-apps/pull/33
https://github.com/beclab/system-apps/pull/31
none
> controlhub/studio: update dialog and fix studio deploy app

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/GPU/config/gpu/hami/templates/dcgm-exporter/metrics-configmap.yaml
- frameworks/GPU/config/gpu/hami/templates/dcgm-exporter/service-monitor.yaml
- frameworks/GPU/config/gpu/hami/templates/webui/hamiservicemonitor.yaml
- frameworks/GPU/config/gpu/hami/templates/webui/servicemonitor.yaml
- frameworks/GPU/config/gpu/hami/values.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
1. Fix hami gpu monitoring configuration bug
2. Make underlay namespaces can access other namespaces' network
v1.12.0
No data in hami webui
https://github.com/beclab/app-service/pull/199
> olares, app-service: fix hami gpu monitoring configuration bug

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
When the network is switched from cloudflare to frp, the interface displays an error
1.12
None
https://github.com/beclab/settings/pull/96
* None
> fix(settings): network update cloudflare to frp error

- .github/workflows/check.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
add lint check listing changed files scope, to trigger the lint checking for more scenarios
v1.12.0
none
none
> olares: add lint check listing changed files scope

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: fix download error when the list is sorted 
files: fix repo show errors in shared libraries on mobile device
v1.12.0
none
https://github.com/beclab/TermiPass/pull/401
https://github.com/beclab/TermiPass/pull/405
none
> files: update Larepass new version to v1.3.50

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
fix the query for backup total size
1.12
https://github.com/beclab/backup-server/pull/14
https://github.com/Above-Os/backups-sdk/commit/f069db1bccc09c0904bc5b4210b855f24db335bb
> backup-server: fix backup total size

- apps/argo/config/cluster/deploy/workflow-controller-config-map.yaml
- apps/knowledge/config/cluster/deploy/knowledge_deployment.yaml
- apps/knowledge/user/helm-charts/knowledge/Chart.yaml
- apps/knowledge/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
fix argo archiveLogs  error
fix knowledge service error
v1.12.0
Related Issues
none
none
none
> fix(knowledge): argo archivelogs and knowledge service error

- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_backups.yaml
- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
fix backup to local path invalid, api response data format correction
1.12
https://github.com/Above-Os/backups-sdk/pull/11
https://github.com/beclab/backup-server/pull/15
> backup-server: backup loacal path invalid, api response data format

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- build/manifest/images
- node shell add lang env
1.12
None
https://github.com/beclab/Installer/pull/195
https://github.com/beclab/kubesphere-ext/pull/14
> ks,Installer: node shell add lang env

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- app's gpu env inject bug
1.11
None
https://github.com/beclab/app-service/pull/205
> app-service: fix app's gpu env inject

- apps/knowledge/config/cluster/deploy/knowledge_deployment.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
Background
fix recommend  install and uninstall error 
v1.12.0
Related Issues
none
none
none
> fix(knowledge): recommend install and uninstall error 

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
studio: coding in olares by studio
studio: fix some bug
control hub: fix event status and update workloads header
v1.12.0
none
https://github.com/beclab/system-apps/pull/35
https://github.com/beclab/system-apps/pull/36
https://github.com/beclab/devbox/pull/40
https://github.com/beclab/devbox/pull/41
https://github.com/beclab/devbox/pull/42
https://github.com/beclab/devbox/pull/43
https://github.com/beclab/devbox/pull/46
https://github.com/beclab/devbox/pull/47
none
> studio&controlHub: coding in olares by studio

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
api interface enhancement, add new apis for querying single record
1.12
https://github.com/beclab/backup-server/pull/18
> backup-server: api interface enhancement

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
market: Update the error message when the user has insufficient resources during app preflight and menu tab when router path changed 
1.11
None
https://github.com/beclab/market/pull/71
https://github.com/beclab/market/pull/72
None
> market: Update the error message when the user has insufficient resources during app preflight

- apps/files/config/cluster/deploy/files_deploy.yaml
- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: add support mount SMB IP
v1.12.0
none
https://github.com/beclab/TermiPass/pull/410
https://github.com/beclab/TermiPass/pull/408
https://github.com/beclab/files/pull/13
none
> files&files-server: add support mount SMB IP

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
collect more logs in `olares-cli olares logs` command
1.12.0
none
https://github.com/beclab/Installer/pull/200
none
> feat(installer): collect more logs

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
fix knowledge feed edit bug
fix knowledge lavel save bug
1.11
Related Issues
none
none
none
> fix: fix knowledge feed edit and label save bug

- apps/knowledge/config/cluster/deploy/knowledge_deployment.yaml
Background
fix knowledge feed edit bug
fix knowledge lavel save bug
fix download task remove bug
1.12
Related Issues
none
none
none
> fix: knowledge feed edit and label save bug

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- frameworks/backup-server/config/cluster/crds/sys.bytetrade.io_backups.yaml
- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
backup-server add notification, improve api interface
1.12
https://github.com/beclab/backup-server/pull/20
https://github.com/Above-Os/backups-sdk/pull/17
> backup-server: add notification, improve api interface

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- studio server envoy timeout when uninstall long
1.12
None
None
> fix: add studio server envoy timeout

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
lldap usergroup sync, backup progress notification block
1.12+
https://github.com/beclab/kubesphere-ext/pull/16
https://github.com/beclab/kubesphere-ext/pull/17
https://github.com/Above-Os/backups-sdk/pull/18
> fix: lldap usergroup sync, backup notify improve

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
fix progress notification blocked, terminal execution with -v flag error,add backup traceId
1.11.7
https://github.com/Above-Os/backups-sdk/pull/18
> fix: backup notify improve

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
snapshot progress notification blocking causing status abnormality, backup process improvement
1.12+
https://github.com/Above-Os/backups-sdk/pull/18
https://github.com/beclab/backup-server/pull/21
> backup-server: snapshot progress notification blocking

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- apps/vault/config/cluster/deploy/vault_server_deploy.yaml
- apps/vault/config/user/helm-charts/vault/templates/vault_deploy.yaml
files: notify message when user cancels upload
files: jump to home page when delete repo in sync drive
v1.12.0
none
https://github.com/beclab/TermiPass/pull/411
none
> files: notify message when user cancels upload

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Settings support backup files to AWS S3, Tencent Cloud, Olares Space, and local File.
1.12
None
https://github.com/beclab/TermiPass/pull/412
None
> settings: update settings backup function

- frameworks/tapr/config/cluster/deploy/middleware_deploy.yaml
Migrate Kvrocks statefulset configuration to persist the kvrocks config file
v1.11.7
none
https://github.com/beclab/tapr/pull/57
> tapr: migrate kvrocks statefulset configuration

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
studio: create files err in application page
v1.11.0
none
https://github.com/beclab/system-apps/pull/39
none
> fix: create files err in application page

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
studio: create files err in application page
v1.12.0
none
https://github.com/beclab/system-apps/pull/39
none
> studio: create files err in application page

- third-party/headscale/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Title: tailscale :  tun
olares Administrator user's VPN uses the TUN interface.
v1.12.0
> feat: Tailscale for admin user uses tun interface

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
desktop: iframe hide or cannot move when zooming the window
v1.12.0
none
https://github.com/beclab/desktop/pull/85
none
> desktop: fix iframe hide when zooming the window

- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
fix knowledge impression bug
1.12
Related Issues
none
none
none
> fix: knowledge impression bug

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- underlayer namespace network policy
1.11
None
https://github.com/beclab/app-service/pull/214
https://github.com/beclab/app-service/pull/213
> app-service: fix underlayer ns netpol

- apps/market/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
**Background**
Set the default theme color to light when the user has not selected a theme color.
1.11
None
https://github.com/beclab/market/pull/74
None
> profile, market: modify default theme configuration

- apps/argo/config/cluster/deploy/server-deployment.yaml
- apps/argo/config/cluster/deploy/workflow-controller-config-map.yaml
- apps/argo/config/cluster/deploy/workflow-controller-deployment.yaml
- apps/knowledge/config/cluster/deploy/knowledge_deployment.yaml
Background
fix argo archivelog bug
fix knowledge feed save bug
1.12
Related Issues
none
none
none
> fix: argo archivelog and knowledge feed save bug

- apps/studio/config/user/helm-charts/studio/templates/deployment.yaml
- change cm push url
1.11
None
https://github.com/beclab/devbox/pull/48
> studio-server: change cm push url

- apps/argo/config/cluster/deploy/server-deployment.yaml
- apps/argo/config/cluster/deploy/workflow-controller-deployment.yaml
- apps/knowledge/config/cluster/deploy/knowledge_deployment.yaml
Background
change argo and sync run user
1.12
Related Issues
none
none
none
> fix: change argo and sync run user

- apps/files/config/cluster/deploy/files_deploy.yaml
- Background
files:
add init container for pgsql
v1.12.0
none
none
none
> fix: add init container for files-server

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
Background
fix youtube donwload error
1.11
Related Issues
none
none
none
> download: fix youtube download failure

- apps/wizard/config/user/helm-charts/wizard/templates/wizard_deploy.yaml
- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- third-party/authelia/config/user/helm-charts/auth/templates/auth_deploy.yaml
The Olares password is transmitted in plain text during the interface transmission process, which is not secure and needs to be changed to encrypted transmission.
1.12
None
https://github.com/beclab/TermiPass/pull/422
https://github.com/beclab/Installer/pull/211
* None
> feat(login & wizard): Encrypted transmission of login password

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
support external directory, such as HDD or SMB
1.12.0
https://github.com/beclab/backup-server/pull/23
> backup-server: support external directory

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
check disk free space when backing up to local directory, api optimization
1.12.0
https://github.com/beclab/backup-server/pull/24
https://github.com/beclab/backup-server/pull/25
https://github.com/Above-Os/backups-sdk/pull/21
> backup-server: check disk free space, api optimization

- build/installer/install.ps1
- build/installer/install.sh
- build/installer/joincluster.sh
- build/manifest/images
- add some metrics for dashboard
1.12
None
https://github.com/beclab/kubesphere-ext/pull/18
https://github.com/beclab/node_exporter/pull/1
https://github.com/beclab/Installer/pull/217
node_disk_smartctl_info
node_disk_temp_celsius
node_cpu_temp_celsius
node_one_disk_utilization_ratio
node_one_disk_capacity_size
node_one_disk_avail_size
node_network_address_info
node_user_cpu_usage
node_system_cpu_usage
node_iowait_cpu_usage
node_cpu_base_frequency_hertz_max
node_disk_power_on_hours
> ks,node_exporter,installer: add some metrics

- build/manifest/images
- frameworks/bfl/config/launcher/templates/otel_define.yaml
- third-party/opentelemetry/config/cluster/deploy/opentelemetry_operator.yaml
Add opentelemetry auto instrumentation image to image manifest
v1.12.0
None
None
> olares: add otel instrumentation image to manifest

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
fix External binding, improve message pushing
1.12.0
https://github.com/beclab/backup-server/pull/26
> backup-server: fix external binding, improve message pushing

- apps/files/config/user/helm-charts/files/templates/files_fe_deploy.yaml
- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
settings: add mirror manager。
settings: fix the white screen bug in lower versions of WebView
files: add backup progress and create backup path from files
files: external right-click support HDD
1.12
None
https://github.com/beclab/TermiPass/pull/434
https://github.com/beclab/TermiPass/pull/432
https://github.com/beclab/TermiPass/pull/436
https://github.com/beclab/TermiPass/pull/430
None
> settings & files: update settings mirror manager & backup, files support backup

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- pull image progress not correct when image exist and image pull policy is Always
1.11
None
https://github.com/beclab/app-service/pull/216
> app-service: fix pull image progress

- frameworks/backup-server/config/cluster/deploy/backup_server.yaml
restore bug fix, sdk supports backup from file list
1.12.0
https://github.com/beclab/backup-server/pull/27
https://github.com/Above-Os/backups-sdk/pull/22
> backup-server: restore bug fix, sdk supports backup from file list

- apps/knowledge/config/cluster/deploy/knowledge_deployment.yaml
Background
fix twitter download failure
update larepass download
1.12
Related Issues
none
none
none
> knowledge&download: fix twitter download failure & update larepass download

- frameworks/bfl/config/launcher/templates/bfl_deploy.yaml
-  fix sub user delete issue
1.12
None
https://github.com/beclab/bfl/pull/97
https://github.com/beclab/bfl/pull/99
> bfl: fix sub user delete issue

- apps/notifications/config/cluster/deploy/notification_deploy.yaml
notification:  Make it possible for the notification server to stay in sync with user changes in the Olares system.
1. Retrieve the full user list during startup.
2. Listen for user-change events and resynchronize the user list whenever a change occurs.
1.12
https://github.com/beclab/notifications/pull/3/files
> feat: Let notification server can get users information

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
show installation status in header bar
fix some bugs
v1.11.0
none
https://github.com/beclab/system-apps/pull/41
none
> studio: show installation status in header bar

- apps/desktop/config/user/helm-charts/desktop/templates/desktop_deploy.yaml
improve data refresh logic by socket after network reconnection
v1.11.0
none
https://github.com/beclab/desktop/pull/86
none
> desktop: improve data refresh logic by socket after network reconnection

- frameworks/app-service/config/cluster/deploy/appservice_deploy.yaml
- improve api performance by use k8s informer
1.12
None
https://github.com/beclab/app-service/pull/218
https://github.com/beclab/app-service/pull/217
> app-service: improve api performance by use k8s informer

- build/manifest/images
- frameworks/bfl/config/launcher/templates/otel_define.yaml
- frameworks/system-server/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
- third-party/authelia/config/cluster/deploy/auth_backend_deploy.yaml
Replace redis client pool of session storage provider in Authelia
v1.12.0
Too many redis connections in Authelia server.
https://github.com/beclab/authelia/pull/12
> authelia: replace redis client pool of session provider

- apps/download/config/user/helm-charts/download/templates/download_deploy.yaml
- apps/knowledge/config/user/helm-charts/knowledge/templates/knowledge_deployment.yaml
Background
fix twitter download failure
fix discovery feed sync bug
1.11
Related Issues
none
none
none
> knowledge&download: fix twitter download failure & fix discovery feed sync bug

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
Upgrade the version of settings-server node and the corresponding version of nestjs
1.12
None
https://github.com/beclab/settings/pull/101
None
> feat(settings-server): upgrade node version 24.0.2  & nestjs version to 11.1.1

- apps/system-apps/config/user/helm-charts/monitoring/templates/system-frontend.yaml
1. Support 4 types of restore methods
2. Display space backup usage in settings
1.12
None
https://github.com/beclab/TermiPass/pull/445
None
> settings: restore function update and add space backup usage

- framework/app-service/.olares/config/cluster/crds/app.bytetrade.io_applicationmanagers.yaml
- framework/app-service/.olares/config/cluster/crds/app.bytetrade.io_applications.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- app installation and state transfer refactor
1.12
None
https://github.com/beclab/app-service/pull/222
> app-service: app installation refactor

- build/base-package/install.sh
- cli/cmd/ctl/os/release.go
- cli/pkg/release/app/app.go
- cli/pkg/release/builder/builder.go
- cli/pkg/release/manifest/manifest.go
update the `olares-cli release` command accordingly after the refactor of Olares repo
1.12.0
none
none
none
> cli(refactor): adjust local release logic for new project structure

- apps/.olares/config/user/helm-charts/monitoring/templates/system-frontend.yaml
- framework/authelia/.olares/config/user/helm-charts/auth/templates/auth_deploy.yaml
Fixed the issue that the desktop & login background image uploaded by the user is not displayed
1.12
None
None
None
> fix(desktop): that the customized desktop background  image does not display

- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
support restoration of wise applications
1.12
https://github.com/Above-Os/backups-sdk/pull/29
https://github.com/beclab/backup-server/pull/35
> backup-server: support app restore

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- app-service: fix some state bug
1.12
None
https://github.com/beclab/app-service/pull/224
> app-service: fix some state bug

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- app-service: fix cancel operation context
1.12
None
https://github.com/beclab/app-service/pull/225
> app-service: fix cancel operation context

- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
Background
fix backup bugs
fix remove entry file bugs 
1.12
Related Issues
none
none
none
> knowledge: fix backup & remove entry file bugs

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
market: add app status failed i18n.
settings: add backup app function.
1.12
None
https://github.com/beclab/TermiPass/pull/475
https://github.com/beclab/TermiPass/pull/474
None
> market, settings: update version to v1.3.69

- framework/gpu/.olares/config/gpu/hami/templates/gpu-scheduler/daemonset.yaml
- framework/gpu/.olares/config/gpu/hami/values.yaml
- platform/hami/.olares/Olares.yaml
Fix some GPU preload hook and scheduler bugs
v1.12.0
GPU Scheduler crashed
none
> gpu: fix gpu scheduler bugs

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
- framework/vault/.olares/config/cluster/deploy/vault_server_deploy.yaml
- app upgrade failed
- add appid to pod label
- fix call analytics-server
1.12
None
https://github.com/beclab/bfl/pull/104
https://github.com/beclab/app-service/pull/229
https://github.com/beclab/app-service/pull/228
> app-service,bfl: fix upgrade failed bug,add appid to pod label;fix call analytics-server

- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
Refactor error message extraction method, optimize application backup.
1.12
https://github.com/beclab/backup-server/pull/38
https://github.com/Above-Os/backups-sdk/pull/33
> backup-server: improve message

- framework/gpu/.olares/config/gpu/hami/values.yaml
- platform/hami/.olares/Olares.yaml
* **Background**  
When every launch kernel function is called, it should add a lock
v1.12.0
none
none
> gpu: add lock to launch kernel functions

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/authelia/.olares/config/user/helm-charts/auth/templates/auth_deploy.yaml
- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
user-service: update intent and add add all applications  nats message 
desktop: fix receive intent message error
login: fix refresh token error
dashboard: add hardware resource management
larepass: refactor quasar variables config
1.12
None
https://github.com/beclab/user-service/pull/4
https://github.com/beclab/TermiPass/pull/481
None
> feat(system-frontend): update desktop&market&user-service new version

- framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
- move USER_INDEX env to front
1.12
None
None
> fix: move USER_INDEX env to front

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
1. Fix the bug and ui in dashboard resource monitoring
2. Settings: update gpu manager
3. user-service: add manage gpu api
1.12
None
https://github.com/beclab/TermiPass/pull/491
https://github.com/beclab/TermiPass/pull/489
https://github.com/beclab/user-service/pull/5
None
> fix(system-frontend/app-service/bfl): update system-frontend , app-service and bfl

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
refactor files cloud call service
1.12
https://github.com/beclab/files/pull/24
> files: refactor cloud call service

- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
fix backup period calculation, optimize prompt message
1.12
https://github.com/beclab/backup-server/pull/39
https://github.com/beclab/backup-server/pull/40
> backup-server: fix backup period calculation

- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
Background
fix t.bilibili.com,xhs,jianshu,douban,weibo etc article extractor
1.12
Related Issues
none
none
none
> knowledge: fix article extractor bugs

- cli/pkg/release/app/app.go
- cli/pkg/release/builder/builder.go
- cli/pkg/release/manifest/manifest.go
Adjust the local release command logic to conform to the new os namespace structure 
1.12.0
none
none
none
> refactor(cli): unify local release with daily build

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/monitor/.olares/config/cluster/deploy/ks_server_deploy.yaml
1. fix dashboard ui and bugs
2. fix control-hub some bugs
3. add system namespaces at monitoring-server
4. add wise tabs and reading entry hotkeys
5. fix larepass some issues supporting Olares 1.11
1.12
none
https://github.com/beclab/TermiPass/pull/505
https://github.com/beclab/TermiPass/pull/506
https://github.com/beclab/TermiPass/pull/507
none
> feat(system-frontend/ks_server): update apps image  and monitoring server versions

- apps/.olares/config/user/helm-charts/market/templates/market_deploy.yaml
- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
- framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml
- framework/seahub/.olares/config/cluster/deploy/seafile_deploy.yaml
- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
- framework/vault/.olares/config/cluster/deploy/vault_server_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/ks-component.yaml
- platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- platform/tapr/.olares/config/cluster/deploy/middleware_deploy.yaml
-  change nats subjet name
1.12
None
> tapr: change nats subjet name

- cli/pkg/common/kube_runtime.go
- daemon/Makefile
- daemon/internel/apiserver/handler_ifs.go
- daemon/pkg/cluster/state/current.go
- daemon/pkg/cluster/state/terminus.go
- daemon/pkg/utils/network_common.go
- daemon/pkg/utils/network_linux.go
- daemon/pkg/utils/system.go
Persist the user name to the Olares release file
v1.12.0
none
none
> cli, daemon: persist the user name to the Olares release file

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/monitor/.olares/config/cluster/deploy/ks_server_deploy.yaml
1. change control-hub network policies YAML to readonly
2. fix dashboard network some bugs
1.12
https://github.com/beclab/Olares/issues/1453
https://github.com/beclab/TermiPass/pull/508
https://github.com/beclab/TermiPass/pull/509
none
> feat(system-frontend): update dashboard, control hub, and settings image

- framework/system-server/.olares/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- lldap pub event async
1.12
None
https://github.com/beclab/lldap/pull/11
https://github.com/beclab/lldap/pull/10
https://github.com/beclab/system-server/pull/10
> lldap,system-server: pub event async; chanage secret ns

- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
Background
add ManyBooks,Standardebooks,z-Library download
add okjike article extractor
1.12
Related Issues
none
none
none
> feat(knowledge): add ebook , pdf download and article extractor

- infrastructure/gpu/.olares/config/gpu/hami/templates/gpu-scheduler/daemonset.yaml
Refactor gpu scheduler with cpp
v1.12.0
none
none
> gpu: refactor gpu scheduler with cpp

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
Fix system-frontend nginx configuration error
1.12
None
None
None
> fix(system-frontend): copy nginx  address error

- daemon/cmd/terminusd/main.go
- daemon/internel/mdns/server.go
- daemon/internel/watcher/cert/user_cert_watcher.go
- daemon/pkg/commands/collect_logs/cmd.go
- daemon/pkg/utils/drivers_linux.go
- daemon/pkg/utils/k8s.go
- daemon/pkg/utils/network_linux.go
Watch the users' HTTP certs, if the certificate will expire within 10 days, create a job to refresh the certs. 
v1.12.0
User's certs were not refreshed if the cluster is not running at the certs refresh time.
none
> olaresd: refresh user expiring certs

- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
Background
download move to  system space,there are issues with canceling and continuing tasks, fix this problem
reduce API requests when retrieving youtube playlists.
v1.12.0
Related Issues
none
none
> fix(download): fix download task operation & reduce youtube API requests

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
profile: fix display error in avatar selector's image list
market: clear market data when terminusId changes and update local data when a new app version is published
1.12
None
https://github.com/beclab/TermiPass/pull/533
https://github.com/beclab/TermiPass/pull/534
https://github.com/beclab/TermiPass/pull/535
https://github.com/beclab/market/releases/tag/v0.4.6
None
> market, profile: fix display error in avatar selector's image list and clear market data when terminusId changed

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
When deploying multiple nodes in the olares system, corresponding operations need to be performed on the corresponding nodes.
files-frontend: supports multiple nodes
1.12
None
https://github.com/beclab/TermiPass/pull/542
https://github.com/beclab/files/pull/25
https://github.com/beclab/files/pull/30
https://github.com/beclab/files/pull/33
None
> feat(files): files supports multiple nodes

- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: hybrid unigram search for title
daily build
* https://github.com/Above-Os/search3/pull/83
* https://github.com/Above-Os/search3/pull/82
> feat: hybrid unigram search for title

- .github/workflows/check.yaml
- .github/workflows/push-deps-to-s3.yml
- .github/workflows/push-to-s3.yaml
- .github/workflows/release-cli.yaml
- .github/workflows/release-daemon.yaml
- .github/workflows/release-daily.yaml
- .github/workflows/release.yaml
- build/build-manifest.py
- build/build-manifest.sh
- build/deps-manifest.sh
- cli/pkg/release/builder/builder.go
- daemon/.olares/Olares.yaml
Add a parameter of the code repository to upload the release packages to a specific publish storage
v1.12.0
none
none
> ci: add a parameter of the code repository

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
Title: <subsystem>:  <what changed>
files: fix bugs in files, including file deletion and image preview functionality.
market: the menu categories and multilingual configurations for each section are configured by the central platform
1.12
https://github.com/beclab/files/pull/36
https://github.com/beclab/TermiPass/pull/546
https://github.com/beclab/TermiPass/pull/547
> fix(files): deletion and other fixes

- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
1. Send notification in the user login phase
2. Fix listing user tokens bug
v1.12.0
Crash when calling the listing user tokens api 
https://github.com/beclab/authelia/pull/19
> authelia: send notification in user login phase

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- framework/knowledge/.olares/config/cluster/deploy/knowledge_deployment.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
- framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml
- framework/seahub/.olares/config/cluster/deploy/seafile_deploy.yaml
- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
- framework/studio/.olares/config/cluster/deploy/studio_deploy.yaml
- framework/vault/.olares/config/cluster/deploy/vault_server_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/ks-component.yaml
- platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- simplify nat permission request
1.12
None
None
> fix: simplify nat permission request

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/authelia/.olares/config/user/helm-charts/auth/templates/auth_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
fix delete external files
fix files some frontend bug
1.12
https://github.com/beclab/files/pull/37
https://github.com/beclab/TermiPass/pull/550
> fix(files): external delete

- daemon/cmd/terminusd/main.go
- daemon/internel/apiserver/handlers/command_group.go
- daemon/internel/apiserver/handlers/containerd_group.go
- daemon/internel/apiserver/handlers/handler_change_host.go
- daemon/internel/apiserver/handlers/handler_collect_logs.go
- daemon/internel/apiserver/handlers/handler_connect_wifi.go
- daemon/internel/apiserver/handlers/handler_containerd.go
- daemon/internel/apiserver/handlers/handler_hosts.go
- daemon/internel/apiserver/handlers/handler_ifs.go
- daemon/internel/apiserver/handlers/handler_mount_smb.go
- daemon/internel/apiserver/handlers/handler_mount_smb_v2.go
- daemon/internel/apiserver/handlers/handler_mounted_hdd.go
- daemon/internel/apiserver/handlers/handler_mounted_path.go
- daemon/internel/apiserver/handlers/handler_mounted_smb.go
- daemon/internel/apiserver/handlers/handler_mounted_usb.go
- daemon/internel/apiserver/handlers/handler_olares_upgrade.go
- daemon/internel/apiserver/handlers/handler_reboot.go
- daemon/internel/apiserver/handlers/handler_shutdown.go
- daemon/internel/apiserver/handlers/handler_terminus_init.go
- daemon/internel/apiserver/handlers/handler_terminus_state.go
- daemon/internel/apiserver/handlers/handler_terminus_uninstall.go
- daemon/internel/apiserver/handlers/handler_umount_smb.go
- daemon/internel/apiserver/handlers/handler_umount_usb.go
- daemon/internel/apiserver/handlers/handlers.go
- daemon/internel/apiserver/handlers/in_cluster.go
- daemon/internel/apiserver/handlers/middlewares.go
- daemon/internel/apiserver/handlers/system_group.go
- daemon/internel/apiserver/server.go
- daemon/internel/apiserver/server/api.go
1. Refactoring `olaresd` api server into modular
2. Add node host name field to /system/ifs api
v1.12.0
none
none
> olaresd: refactor api server

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
- framework/system-server/.olares/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
- platform/open-telemetry/.olares/config/cluster/deploy/opentelemetry_operator.yaml
Disable telemetry by default
v1.12.0
none
none
> otel: disable telemetry by default

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
- framework/l4-bfl-proxy/.olares/Olares.yaml
- framework/studio/.olares/config/cluster/deploy/studio_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/middleware_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/sys_event_deploy.yaml
- fit new user owner role
1.12
None
https://github.com/beclab/bfl/pull/115
https://github.com/beclab/devbox/pull/55
https://github.com/beclab/tapr/pull/68
https://github.com/beclab/authelia/pull/23
> bfl, studio, tapr, authelia: fit new user owner role

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- some app entrance never become ready
- workflow install
1.12
None
https://github.com/beclab/app-service/pull/252
https://github.com/beclab/app-service/pull/253
> app-service: correct entrance status;workflow install

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
fix settings & market some bugs
1.12
None
https://github.com/beclab/TermiPass/pull/561
https://github.com/beclab/TermiPass/pull/562
none
> system-frontend&market: release new version

- README.md
- README_CN.md
- docs/.vitepress/config.mts
- docs/README.md
> Docs: revert search provider to agolia  

- build/build-manifest.py
So that we can calculate dynamically how much space is needed for an upgrade by a diff between the manifest and the local cache of downloaded files , along with existing layers in Containerd
1.12.0
none
none
none
> feat(ci): record cdn object file size in manifest

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- fix admin reset password
- refresh token expiry 
1.12
None
https://github.com/beclab/app-service/pull/254
https://github.com/beclab/lldap/pull/14
> app-service, lldap: fix admin reset password;refresh token expiry

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
dashboard&settings&desktop: fix some bugs
backup&user-service: add nats message
1.12
None
https://github.com/beclab/user-service/pull/10
https://github.com/beclab/TermiPass/pull/569
https://github.com/beclab/TermiPass/pull/568
https://github.com/beclab/TermiPass/pull/564
None
> dashboard&settings&desktop&backup&user-service: fix some bugs and add backup nats message

- framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
Avoiding nftables firewall rule conflicts.
1.12.0
> fix: nftables only for owner

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
1. move socket to sharedworker
2. fix some ui bugs
1.12
None
https://github.com/beclab/TermiPass/pull/576
None
> system-frontend: move socket to sharedworker and fix some ui bugs

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
Background
Support intent messages through NATS.
1.12.0
Related Issues
none
none
none
> feat: add intent sub pub on market and user-service

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
update the global External data during mount
1.12
https://github.com/beclab/files/pull/41
> fix(files): update global external data on mount

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/vault/.olares/config/cluster/deploy/vault_server_deploy.yaml
desktop: fix remove app request error
settings: backup and restore only in master node
wise: preview url and nginx config,
settings:  gpu page copy and owner role copy,
market & settings:  resume, stop status limit
vault-server: fix nats topic error
others
1.12
None
https://github.com/beclab/TermiPass/pull/583
https://github.com/beclab/TermiPass/pull/582
https://github.com/beclab/TermiPass/pull/579
> vault-server,vault-admin,system-frontend: update system-frontend some bugs

- framework/app-service/.olares/config/cluster/crds/app.bytetrade.io_applicationmanagers.yaml
- framework/app-service/.olares/config/cluster/crds/app.bytetrade.io_imagemanagers.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- support v2 install
- operate app by crd
- user event publish to nats
1.12
https://github.com/beclab/app-service/pull/256
https://github.com/beclab/app-service/pull/257
https://github.com/beclab/app-service/pull/258
> app-service: support v2 install;operate app by crd;user event publish to nats

- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
wise svc change
1.12
https://github.com/beclab/backup-server/pull/50
> fix(backup): wise svc upgrade

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/app-service/.olares/config/cluster/crds/app.bytetrade.io_applicationmanagers.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- fix some app-service bug
- user-service nats auth error
1.12
None
https://github.com/beclab/app-service/pull/262
https://github.com/beclab/app-service/pull/261
https://github.com/beclab/app-service/pull/260
https://github.com/beclab/app-service/pull/259
> app-service,user-service: fix wehbook,uninstall bug; user-service nats auth error

- daemon/pkg/commands/upgrade/check.go
- daemon/pkg/commands/upgrade/utils.go
Optimized several prechecks before upgrade:
When a node has pressures, the `Ready` condition may still be true, so specific pressure conditions are checked
When checking for available space before downloading & image-importing, if the target path is the same as the K8s' root path, available space >10% after usage is also checked.
1.12.0
none
none
none
> fix(daemon): optimize disk space and node health check before upgrade

- framework/chart-repo/.olares/config/cluster/deploy/chart_repo_deploy.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
Title: market, chart-repo:  Split the chart repo included in the market into a separate program
Because there are multiple programs/components that depend on the chart repo, and these programs/components should not depend on the market, so the two are separated
1.12.0
none
https://github.com/beclab/market/commit/344c771cf8f378ba175b672d310acac23168a41c
https://github.com/beclab/market/commit/572f697e916ef61fa750e436d507e483215f1ebf
https://github.com/beclab/market/commit/5c5f9ea0cd73d3e1b765696e51a207ef284054a9
none
> feat:add dynamic chart repository

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml
notification: fix get template error
user-service: add wise & translate ability api
system-frontend: fix some bugs
1.12
None
https://github.com/beclab/TermiPass/pull/589
https://github.com/beclab/TermiPass/pull/588
https://github.com/beclab/user-service/pull/12
None
> notification-api,user-service,system-frontend: fix notification error & fix system-frontend bugs

- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
NATS service check
1.12
https://github.com/beclab/backup-server/pull/51
> fix(backup): nats service check

- cli/pkg/upgrade/1_12_0_20250728.go
- cli/pkg/upgrade/version.go
Add tasks to upgrade K3s and GPU plugin for daily build 0728
1.12.0
none
https://github.com/beclab/Olares/pull/1629
https://github.com/beclab/Olares/pull/1632
none
> feat(upgrade): add upgrade tasks for K3s and GPU plugin

- cli/pkg/upgrade/1_12_0_20250729.go
- cli/pkg/upgrade/version.go
Switch the breaking change upgrader for the missed daily release version 0728 to current 0729
none
none
none
none
> fix(upgrade): switch upgrader for 0728 to 0729

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
market: change open application with user service
desktop: fix the app entrance status
1.12
None
https://github.com/beclab/TermiPass/pull/604
https://github.com/beclab/TermiPass/pull/603
https://github.com/beclab/user-service/pull/16
None
> feat: update system frontend and user service version

- infrastructure/gpu/.olares/config/gpu/hami/values.yaml
- platform/hami/.olares/Olares.yaml
Bump hami-core to v2.6.0
none
none
none
> hami: sync hami-core 2.6.0

- .github/workflows/check.yaml
- .github/workflows/release-daily.yaml
- build/base-package/install.sh
- build/base-package/joincluster.sh
- build/base-package/version.hint
- cli/cmd/ctl/os/release.go
Bump developing version to 1.12.1
v1.12.1
none
none
> ci: bump version to 1.12.1

- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
Updated NATS to the latest version (1.31.0 -> 1.44.0), which includes functional updates and bug fixes for connection, message sending and receiving, and memory management
1.12.0
https://github.com/beclab/market/commit/29bc1c96e8e8df15a56510bebdfe8374aa689fef
> fix: nats upversion to 1.44.0 for market

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- fix downloading limit
- user create failed bug
1.12
None
https://github.com/beclab/app-service/pull/275
https://github.com/beclab/app-service/pull/274
> app-service: fix downloading limit;user create failed bug

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- files api has changed
1.12
None
https://github.com/beclab/app-service/pull/276
> fix: use new files api to delete app cache dir

- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
After the NATS upgrade, the receiving of messages changed from serial to parallel, resulting in unexpected concurrent logic.
1.12.0
https://github.com/beclab/market/commit/d23c4b83eeddc51e610460047cc745d95337b26b
> fix: nats message concurrent

- daemon/internel/watcher/cert/user_cert_watcher.go
- daemon/pkg/cluster/state/utils.go
1. Fix the wrong service name
2. Fix the re-creating download-cert job bug
v1.12.0 v1.12.1
none
none
> daemon: fix recreate download-cert job bug

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- v2 upgrade failed
- cs chart render error
1.12
None
https://github.com/beclab/app-service/pull/279
> fix: v2 upgrade and cs chart render

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- set concurrent downloads to 1
1.12.0
None
https://github.com/beclab/app-service/pull/281
> app-service: set concurrent downloads to 1

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
market: the minimization issue in Market has also been fixed, and the sidebar now stays permanently visible.
settings: the units for memory/CPU usage have been standardized.
wise: issues with the right sidebar and image stretching in Wise have been addressed.
1.12
None
https://github.com/beclab/TermiPass/pull/625
None
> system-frontend: update system frontend version to v1.3.126

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- sync users group error
1.12.0
None
https://github.com/beclab/app-service/pull/282
> fix: sync users group error

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
integrate rclone and improve the seahub YAML
1.12.1
https://github.com/beclab/files/pull/47
> ci: integrate rclone, seahub replace

- docs/.vitepress/en.ts
- docs/.vitepress/zh.ts
- docs/developer/develop/package/manifest.md
- docs/developer/install/index.md
- docs/developer/install/linux-via-docker-compose.md
- docs/developer/install/windows-via-docker-image.md
- docs/zh/developer/develop/package/manifest.md
- docs/zh/developer/install/index.md
- docs/zh/developer/install/linux-via-docker-compose.md
- docs/zh/developer/install/reusables.md
- docs/zh/developer/install/windows-via-docker-image.md
Exposed additional installation methods on docs and update Docker installation for Linux and WSL
1.12, Dev
None
None
> docs: expose other installation methods

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- framework/l4-bfl-proxy/.olares/Olares.yaml
- support creator name cli
1.12
None
https://github.com/beclab/l4-bfl-proxy/pull/6
https://github.com/beclab/bfl/pull/118
https://github.com/beclab/bfl/pull/117
https://github.com/beclab/app-service/pull/286
> app-service, l4, bfl: support creator cli

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
rename, create file and copy with rclone
sync rename, batch copy & move, copy/move
1.12.1
https://github.com/beclab/files/pull/51
https://github.com/beclab/files/pull/52
https://github.com/beclab/files/pull/53
https://github.com/beclab/files/pull/54
> ci(files): rename, create file and copy with rclone

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
files: add sync get shared api
dashboard: fix axios error
settings: add video config
user-service: add video config api & remove some unused bfl api
1.12.1
None
https://github.com/beclab/TermiPass/pull/642
https://github.com/beclab/TermiPass/pull/641
https://github.com/beclab/user-service/pull/18
https://github.com/beclab/user-service/pull/19
None
> feat(system-frontend): update system-frontend new version

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
-  improve performance of retrieving image layer information
- myapps with stable app sort
- authelia ttlcache panic bug
1.12
None
https://github.com/beclab/app-service/pull/289
https://github.com/beclab/app-service/pull/290
https://github.com/beclab/app-service/pull/291
https://github.com/beclab/authelia/pull/32
> app-service, authelia: fix myapps app sort and authelia ttlcache panic bug

- platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- add some auth log for debug
1.12
None
https://github.com/beclab/lldap/pull/22
> lldap: add some auth log

- framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml
- framework/system-server/.olares/config/user/helm-charts/systemserver/templates/systemserver_deploy.yaml
Remove redundant service of notifications-server
v1.12.1
none
https://github.com/beclab/system-server/pull/12
> notifications: remove redundant notification service

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
Title: <subsystem>:  <what changed>
The presence of special characters such as $ causes video playback to fail.
v1.12.1
> fix: play failed for some special characters

- apps/.olares/config/user/helm-charts/system-apps/templates/system-frontend.yaml
- framework/chart-repo/.olares/config/cluster/deploy/chart_repo_deploy.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
market: support multi-source
files: fix video play path format error
desktop: fix market open app error
v1.12.1
None
https://github.com/beclab/TermiPass/pull/654
https://github.com/beclab/TermiPass/pull/653
None
> feat(system-frontend): market support multi-source and fix some bugs

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
- apps/.olares/config/user/helm-charts/system-apps/templates/ui.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
- framework/bfl/.olares/config/launcher/templates/bfl_deploy.yaml
- merge multiple applications into one with multi entrances
- node resource pressure event publish
1.12
None
https://github.com/beclab/app-service/pull/293
https://github.com/beclab/app-service/pull/294
https://github.com/beclab/app-service/pull/295
https://github.com/beclab/bfl/pull/120
https://github.com/beclab/authelia/pull/33
https://github.com/beclab/bfl/pull/122
> app-service,bfl,auth: merge multiple applications into one

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- Background
files hertz-thrift recons: all apis replaced
1.12.1
https://github.com/beclab/files/pull/71
> feat: files hertz-thrift recons: all apis replaced

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- framework/seahub/.olares/config/cluster/deploy/seafile_deploy.yaml
- Background
fix files parse form bug
remove seahub from deployment yaml
replace nignx for seafile
copy sync to cloud
1.12.1
https://github.com/beclab/files/pull/72
https://github.com/beclab/files/pull/74
> fix: files parse form bug & remove seahub & replace nginx for seafile

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
- restrict user-service nats permission
1.12
None
None
> fix: restrict user-service nats permission

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
desktop: fix profile open error
settings: add hardware ui
1.12.1
None
https://github.com/beclab/user-service/pull/23
https://github.com/beclab/TermiPass/pull/667
https://github.com/beclab/TermiPass/pull/669
> system-frontend, user-service: release new version

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
files: fix nginx error
v1.12.1
None
https://github.com/beclab/TermiPass/pull/675
None
> feat(system-frontend): release new version to v1.4.18

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
market: mage size update
1.12.1
None
https://github.com/beclab/TermiPass/pull/676
None
> feat: update system frontend version to v1.4.19

- README.md
- README_CN.md
- README_JP.md
Title: <subsystem>:  <what changed>
> Update readme: fix architecture link

- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
> fix(backup): remove hostNetwork

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
1. Search the provider in both the installation market source and the official market source
2. Fix the app-service provider proxy address for the user-service
v1.12.1
Cannot create a new user in the Settings
https://github.com/beclab/app-service/pull/305
> app-service: search provider in both installation and official market source

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
Supports media-server settings
1.12.1
> feat: support most encoding settings

- platform/tapr/.olares/config/cluster/deploy/lldap-deployment.yaml
- platform/tapr/.olares/config/cluster/deploy/nats_deployment.yaml
- add system-cluster-critical to lldap,nats
1.12
None
None
> fix: add system-cluster-critical to lldap,nats

- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
fix sync write error for duplicate file names during upload and download, sync progress calculation error, sync duplicate file downloads.
1.12.1
https://github.com/beclab/files/pull/88
> fix: sync duplicate file name

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
- framework/notifications/.olares/config/cluster/deploy/notification_deploy.yaml
desktop: add notification
files: fix some bugs
1.12.1
None
https://github.com/beclab/TermiPass/pull/692
https://github.com/beclab/TermiPass/pull/690
https://github.com/beclab/notifications/pull/4
https://github.com/beclab/user-service/pull/25
None
> feat(system-frontend): add desktop notification

- framework/headscale/.olares/config/user/helm-charts/headscale/templates/headscale_deploy.yaml
disable provider for headscale api wrapper
1.12.1
> feat: update headscale api wrapper without using provider mechanism

- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: search3monitor memory leak
when create dir, handle dir failed, need to remove data from WATCH_PATH_TO_TASK_ID map
daily build
https://github.com/Above-Os/search3/pull/112
> fix: fix monitor memory leak

- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: search3 server memory optimization
search3 server does not detect language, and does not cache user's language
daily build
https://github.com/Above-Os/search3/pull/113
> feat: search3 server memory optimzation

- docs/README.md
Change from https://one.olares.com to https://www.olares.com
1.12.1
None
None
None
> Reset official link

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
desktop: fix nginx setting server error
wise: add block list function
1.12
None
https://github.com/beclab/TermiPass/pull/704
None
> feat: update system frontend version to v1.4.28

- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: search3 monitor refactor
search3 refactor
daily build
https://github.com/Above-Os/search3/pull/114
> feat: refactor monitor

- framework/market/.olares/config/cluster/deploy/market_deploy.yaml
There are a lot of synchronization, rendering, and status checking tasks in the market, which all operate on memory. In order to ensure data correctness, many tasks are serialized. This submission is to optimize as many tasks as possible to parallelize them.
1.12.1
https://github.com/beclab/market/commit/0fdfacc026dfa636ba873b40d7b76f4a6448aaaf
> fix: Optimizing task execution

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/files/.olares/config/cluster/deploy/files_deploy.yaml
- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
- platform/tapr/.olares/config/cluster/deploy/middleware_deploy.yaml
Add a higher priority class to some system services
v1.12.1 v1.12.2
Critical system services had been evicted
none
> olares: add priority class to some system services

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
market: update add source dialog prompt text
settings: delete acl error
1.12.1
None
https://github.com/beclab/TermiPass/pull/713
https://github.com/beclab/TermiPass/pull/714
None
> system frontend: update system frontend to v1.4.33 

- apps/.olares/config/user/helm-charts/system-apps/templates/olares-app.yaml
user-service: fix sign message send to LarePass error
settings: fix gpu page error
1.12.1
None
https://github.com/beclab/user-service/pull/30
https://github.com/beclab/TermiPass/pull/717
None
> feat(system-frontend): release new version to v1.4.35

- framework/search3/.olares/config/cluster/deploy/search3_server_deploy.yaml
Title: aboveos/search3: fix error
allow search3server, search3monitor receive os.users message from nats
daily build
* **PRs Involving Sub-Systems**
> feat: allow search3 search3monitor receiver os.users nats message

- framework/app-service/.olares/config/cluster/deploy/appservice_deploy.yaml
- framework/authelia/.olares/config/cluster/deploy/auth_backend_deploy.yaml
- framework/backup-server/.olares/config/cluster/deploy/backup_server.yaml
- framework/osnode-init/.olares/config/cluster/deploy/nodeinit_daemonset.yaml
- platform/tapr/.olares/config/cluster/deploy/sys_event_deploy.yaml
Remove authentication with backend nonce, using the RBAC proxy instead
v1.12.2
none
none
> authelia: remove authentication with backend nonce

- daemon/internel/client/validate.go
- daemon/pkg/utils/jws.go
Remove redundant slash on did-gate-url
v1.12.2
Check jws failed
none
> daemon: did-gate-url bug
